import * as api from './index';
import { platformRpc } from './platformSupabaseClient';
import { listPlatformCompanies } from './platformCompanyDirectoryService';
import { getServiceMode } from '@/lib/services/mode';
import type { PlatformCapability, PlatformDashboardSummary, PlatformRoleKey, PlatformUserStatus } from '@/types/platformConsole';
import type { ServiceResult } from '@/types/core/base';
import { consoleDate, consoleEuros, consoleLabel, consoleMoney, consoleSettingValue, consoleText, isSensitiveSetting, validConsoleDay, type ConsoleRow } from './consoleWorkspaceModel';

export type ConsoleSection = 'dashboard' | 'tenants' | 'plans' | 'addons' | 'modules' | 'discounts' | 'billing' | 'payments' | 'feature-flags' | 'users' | 'audit' | 'system' | 'releases';
export type ConsoleColumn = { key: string; label: string; format?: 'money' | 'date' | 'status' | 'boolean'; };
export type ConsoleSectionInfo = { title: string; subtitle: string; description: string; empty: string; capability?: PlatformCapability; columns: ConsoleColumn[]; };
const c = (key: string, label: string, format?: ConsoleColumn['format']): ConsoleColumn => ({ key, label, format });
export const CONSOLE_SECTIONS: Record<ConsoleSection, ConsoleSectionInfo> = {
  dashboard: { title: 'Dashboard', subtitle: 'Die Plattform im Überblick', description: 'Registrierungen, offene Vorgänge und Veränderungen an einem Ort. Öffnen Sie einen Vorgang, um direkt im zuständigen Bereich weiterzuarbeiten.', empty: '', columns: [] },
  tenants: { title: 'Mandanten', subtitle: 'Unternehmen und Zusammenarbeit', description: 'Alle registrierten Unternehmen mit Einrichtungsstand, Ansprechpartnern, Datenumgebung und Vertragsstatus. Die Unternehmensakte verbindet Stammdaten, Zugriffe, Finanzen und Support.', empty: 'Es liegen noch keine passenden Unternehmen vor. Neue Firmen erscheinen nach ihrer Registrierung automatisch in dieser Übersicht.', capability: 'tenants.read', columns: [c('tenantName','Unternehmen'),c('environmentMode','Umgebung','status'),c('lifecycleStatus','Einrichtung','status'),c('billingStatus','Nutzung','status'),c('status','Zugriff','status'),c('createdAt','Registriert','date')] },
  plans: { title: 'Tarife & Verträge', subtitle: 'Kostenlose Nutzung und Vertragsbestand', description: 'CareSuite HealthOS ist kostenlos. Hier verwalten Sie die Vertragsgrundlagen und nachvollziehbare Versionen. Bestehende abweichende Konditionen bleiben sichtbar und werden nicht automatisch verändert.', empty: 'Es sind noch keine Vertragsmodelle hinterlegt. Sie können den kostenlosen Plattformvertrag mit 0 € anlegen.', capability:'plans.read', columns:[c('plan_name','Vertragsmodell'),c('plan_key','Kennung'),c('monthly_price_cents','Monat','money'),c('yearly_price_cents','Jahr','money'),c('status','Status','status'),c('is_public','Öffentlich','boolean')] },
  addons: { title: 'Erweiterungen', subtitle: 'Zusätzliche Angebote und Versionen', description: 'Erweiterungen mit Zweck, Status und Versionshistorie verwalten und gezielt einem Unternehmen zuordnen. Die kostenlose Grundnutzung der Plattform bleibt davon unabhängig.', empty:'Es sind keine Erweiterungen hinterlegt. Legen Sie ein Angebot nur an, wenn es tatsächlich bereitgestellt werden kann.', capability:'plans.read', columns:[c('addon_name','Erweiterung'),c('addon_key','Kennung'),c('description','Beschreibung'),c('status','Status','status')] },
  modules: { title:'Funktionskatalog', subtitle:'Produktumfang und Verfügbarkeit', description:'Verwalten Sie die im Produkt hinterlegten Funktionen, ihre Beschreibung und ihren Freigabestatus. Abhängigkeiten und interne Kennzeichnungen sind in den Details sichtbar. Die Firmenregistrierung benötigt keine Funktionsauswahl.', empty:'Der Produktkatalog enthält noch keine Funktionen. Ein Katalogeintrag beschreibt eine bestehende Implementierung; er erzeugt keine neue Softwarefunktion.', capability:'modules.read', columns:[c('module_name','Funktion'),c('category','Kategorie'),c('status','Verfügbarkeit','status'),c('is_core','Grundfunktion','boolean'),c('is_internal','Intern','boolean'),c('updated_at','Geändert','date')] },
  discounts: { title:'Rabatte & Sonderkonditionen', subtitle:'Katalog und gültige Zuweisungen', description:'Nachlässe transparent dokumentieren, zeitlich begrenzen und Unternehmen zuordnen. Für eine kostenlose Nutzung ist kein Rabatt erforderlich. Bestehende Sondervereinbarungen lassen sich weiterhin nachvollziehen.', empty:'Es sind keine Sonderkonditionen angelegt. Bei einer kostenlosen Nutzung ist dies der reguläre Zustand.', capability:'discounts.read', columns:[c('discount_name','Bezeichnung'),c('discount_key','Code'),c('discount_type','Art'),c('display_value','Wert'),c('status','Status','status')] },
  billing: { title:'Rechnungen', subtitle:'Fälligkeiten und Rechnungsstand', description:'Verwalten Sie Plattformrechnungen und manuell vereinbarte Leistungen. Die Übersicht enthält keine Leistungsabrechnungen der Mandanten mit ihren Klient:innen. Die kostenlose Grundnutzung erzeugt keine laufenden Plattformkosten.', empty:'Es liegen keine Plattformrechnungen vor. Für die kostenlose Grundnutzung ist keine Rechnung erforderlich.', capability:'billing.read', columns:[c('invoice_number','Rechnung'),c('tenant_label','Unternehmen'),c('amount_cents','Brutto','money'),c('net_cents','Netto','money'),c('status','Status','status'),c('due_at','Fällig','date')] },
  payments: { title:'Zahlungen', subtitle:'Zahlungseingänge und Zuordnung', description:'Prüfen Sie Zahlungseingänge, fehlgeschlagene Vorgänge und die Zuordnung zu Plattformrechnungen. Manuelle Erfassung dokumentiert einen tatsächlichen Zahlungsvorgang; sie führt keine Banküberweisung aus.', empty:'Es sind keine Zahlungen erfasst. Bei kostenloser Plattformnutzung sind keine regelmäßigen Zahlungseingänge zu erwarten.', capability:'payments.read', columns:[c('tenant_label','Unternehmen'),c('invoice_label','Rechnung'),c('amount_cents','Betrag','money'),c('provider','Quelle'),c('status','Status','status'),c('created_at','Erfasst','date')] },
  'feature-flags': { title:'Feature Flags', subtitle:'Gezielte technische Freigaben', description:'Technische Funktionen kontrolliert plattformweit oder für einzelne Mandanten freigeben. Prüfen Sie Geltungsbereich und Rollout vor jeder Änderung. Ein Schalter wirkt nur auf Funktionen, die ihn in der Anwendung auswerten.', empty:'Es sind noch keine technischen Freigaben angelegt. Neue Schalter benötigen einen passenden Schlüssel aus der implementierten Funktion.', capability:'flags.read', columns:[c('flag_name','Funktion'),c('flag_key','Schlüssel'),c('scope','Geltungsbereich'),c('tenant_label','Unternehmen'),c('enabled','Aktiv','boolean'),c('rollout_label','Rollout'),c('updated_at','Geändert','date')] },
  users:{ title:'Benutzer & Rollen', subtitle:'Zugriffe auf die Plattformverwaltung', description:'Plattformzugriffe prüfen und Rollen gezielt vergeben. Die Rechteübersicht erklärt, welche Bereiche eine Rolle lesen oder verändern darf. Mitarbeitende und Klient:innen werden innerhalb ihrer jeweiligen Unternehmensakte verwaltet.', empty:'Für die gewählten Filter wurden keine Plattformbenutzer gefunden.', capability:'users.read', columns:[c('full_name','Name'),c('email','E-Mail'),c('role','Rolle','status'),c('status','Zugriff','status'),c('last_login_at','Letzte Anmeldung','date')] },
  audit:{title:'Audit & Verlauf',subtitle:'Änderungen nachvollziehen',description:'Wer hat wann was geändert und warum? Öffnen Sie einen Eintrag für Ausgangswert, Ergebnis, Ziel und Begründung. Zeitraum, Unternehmen und Aktion lassen sich eingrenzen; Exporte enthalten ausschließlich die angezeigte Auswahl.',empty:'Für die ausgewählten Filter liegen keine Audit-Einträge vor.',capability:'audit.read',columns:[c('created_at','Zeitpunkt','date'),c('action','Aktion'),c('actor_role','Rolle'),c('tenant_label','Unternehmen'),c('target_type','Bereich'),c('reason','Begründung')]},
  system:{title:'System',subtitle:'Globale Einstellungen kontrollieren',description:'Globale Konfiguration einsehen und mit Begründung ändern. Wahrheitswerte, Zahlen und Texte werden passend bearbeitet; geschützte Einstellungen bleiben maskiert. Auswirkungen ergeben sich aus der jeweiligen Funktion, die diese Einstellung verwendet.',empty:'Es wurden keine Systemeinstellungen gefunden. Prüfen Sie die Datenbankanbindung und den eingerichteten Konfigurationsbestand.',capability:'system.read',columns:[c('display_name','Einstellung'),c('display_value','Aktueller Wert'),c('description','Bedeutung'),c('updated_at','Geändert','date')]},
  releases:{title:'Releases',subtitle:'Bereitstellungen und Prüfergebnisse',description:'Version, Umgebung, Commit, Datenbankstand und tatsächliche Prüfergebnisse dokumentieren. Das Register macht Bereitstellungen nachvollziehbar; ein Eintrag löst keine Veröffentlichung aus.',empty:'Es sind noch keine Releases registriert. Dokumentieren Sie eine tatsächlich geplante oder ausgeführte Bereitstellung mit dem zugehörigen Prüfstand.',capability:'releases.read',columns:[c('version_label','Version'),c('environment','Umgebung','status'),c('status','Ergebnis','status'),c('commit_sha','Commit'),c('migration_version','Datenbankstand'),c('deployed_at','Erfasst','date')]},
};
export const SETTING_NAMES: Record<string,string> = { maintenance_mode:'Wartungsmodus', default_trial_days:'Testzeitraum für Bestandsverträge', support_session_minutes:'Dauer einer Support-Sitzung', invoice_due_days:'Zahlungsziel in Tagen', platform_notice:'Plattformhinweis', registration_enabled:'Firmenregistrierung', free_platform_enabled:'Kostenlose Plattformnutzung' };
export type ConsoleQuery = { search: string; status: string; tenantId: string; offset: number; start?:string; end?:string; };
export type ConsoleData = { rows: ConsoleRow[]; tenants: ConsoleRow[]; related: ConsoleRow[]; warnings: string[]; hasMore: boolean; summary?: PlatformDashboardSummary; };
async function unwrap<T>(promise: Promise<ServiceResult<T>>): Promise<T> { const result = await promise; if (!result.ok) throw new Error(result.error); return result.data; }
const rows = async (promise: Promise<ServiceResult<unknown>>): Promise<ConsoleRow[]> => await unwrap(promise) as ConsoleRow[];

export async function loadConsoleData(section: ConsoleSection, query: ConsoleQuery, role: PlatformRoleKey | undefined): Promise<ConsoleData> {
  const result: ConsoleData = { rows:[], tenants:[], related:[], warnings:[], hasMore:false };
  const can = (capability: PlatformCapability) => api.platformRoleHasCapability(role, capability);
  // Auxiliary permission failures never erase the main page.
  const tenantSections: ConsoleSection[] = ['billing','payments','feature-flags','discounts','audit','plans','addons'];
  const directory = tenantSections.includes(section) && can('tenants.read') ? (async()=>{ let offset=0; for(;;){const data=await unwrap(listPlatformCompanies({limit:200,offset}));result.tenants.push(...data.items as unknown as ConsoleRow[]);if(data.items.length<200)break;offset+=200;} })().catch(error => { result.warnings.push(`Unternehmensnamen: ${error.message}`); }) : Promise.resolve();
  switch(section) {
    case 'tenants': { const data = await unwrap(listPlatformCompanies({ search:query.search || undefined,status:query.status || undefined,limit:51,offset:query.offset }));result.rows=data.items.slice(0,50) as unknown as ConsoleRow[];result.hasMore=data.items.length>50; break; }
    case 'plans': result.rows=await rows(api.listPlatformPlans());break;
    case 'addons': result.rows=await rows(api.listPlatformAddonsCatalog());try{result.related=await rows(api.listPlatformTenantAddons());}catch(error){result.warnings.push(`Zuweisungen: ${error instanceof Error?error.message:String(error)}`);}break;
    case 'modules': result.rows=(await rows(api.listPlatformModules())).filter(row => !String(row.module_key).toLowerCase().includes('bodymap'));break;
    case 'discounts': result.rows=await rows(api.listPlatformDiscountCatalog());try{result.related=await rows(api.listPlatformTenantDiscounts());}catch(error){result.warnings.push(`Zuweisungen: ${error instanceof Error ? error.message : String(error)}`);}break;
    case 'billing': result.rows=await rows(api.listPlatformInvoices());if(can('payments.read')){try{result.related=await rows(api.listPlatformPayments());}catch(error){result.warnings.push(`Zahlungen: ${error instanceof Error ? error.message : String(error)}`);}}break;
    case 'payments': result.rows=await rows(api.listPlatformPayments());if(can('billing.read')){try{result.related=await rows(api.listPlatformInvoices());}catch(error){result.warnings.push(`Rechnungen: ${error instanceof Error ? error.message : String(error)}`);}}break;
    case 'feature-flags':result.rows=await rows(api.listPlatformFeatureFlags());break;
    case 'users': result.rows=await rows(api.listPlatformOperatorUsers());break;
    case 'audit': {const response=await platformRpc<{items:ConsoleRow[]}>('platform_list_console_audit',{p_tenant_id:query.tenantId||null,p_search:query.search||null,p_from:query.start||null,p_until:query.end||null,p_offset:query.offset});if(response.error)throw new Error(response.error.message);const items=response.data?.items??[];result.rows=items.slice(0,50);result.hasMore=items.length>50;break;}
    case 'system':result.rows=await rows(api.listPlatformSystemSettings());break;
    case 'releases':{const response=await platformRpc<{items:ConsoleRow[]}>('platform_list_console_releases',{p_search:query.search||null,p_status:query.status||null,p_from:query.start||null,p_until:query.end||null,p_offset:query.offset});if(response.error)throw new Error(response.error.message);const items=response.data?.items??[];result.rows=items.slice(0,50);result.hasMore=items.length>50;break;}
    case 'dashboard': {
      result.summary=await unwrap(api.fetchPlatformDashboardSummary());
      if(can('audit.read')){try{const response=await platformRpc<{items:ConsoleRow[]}>('platform_list_console_audit',{});if(response.error)throw new Error(response.error.message);result.related=(response.data?.items??[]).slice(0,8);}catch(error){result.warnings.push(`Aktivitätsverlauf: ${error instanceof Error?error.message:String(error)}`);}}
      break;
    }
  }
  await directory;
  const names=new Map(result.tenants.map(row=>[String(row.tenantId),String(row.tenantName)]));
  const invoices=new Map((section==='payments'?result.related:result.rows).map(row=>[row.id,row.invoice_number]));
  result.rows=result.rows.map(row=>({...row,
    tenant_label:row.tenant_id ? names.get(String(row.tenant_id)) ?? `Mandant ${String(row.tenant_id).slice(0,8)}` : 'Plattformweit',
    invoice_label:row.invoice_id ? invoices.get(row.invoice_id) ?? String(row.invoice_id) : 'Ohne Rechnungszuordnung',
    ...(section==='discounts'?{display_value: row.discount_type==='free_months'?`${row.value} Monate`:['fixed_amount','manual_credit','goodwill_credit'].includes(String(row.discount_type))?consoleMoney(row.value):`${row.value ?? '—'} %`}:{}),
    ...(section==='feature-flags'?{rollout_label:row.rollout_percentage==null?'Nicht festgelegt':`${row.rollout_percentage} %`}:{}),
    ...(section==='system'?{display_name:SETTING_NAMES[String(row.setting_key)]??String(row.setting_key).replace(/_/g,' '),display_value:isSensitiveSetting(row)?'Geschützt':consoleText(row.value)}:{}),
  }));
  result.related=result.related.map(row=>({...row,tenant_label:row.tenant_id?names.get(String(row.tenant_id))??`Mandant ${String(row.tenant_id).slice(0,8)}`:'Plattformweit'}));
  return result;
}

export type ConsoleField = { key: string; label: string; type?: 'text'|'textarea'|'select'|'date'|'email'|'number'|'url'; required?: boolean; value?: string; options?: {value:string;label:string}[]; hint?: string; min?: number; max?:number; };
export type ConsoleAction = { key:string; title:string; description:string; capability:PlatformCapability; fields:ConsoleField[]; danger?:boolean; run:(values:Record<string,string>,reason:string)=>Promise<unknown>; };
const field=(key:string,label:string,value:unknown='',type:ConsoleField['type']='text',required=true):ConsoleField=>({key,label,value:value==null?'':String(value),type,required});
const choices=(key:string,label:string,options:string[],value?:unknown):ConsoleField=>({...field(key,label,value??options[0],'select'),options:options.map(value=>({value,label:consoleLabel(value)}))});
const resultOf=async(promise:Promise<ServiceResult<unknown>>)=>unwrap(promise);
const euroValue=(value:unknown)=> (Number(value??0)/100).toFixed(2).replace('.',',');
const integer=(value:string,min=0,max=2147483647)=>{const n=Number(value);if(!value.trim()||!Number.isInteger(n)||n<min||n>max)throw new Error(`Bitte eine ganze Zahl zwischen ${min} und ${max} eingeben.`);return n;};

export function consoleActions(section:ConsoleSection,row:ConsoleRow|null,data:ConsoleData):ConsoleAction[]{
  const actions:ConsoleAction[]=[];
  const requestId = typeof globalThis.crypto?.randomUUID === 'function' ? globalThis.crypto.randomUUID() : '';
  const finance = async (operation:string,payload:ConsoleRow,reason:string) => {
    if(!requestId) throw new Error('Die sichere Vorgangskennung konnte nicht erstellt werden. Bitte die Seite über HTTPS öffnen.');
    const result=await platformRpc('platform_record_console_finance',{p_request_id:requestId,p_operation:operation,p_payload:payload,p_reason:reason});
    if(result.error) throw new Error(result.error.message);
    return result.data;
  };

  const tenant:ConsoleField={key:'tenant',label:'Unternehmen',type:'select',required:true,options:data.tenants.map(t=>({value:String(t.tenantId),label:String(t.tenantName)}))};
  const amount=field('amount','Betrag in Euro','0,00');
  const status=(values:string[],current?:unknown)=>choices('status','Status',values,current);
  const add=(action:ConsoleAction)=>actions.push({...action,run:async(values,reason)=>action.run(values,reason)});
  if(section==='modules')add({key:'module',title:row?'Funktion bearbeiten':'Funktion erfassen',description:'Beschreibung und Katalogstatus einer vorhandenen Funktion ändern. Grundfunktionen können hier nicht deaktiviert werden.',capability:'modules.write',fields:[...(!row?[field('key','Technischer Schlüssel')]:[]),field('name','Bezeichnung',row?.module_name),field('category','Kategorie',row?.category,'text',false),field('description','Beschreibung',row?.description,'textarea',false),status(row?.is_core?['available','beta']:['available','beta','internal','deprecated','disabled'],row?.status??'available')],run:async(v,reason)=>{if(getServiceMode()==='demo')throw new Error('Katalogänderungen benötigen eine echte Datenbankverbindung.');const res=await platformRpc('platform_save_module_catalog',{p_key:row?.module_key??v.key,p_name:v.name,p_description:v.description,p_category:v.category,p_status:v.status,p_reason:reason});if(res.error)throw new Error(res.error.message);return res.data;}});
  if(section==='plans'||section==='addons'){
    const plan=section==='plans';const key=String(row?.[plan?'plan_key':'addon_key']??'');
    add({key:'catalog',title:row?'Stammdaten bearbeiten':plan?'Kostenlosen Vertrag anlegen':'Erweiterung anlegen',description:plan?'Neue Plattformverträge werden mit 0 € angelegt. Die Anlage verändert keine bestehenden Verträge.':'Bezeichnung und Zweck einer tatsächlich verfügbaren Erweiterung dokumentieren.',capability:'plans.write',fields:[...(!row?[field('key','Kennung',plan?'free_platform':'')]:[]),field('name','Bezeichnung',row?.[plan?'plan_name':'addon_name']??(plan?'CareSuite HealthOS · Kostenlos':'')),field('description','Beschreibung',row?.description,'textarea',false),...(row?[status(plan?['active','inactive','archived']:['active','beta','deprecated','disabled'],row.status)]:[])],run:(v,reason)=>resultOf(row?plan?api.updatePlatformPlan(key,reason,{planName:v.name,description:v.description,status:v.status}):api.updatePlatformAddon(key,reason,{addonName:v.name,description:v.description,status:v.status}):plan?api.createPlatformPlan(v.key,v.name,reason,{description:v.description,monthlyPriceCents:0,yearlyPriceCents:0,isPublic:true}):api.createPlatformAddon(v.key,v.name,reason,{description:v.description,monthlyPriceCents:0,yearlyPriceCents:0}))});
    if(row){
      add({key:'version',title:'Neue Version dokumentieren',description:plan?'Die kostenlose Plattformnutzung bleibt bei 0 €. Frühere Versionen bleiben im Verlauf erhalten.':'Neue Preisversion dokumentieren. Bestehende Zuweisungen bleiben gemäß ihrem Vertragsstand bestehen.',capability:'plans.write',fields:[...(!plan?[field('monthly','Monatspreis in Euro',euroValue(row.monthly_price_cents)),field('yearly','Jahrespreis in Euro',euroValue(row.yearly_price_cents))]:[]),field('date','Gültig ab',new Date().toISOString().slice(0,10),'date')],run:(v,reason)=>{if(!validConsoleDay(v.date))throw new Error('Bitte ein gültiges Datum wählen.');return resultOf(plan?api.createPlatformPlanVersion(key,reason,0,0,`${v.date}T00:00:00Z`):api.createPlatformAddonVersion(key,reason,consoleEuros(v.monthly),consoleEuros(v.yearly),`${v.date}T00:00:00Z`));}});
      add({key:'assign',title:'Unternehmen zuweisen',description:`„${row[plan?'plan_name':'addon_name']}“ einem Unternehmen zuweisen. Prüfen Sie vor dem Speichern die Vertragsgrundlage.`,capability:'plans.write',fields:[tenant,choices('interval','Intervall',['monthly','yearly'])],run:(v,reason)=>resultOf(plan?api.assignPlatformPlanToTenant(v.tenant,key,reason,{billingInterval:v.interval as 'monthly'|'yearly'}):api.assignPlatformAddonToTenant(v.tenant,key,reason,{billingInterval:v.interval as 'monthly'|'yearly'}))});
    }
  }
  if(section==='discounts'){
    if(!row)add({key:'discount',title:'Sonderkondition anlegen',description:'Prozentwert, Betrag oder Freimonate mit einem eindeutigen Code dokumentieren.',capability:'discounts.write',fields:[field('key','Code'),field('name','Bezeichnung'),choices('type','Rabattart',['percentage','fixed_amount','free_months','lifetime_discount','beta_discount','partner_discount']),field('value','Wert'),field('description','Beschreibung','','textarea',false)],run:(v,reason)=>{let value:number;if(v.type==='fixed_amount')value=consoleEuros(v.value);else if(v.type==='free_months')value=integer(v.value,1,120);else{value=Number(v.value.replace(',','.'));if(!v.value.trim()||!Number.isFinite(value)||value<=0||value>100)throw new Error('Der Prozentrabatt muss größer als 0 und höchstens 100 sein.');}return resultOf(api.createPlatformDiscount({key:v.key,name:v.name,type:v.type as Parameters<typeof api.createPlatformDiscount>[0]['type'],value,description:v.description},reason));}});
    else add({key:'assign',title:'Sonderkondition zuweisen',description:`„${row.discount_name}“ für einen bestimmten Zeitraum zuweisen.`,capability:'discounts.write',fields:[tenant,field('start','Beginn',new Date().toISOString().slice(0,10),'date'),field('end','Ende','','date',false)],run:(v,reason)=>{if(!validConsoleDay(v.start)||(v.end&&(!validConsoleDay(v.end)||v.end<v.start)))throw new Error('Bitte einen gültigen Zeitraum angeben.');return resultOf(api.assignPlatformDiscount(v.tenant,String(row.discount_key),reason,{startsAt:`${v.start}T00:00:00Z`,endsAt:v.end?`${v.end}T23:59:59Z`:undefined}));}});
  }
  if(section==='billing'){
    if(!row)add({key:'invoice',title:'Manuelle Rechnung erfassen',description:'Nur tatsächlich vereinbarte zusätzliche Leistungen erfassen. Der Grund dokumentiert die Leistungsgrundlage. Die kostenlose Plattformnutzung wird nicht in Rechnung gestellt.',capability:'billing.write',fields:[tenant,field('amount','Bruttobetrag in Euro'),field('tax','Enthaltene Steuer in Euro','0,00'),field('due','Fällig am',new Date(Date.now()+14*86400000).toISOString().slice(0,10),'date')],run:(v,reason)=>{const total=consoleEuros(v.amount),tax=consoleEuros(v.tax);if(total<=0||tax>total||!validConsoleDay(v.due))throw new Error('Bitte Bruttobetrag, Steueranteil und Fälligkeitsdatum prüfen.');return finance('invoice',{tenant_id:v.tenant,amount_cents:total,tax_cents:tax,due_date:v.due},reason);}});
    else if((row.provider===null||row.provider==='manual')&&!['paid','partially_paid','refunded'].includes(String(row.status)))add({key:'status',title:'Rechnungsstatus berichtigen',description:`Status für Rechnung ${row.invoice_number} ändern. Zahlungseingänge erfassen Sie unter Zahlungen.`,capability:'billing.write',fields:[status(['draft','open','past_due','cancelled','failed'],row.status)],danger:true,run:(v,reason)=>resultOf(api.updatePlatformInvoiceStatus(String(row.id),v.status,reason))});
  }
  if(section==='payments'){
    if(!row)add({key:'payment',title:'Zahlungseingang erfassen',description:'Eine tatsächlich eingegangene Zahlung dokumentieren und optional einer Rechnung zuordnen. Das Unternehmen muss mit der Rechnung übereinstimmen.',capability:'payments.write',fields:[tenant,{...field('invoice','Rechnung','','select',false),options:[{value:'',label:'Ohne Rechnungszuordnung'},...data.related.filter(i=>!['cancelled','refunded','paid'].includes(String(i.status))).map(i=>({value:String(i.id),label:`${i.invoice_number} · ${consoleMoney(i.amount_cents)} · ${i.tenant_label??i.tenant_id}`}))]},amount,choices('method','Zahlungsweg',['bank_transfer','manual'])],run:(v,reason)=>{const amount=consoleEuros(v.amount);if(amount<=0)throw new Error('Der Zahlungseingang muss größer als 0 sein.');const invoice=data.related.find(i=>i.id===v.invoice);if(v.invoice&&(!invoice||invoice.tenant_id!==v.tenant))throw new Error('Die ausgewählte Rechnung gehört nicht zum ausgewählten Unternehmen.');return finance('payment',{tenant_id:v.tenant,invoice_id:v.invoice||null,amount_cents:amount,payment_method:v.method},reason);}});
    else if(row.provider==='manual')add({key:'status',title:'Zahlung berichtigen',description:'Den dokumentierten Status einer manuellen Zahlung korrigieren. Eine Erstattung wird hier nur dokumentiert; die Auszahlung erfolgt über den tatsächlichen Zahlungsweg.',capability:'payments.write',fields:[status(['pending','succeeded','failed','cancelled','refunded','chargeback'],row.status)],danger:true,run:(v,reason)=>resultOf(api.updatePlatformPaymentStatus(String(row.id),v.status,reason))});
  }
  if(section==='feature-flags'&&(!row||['global','tenant'].includes(String(row.scope))))add({key:'flag',title:row?'Freigabe bearbeiten':'Technische Freigabe anlegen',description:'Geltungsbereich und Rollout prüfen. Ein globaler Schalter betrifft alle Mandanten, für die keine abweichende Freigabe gilt.',capability:'flags.write',fields:[...(!row?[field('key','Technischer Schlüssel'),choices('scope','Geltungsbereich',['tenant','global']),{...tenant,required:false}]:[]),choices('enabled','Freigabe',['false','true'],String(row?.enabled??false)),{...field('rollout','Rollout in Prozent',row?.rollout_percentage??100,'number'),min:0,max:100}],danger:row?.scope==='global',run:(v,reason)=>{const scope=String(row?.scope??v.scope);const tenantId=String(row?.tenant_id??v.tenant??'');if(scope==='tenant'&&!tenantId)throw new Error('Für eine mandantenbezogene Freigabe ist ein Unternehmen erforderlich.');const key=String(row?.flag_key??v.key);if(!/^[a-z0-9_.-]{3,100}$/.test(key))throw new Error('Der technische Schlüssel muss 3–100 Kleinbuchstaben, Zahlen, Punkte, Unterstriche oder Bindestriche enthalten.');return resultOf(api.setPlatformFeatureFlag(key,v.enabled==='true',reason,{scope,tenantId:scope==='tenant'?tenantId:undefined,rolloutPercentage:integer(v.rollout,0,100)}));}});
  if(section==='users'&&!row)add({key:'add-user',title:'Plattformzugriff hinzufügen',description:'Einem bereits registrierten Benutzer Zugriff auf die Plattformverwaltung geben. Es wird keine Einladung versandt. Die E-Mail-Adresse muss exakt zum bestehenden Konto passen.',capability:'users.write',fields:[field('email','E-Mail des vorhandenen Kontos','','email'),choices('role','Rolle',Object.keys(api.PLATFORM_ROLE_LABELS),'platform_readonly')],danger:true,run:async(v,reason)=>{const result=await platformRpc('platform_add_operator_user',{p_email:v.email,p_role:v.role,p_reason:reason});if(result.error)throw new Error(result.error.message);return result.data;}});
  if(section==='users'&&row)add({key:'user',title:'Plattformzugriff bearbeiten',description:`Rolle und Zugriff für ${row.email} ändern. Der letzte aktive Inhaber bleibt geschützt.`,capability:'users.write',fields:[choices('role','Rolle',Object.keys(api.PLATFORM_ROLE_LABELS),row.role),status(['active','disabled','revoked'],row.status)],danger:true,run:(v,reason)=>resultOf(api.updatePlatformOperatorUser(String(row.id),v.role as PlatformRoleKey,v.status as PlatformUserStatus,reason))});
  if(section==='system'&&row&&!isSensitiveSetting(row))add({key:'setting',title:'Einstellung bearbeiten',description:String(row.description??'Diese Einstellung wirkt plattformweit.'),capability:'system.write',fields:[typeof row.value==='boolean'?choices('value','Wert',['false','true'],String(row.value)):field('value','Wert',typeof row.value==='object'?JSON.stringify(row.value,null,2):row.value,typeof row.value==='number'?'number':typeof row.value==='object'?'textarea':'text',false)],danger:row.setting_key==='maintenance_mode',run:(v,reason)=>resultOf(api.updatePlatformSystemSetting(String(row.setting_key),consoleSettingValue(row.value,v.value),reason))});
  if(section==='releases'&&!row)add({key:'release',title:'Release registrieren',description:'Tatsächlichen Stand dokumentieren. Prüfergebnisse werden ausdrücklich angegeben und nicht aus dem Release-Status abgeleitet.',capability:'system.write',fields:[field('version','Versionsbezeichnung'),choices('environment','Umgebung',['preview','staging','production']),status(['planned','building','ready','failed','rolled_back'],'planned'),field('commit','Git-Commit','','text',false),field('url','Deployment-URL','','url',false),field('migration','Datenbankstand','','text',false),choices('build','Build-Prüfung',['not_checked','passed','failed'],'not_checked'),choices('smoke','Funktionsprüfung',['not_checked','passed','failed'],'not_checked'),choices('visual','Darstellungsprüfung',['not_checked','passed','failed'],'not_checked'),field('notes','Prüfnotiz','','textarea',false)],run:(v,reason)=>{if(v.commit&&!/^[a-f0-9]{7,40}$/i.test(v.commit))throw new Error('Der Git-Commit muss 7–40 hexadezimale Zeichen enthalten.');if(v.url){const url=new URL(v.url);if(url.protocol!=='https:')throw new Error('Bitte eine HTTPS-Adresse angeben.');}return resultOf(api.registerPlatformRelease({environment:v.environment as 'preview'|'staging'|'production',version_label:v.version,commit_sha:v.commit||null,status:v.status as 'planned'|'building'|'ready'|'failed'|'rolled_back',deployment_url:v.url||null,migration_version:v.migration||null,notes:v.notes||null,checks:{build:v.build,smoke:v.smoke,visual:v.visual,recorded_in_console:true}},reason));}});
  return actions;
}

export function formatConsoleCell(row:ConsoleRow,column:ConsoleColumn):string {
  const value=row[column.key];
  if(column.format==='money')return consoleMoney(value,row.currency);
  if(column.format==='date')return consoleDate(value);
  if(column.format==='boolean')return value==null?'—':value?'Ja':'Nein';
  return consoleText(value);
}
export async function loadConsoleVersions(section:ConsoleSection,row:ConsoleRow):Promise<ConsoleRow[]> {
  return rows(section==='plans'?api.listPlatformPlanVersions(String(row.plan_key)):api.listPlatformAddonVersions(String(row.addon_key)));
}
