import { DEMO_TENANT_ID } from '@/data/constants/testTenant';
import type {
  DeviceManagementProfile,
  InventoryAssignment,
  InventoryCategory,
  InventoryDamageReport,
  InventoryItem,
  InventoryLocation,
  InventoryReturnProtocol,
  InventoryReturnRecord,
} from '@/types/inventory';

const now = '2026-06-01T10:00:00.000Z';

export const demoInventoryLocations: InventoryLocation[] = [
  {
    id: 'inv-loc-001',
    tenantId: DEMO_TENANT_ID,
    label: 'Büro Hauptlager',
    building: 'Verwaltung',
    room: 'Lager 1',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-loc-002',
    tenantId: DEMO_TENANT_ID,
    label: 'Dienstkleidung Schrank',
    building: 'Verwaltung',
    room: 'Umkleide',
    createdAt: now,
    updatedAt: now,
  },
];

export const demoInventoryCategories: InventoryCategory[] = [
  {
    id: 'inv-cat-devices',
    tenantId: DEMO_TENANT_ID,
    group: 'devices',
    label: 'Tablets & Laptops',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    barcodeEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-mobile',
    tenantId: DEMO_TENANT_ID,
    group: 'mobile_sim',
    label: 'Diensthandys & SIM',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    barcodeEnabled: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-uniform',
    tenantId: DEMO_TENANT_ID,
    group: 'uniform',
    label: 'Dienstkleidung',
    requiresReturnOnExit: false,
    portalVisibleToEmployee: true,
    barcodeEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-keys',
    tenantId: DEMO_TENANT_ID,
    group: 'keys_access',
    label: 'Schlüssel & Transponder',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: false,
    barcodeEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-docs',
    tenantId: DEMO_TENANT_ID,
    group: 'documents',
    label: 'Ausweise & Dokumente',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: false,
    barcodeEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-vehicles',
    tenantId: DEMO_TENANT_ID,
    group: 'vehicles',
    label: 'Firmenfahrzeuge',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: false,
    barcodeEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-cat-software',
    tenantId: DEMO_TENANT_ID,
    group: 'software_access',
    label: 'Software & Systemzugänge',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    barcodeEnabled: false,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoInventoryItems: InventoryItem[] = [
  {
    id: 'inv-item-001',
    tenantId: DEMO_TENANT_ID,
    categoryId: 'inv-cat-devices',
    categoryGroup: 'devices',
    name: 'Samsung Galaxy Tab A8',
    sku: 'TAB-A8-001',
    serialNumber: 'SN-TAB-88421',
    manufacturer: 'Samsung',
    model: 'Galaxy Tab A8',
    locationId: 'inv-loc-001',
    status: 'assigned',
    condition: 'very_good',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    purchaseDate: '2024-03-01',
    warrantyUntil: '2027-03-01',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-item-002',
    tenantId: DEMO_TENANT_ID,
    categoryId: 'inv-cat-mobile',
    categoryGroup: 'mobile_sim',
    name: 'iPhone 13 Dienst',
    serialNumber: 'SN-IPH-33201',
    manufacturer: 'Apple',
    model: 'iPhone 13',
    locationId: 'inv-loc-001',
    status: 'assigned',
    condition: 'good',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-item-003',
    tenantId: DEMO_TENANT_ID,
    categoryId: 'inv-cat-uniform',
    categoryGroup: 'uniform',
    name: 'Poloshirt Gr. L',
    sku: 'UNI-POLO-L',
    locationId: 'inv-loc-002',
    status: 'available',
    condition: 'new',
    requiresReturnOnExit: false,
    portalVisibleToEmployee: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-item-004',
    tenantId: DEMO_TENANT_ID,
    categoryId: 'inv-cat-keys',
    categoryGroup: 'keys_access',
    name: 'Büroschlüssel Satz A',
    locationId: 'inv-loc-001',
    status: 'assigned',
    condition: 'used',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: false,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-item-005',
    tenantId: DEMO_TENANT_ID,
    categoryId: 'inv-cat-devices',
    categoryGroup: 'devices',
    name: 'Lenovo ThinkPad L14',
    serialNumber: 'SN-LNV-99102',
    manufacturer: 'Lenovo',
    model: 'ThinkPad L14',
    locationId: 'inv-loc-001',
    status: 'available',
    condition: 'good',
    requiresReturnOnExit: true,
    portalVisibleToEmployee: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoInventoryAssignments: InventoryAssignment[] = [
  {
    id: 'inv-asg-001',
    tenantId: DEMO_TENANT_ID,
    itemId: 'inv-item-001',
    recipientEmployeeId: 'employee-001',
    responsibleEmployeeId: 'employee-001',
    issuedByProfileId: null,
    issuedAt: '2025-01-15T09:00:00.000Z',
    expectedReturnAt: null,
    acknowledgedAt: '2025-01-16T08:00:00.000Z',
    status: 'acknowledged',
    issueCondition: 'very_good',
    returnRequired: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-asg-002',
    tenantId: DEMO_TENANT_ID,
    itemId: 'inv-item-002',
    recipientEmployeeId: 'employee-002',
    responsibleEmployeeId: 'employee-002',
    issuedAt: '2024-08-01T09:00:00.000Z',
    expectedReturnAt: '2026-05-01T00:00:00.000Z',
    acknowledgedAt: '2024-08-02T10:00:00.000Z',
    status: 'overdue',
    issueCondition: 'good',
    returnRequired: true,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'inv-asg-003',
    tenantId: DEMO_TENANT_ID,
    itemId: 'inv-item-004',
    recipientEmployeeId: 'employee-003',
    responsibleEmployeeId: 'employee-003',
    issuedAt: '2025-11-01T09:00:00.000Z',
    status: 'return_requested',
    issueCondition: 'used',
    returnRequired: true,
    createdAt: now,
    updatedAt: now,
  },
];

export const demoInventoryReturnRecords: InventoryReturnRecord[] = [];

export const demoInventoryDamageReports: InventoryDamageReport[] = [];

export const demoInventoryReturnProtocols: InventoryReturnProtocol[] = [];

export const demoDeviceManagementProfiles: DeviceManagementProfile[] = [
  {
    id: 'inv-mdm-001',
    tenantId: DEMO_TENANT_ID,
    itemId: 'inv-item-001',
    deviceId: 'mdm-device-tab-001',
    osName: 'Android',
    osVersion: '13',
    appVersion: '1.4.2',
    lastLoginAt: '2026-06-10T07:30:00.000Z',
    lastSyncAt: '2026-06-10T07:35:00.000Z',
    mdmStatus: 'not_configured',
    remoteLockPrepared: true,
    remoteWipePrepared: true,
    mdmProviderKey: null,
    updatedAt: now,
  },
];
