import { beforeEach, describe, expect, it, vi } from 'vitest';
const mock=vi.hoisted(()=>({rpc:vi.fn(),createPlan:vi.fn(),createVersion:vi.fn(),setFlag:vi.fn(),release:vi.fn()}));
vi.mock('@/lib/platformConsole/index',()=>({PLATFORM_ROLE_LABELS:{platform_owner:'Owner',platform_readonly:'Lesen'},createPlatformPlan:mock.createPlan,createPlatformPlanVersion:mock.createVersion,setPlatformFeatureFlag:mock.setFlag,registerPlatformRelease:mock.release}));
vi.mock('@/lib/platformConsole/platformSupabaseClient',()=>({platformRpc:mock.rpc}));
vi.mock('@/lib/platformConsole/platformCompanyDirectoryService',()=>({listPlatformCompanies:vi.fn()}));
vi.mock('@/lib/services/mode',()=>({getServiceMode:()=> 'supabase'}));
import { consoleActions, type ConsoleData } from '@/lib/platformConsole/consoleWorkspaceService';
const data:ConsoleData={rows:[],tenants:[{tenantId:'tenant-a',tenantName:'Beispiel A'},{tenantId:'tenant-b',tenantName:'Beispiel B'}],related:[{id:'invoice-a',tenant_id:'tenant-a',invoice_number:'TEST-1',amount_cents:10000,status:'open'}],warnings:[],hasMore:false};
beforeEach(()=>{vi.clearAllMocks();mock.rpc.mockResolvedValue({data:{id:'saved'},error:null});mock.createPlan.mockResolvedValue({ok:true,data:{}});mock.createVersion.mockResolvedValue({ok:true,data:{}});mock.setFlag.mockResolvedValue({ok:true,data:{}});mock.release.mockResolvedValue({ok:true,data:{}});});
describe('Platform Console actions',()=>{
  it('creates a free contract without introducing a paid registration',async()=>{await consoleActions('plans',null,data)[0].run({key:'free_platform',name:'HealthOS',description:'Kostenlos'},'Vertragsbasis festgelegt');expect(mock.createPlan).toHaveBeenCalledWith('free_platform','HealthOS','Vertragsbasis festgelegt',expect.objectContaining({monthlyPriceCents:0,yearlyPriceCents:0,isPublic:true}));});
  it('refuses cross-tenant invoice assignment before contacting the server',async()=>{const action=consoleActions('payments',null,data)[0];await expect(action.run({tenant:'tenant-b',invoice:'invoice-a',amount:'100,00',method:'bank_transfer'},'Zahlung geprüft')).rejects.toThrow('gehört nicht');expect(mock.rpc).not.toHaveBeenCalled();});
  it('reuses an idempotency key when a financial request is retried',async()=>{const action=consoleActions('payments',null,data)[0];const values={tenant:'tenant-a',invoice:'invoice-a',amount:'100,00',method:'bank_transfer'};await action.run(values,'Zahlung geprüft');await action.run(values,'Zahlung geprüft');const a=mock.rpc.mock.calls[0][1],b=mock.rpc.mock.calls[1][1];expect(a.p_request_id).toBeTruthy();expect(a.p_request_id).toBe(b.p_request_id);expect(a.p_payload.amount_cents).toBe(10000);});
  it('rejects impossible invoice dates and tax exceeding the total',async()=>{const action=consoleActions('billing',null,data)[0];await expect(action.run({tenant:'tenant-a',amount:'10,00',tax:'11,00',due:'2026-09-20'},'Leistung vereinbart')).rejects.toThrow();await expect(action.run({tenant:'tenant-a',amount:'10,00',tax:'0,00',due:'2026-02-31'},'Leistung vereinbart')).rejects.toThrow();expect(mock.rpc).not.toHaveBeenCalled();});
  it('requires a tenant for scoped flags and bounds rollout',async()=>{const action=consoleActions('feature-flags',null,data)[0];await expect(action.run({key:'feature_v2',scope:'tenant',tenant:'',enabled:'true',rollout:'100'},'Freigabe geprüft')).rejects.toThrow();await expect(action.run({key:'feature_v2',scope:'global',enabled:'true',rollout:'101'},'Freigabe geprüft')).rejects.toThrow();expect(mock.setFlag).not.toHaveBeenCalled();});
  it('does not infer successful checks from a ready release',async()=>{await consoleActions('releases',null,data)[0].run({version:'Test-1',environment:'preview',status:'ready',commit:'abcdef0',url:'',migration:'',build:'not_checked',smoke:'failed',visual:'not_checked',notes:''},'Prüfstand dokumentiert');expect(mock.release.mock.calls[0][0].checks).toEqual({build:'not_checked',smoke:'failed',visual:'not_checked',recorded_in_console:true});});
  it('never offers editing for protected settings or provider-owned payments',()=>{expect(consoleActions('system',{setting_key:'smtp_config',value:'secret',is_sensitive:true},data)).toEqual([]);expect(consoleActions('payments',{provider:'stripe'},data)).toEqual([]);});
});
