export {
  hasPermission,
  hasPermissionInList,
  hasAnyPermission,
  hasAnyPermissionInList,
  hasAllPermissions,
  hasAllPermissionsInList,
  checkPermission,
  checkPermissionWithList,
  permissionError,
} from './check';
export { enforcePermission } from './enforce';
export { runPermissionMatrix, type PermissionMatrixCase } from './testMatrix';
export {
  WORKSPACE_ROLE_DEFINITIONS,
  resolveWorkspaceArea,
  resolveWorkspaceCategory,
  isPortalOnlyRole,
  isEmployeePortalRole,
  isClientPortalRole,
  isAdministrationRole,
  hasFullTenantDataAccess,
  mapCanonicalRoleToRoleKey,
  getWorkspaceRoleDefinition,
} from './workspaceRoles';
export {
  buildWorkspaceAccessContext,
  canAccessAdminArea,
  canAccessEmployeePortal,
  canAccessClientPortal,
  canViewAssignment,
  canEditAssignment,
  canStartAssignment,
  canCompleteAssignment,
  canViewClientRecord,
  canViewDocument,
  canRequestReschedule,
  canCancelVisitRequest,
  canViewAuditLog,
  canDirectEmployeeClientChat,
  assertWorkspaceAccess,
  filterAssignmentsForActor,
  resolveWorkspaceAreaForPath,
  checkWorkspaceAreaAccess,
  logWorkspaceAccessEvent,
  getWorkspaceAuditTrail,
  resetWorkspaceAuditStore,
  PORTAL_ONLY_ROLES,
  EMPLOYEE_PORTAL_ROLES,
  CLIENT_PORTAL_ROLES,
} from './workspaceAccess';
export type {
  WorkspaceArea,
  WorkspaceRoleCategory,
  CanonicalWorkspaceRoleKey,
  WorkspaceRoleDefinition,
  WorkspaceAccessContext,
  WorkspaceAccessCode,
  WorkspaceAccessDecision,
  WorkspaceAuditEvent,
} from '@/types/permissions/workspace';
export {
  fetchRoleMatrixOverview,
  fetchRoleMatrixForRole,
  saveRoleMatrix,
  restoreRoleDefaults,
  copyRolePermissions,
  fetchPermissionAuditHistory,
  previewRoleMatrixChange,
  createCustomRoleWithPermissions,
  getPermissionAreaLabel,
  listSystemRoles,
  getEffectivePermissionsForRole,
  buildDefaultRoleMatrix,
  PERMISSION_AREAS,
  PERMISSION_ACTIONS,
} from './roleMatrixService';
export type {
  PermissionAction,
  PermissionAreaKey,
  AreaPermissionSet,
  RoleAreaMatrix,
  TenantRoleMatrixEntry,
  PermissionMatrixPreview,
  PermissionAuditEvent,
  SaveRoleMatrixInput,
  RoleMatrixValidationResult,
} from '@/types/permissions/roleMatrix';
