import type { KpiDefinition } from '@/types/reporting/metrics';

/** Prompt 70 — KPI registry with defined data sources and drilldowns */
export const KPI_DEFINITIONS: KpiDefinition[] = [
  // Assignments
  {
    id: 'assignments_total',
    category: 'assignments',
    label: 'Einsätze',
    description: 'Einsätze im gewählten Zeitraum',
    dataSource: 'assignments',
    dashboards: ['ceo', 'admin', 'employee'],
    drilldownRoute: '/assist/assignments',
  },
  {
    id: 'assignments_planned',
    category: 'assignments',
    label: 'Geplant',
    description: 'Geplante Einsätze',
    dataSource: 'assignments',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/assist/assignments',
  },
  {
    id: 'assignments_completed',
    category: 'assignments',
    label: 'Abgeschlossen',
    description: 'Abgeschlossene Einsätze',
    dataSource: 'assignments',
    dashboards: ['ceo', 'admin', 'employee'],
    drilldownRoute: '/assist/assignments',
  },
  {
    id: 'assignments_open_no_employee',
    category: 'assignments',
    label: 'Ohne Mitarbeitende',
    description: 'Offene Einsätze ohne Zuweisung',
    dataSource: 'assignments',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/assist/assignments',
  },
  {
    id: 'assignments_on_time_start',
    category: 'assignments',
    label: 'Pünktlicher Start',
    description: 'Einsätze mit pünktlichem Start',
    dataSource: 'assignment_status_events',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/assist/live-monitor',
  },
  // Documentation
  {
    id: 'documentation_complete',
    category: 'documentation',
    label: 'Doku vollständig',
    description: 'Vollständige Einsatzdokumentation',
    dataSource: 'assignment_documentation',
    dashboards: ['ceo', 'admin', 'qm', 'employee'],
    drilldownRoute: '/assist/assignments',
    dataQualityArea: 'documents',
  },
  {
    id: 'documentation_missing',
    category: 'documentation',
    label: 'Doku fehlt',
    description: 'Fehlende Dokumentation',
    dataSource: 'assignment_documentation',
    dashboards: ['ceo', 'admin', 'qm', 'employee'],
    drilldownRoute: '/assist/assignments',
    dataQualityArea: 'documents',
  },
  {
    id: 'documentation_corrections',
    category: 'documentation',
    label: 'Korrekturen',
    description: 'Offene Dokumentationskorrekturen',
    dataSource: 'assignment_documentation',
    dashboards: ['ceo', 'qm', 'employee'],
    drilldownRoute: '/assist/live-monitor',
  },
  // Signatures
  {
    id: 'signatures_complete',
    category: 'signatures',
    label: 'Signaturen vollständig',
    description: 'Vollständige Signaturen',
    dataSource: 'assignment_signatures',
    dashboards: ['ceo', 'admin', 'qm'],
    drilldownRoute: '/assist/assignments',
    dataQualityArea: 'documents',
  },
  {
    id: 'signatures_missing',
    category: 'signatures',
    label: 'Signaturen fehlen',
    description: 'Fehlende Signaturen',
    dataSource: 'assignment_signatures',
    dashboards: ['ceo', 'admin', 'qm'],
    drilldownRoute: '/assist/assignments',
    dataQualityArea: 'documents',
  },
  // Service records
  {
    id: 'service_records_billing_ready',
    category: 'service_records',
    label: 'Abrechnungsbereit',
    description: 'Freigegebene Leistungsnachweise bereit zur Abrechnung',
    dataSource: 'service_records',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/billing',
    dataQualityArea: 'service_records',
  },
  {
    id: 'service_records_review_pending',
    category: 'service_records',
    label: 'Prüfung ausstehend',
    description: 'Leistungsnachweise in Prüfung',
    dataSource: 'service_records',
    dashboards: ['ceo', 'billing', 'admin'],
    drilldownRoute: '/business/office/billing',
    dataQualityArea: 'service_records',
  },
  // Billing
  {
    id: 'billing_revenue_prepared',
    category: 'billing',
    label: 'Umsatz vorbereitet',
    description: 'Vorbereiteter Umsatz aus abrechnungsbereiten Positionen — nicht fakturiert',
    dataSource: 'billable_items',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/billing',
    dataQualityArea: 'invoices',
  },
  {
    id: 'billing_revenue_invoiced',
    category: 'billing',
    label: 'Umsatz fakturiert',
    description: 'Tatsächlich fakturierter Umsatz aus Rechnungen',
    dataSource: 'invoices',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/invoices',
    dataQualityArea: 'invoices',
    valueFormat: 'currency',
  },
  {
    id: 'billing_open_amount',
    category: 'billing',
    label: 'Offene Beträge',
    description: 'Noch nicht bezahlte Rechnungsbeträge',
    dataSource: 'invoices',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/invoices',
    valueFormat: 'currency',
  },
  {
    id: 'billing_overdue',
    category: 'billing',
    label: 'Überfällig',
    description: 'Überfällige Rechnungen',
    dataSource: 'invoices',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/invoices',
  },
  {
    id: 'billing_drafts',
    category: 'billing',
    label: 'Rechnungsentwürfe',
    description: 'Offene Rechnungsentwürfe',
    dataSource: 'invoice_drafts',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/invoices',
  },
  {
    id: 'billing_blockers',
    category: 'billing',
    label: 'Abrechnungsblocker',
    description: 'Blockierte Abrechnungspositionen',
    dataSource: 'billable_items',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/admin/data-quality/invoices',
    dataQualityArea: 'invoices',
  },
  // Budget
  {
    id: 'budget_exceeded',
    category: 'budget',
    label: 'Budget überschritten',
    description: 'Klient:innen-Budgets über Limit',
    dataSource: 'client_budgets',
    dashboards: ['ceo', 'admin', 'billing'],
    drilldownRoute: '/business/office/budgets',
    dataQualityArea: 'clients',
  },
  {
    id: 'budget_warning',
    category: 'budget',
    label: 'Budget-Warnung',
    description: 'Budgets nahe Limit',
    dataSource: 'client_budgets',
    dashboards: ['ceo', 'admin', 'billing'],
    drilldownRoute: '/business/office/budgets',
  },
  {
    id: 'budget_available',
    category: 'budget',
    label: 'Verfügbar',
    description: 'Verfügbares Budgetvolumen',
    dataSource: 'client_budgets',
    dashboards: ['ceo', 'billing'],
    drilldownRoute: '/business/office/budgets',
    valueFormat: 'currency',
  },
  // Employees
  {
    id: 'employees_active',
    category: 'employees',
    label: 'Aktive Mitarbeitende',
    description: 'Aktive Mitarbeitende im Mandanten',
    dataSource: 'employees',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/business/office/employees',
  },
  {
    id: 'employees_utilization',
    category: 'employees',
    label: 'Auslastung',
    description: 'Durchschnittliche Einsatzauslastung',
    dataSource: 'assignments',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/assist/assignments',
    valueFormat: 'percent',
  },
  {
    id: 'employees_open_docs',
    category: 'employees',
    label: 'Offene Dokumentation',
    description: 'Mitarbeitende mit offener Dokumentation',
    dataSource: 'assignment_documentation',
    dashboards: ['ceo', 'admin', 'employee'],
    drilldownRoute: '/assist/assignments',
  },
  // Clients
  {
    id: 'clients_active',
    category: 'clients',
    label: 'Aktive Klient:innen',
    description: 'Aktive Klient:innen',
    dataSource: 'clients',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/business/office/clients',
  },
  {
    id: 'clients_new',
    category: 'clients',
    label: 'Neu im Zeitraum',
    description: 'Neu angelegte Klient:innen',
    dataSource: 'clients',
    dashboards: ['ceo', 'admin'],
    drilldownRoute: '/business/office/clients',
  },
  // Quality / Risk
  {
    id: 'quality_complaints',
    category: 'quality_risk',
    label: 'Beschwerden',
    description: 'Gemeldete Beschwerden',
    dataSource: 'problem_reports',
    dashboards: ['ceo', 'qm'],
    drilldownRoute: '/assist/live-monitor',
  },
  {
    id: 'quality_emergencies',
    category: 'quality_risk',
    label: 'Notfälle',
    description: 'Gemeldete Notfälle',
    dataSource: 'emergency_reports',
    dashboards: ['ceo', 'qm'],
    drilldownRoute: '/assist/live-monitor',
  },
  {
    id: 'quality_qm_tasks',
    category: 'quality_risk',
    label: 'QM-Aufgaben offen',
    description: 'Offene QM-Verwaltungsaufgaben',
    dataSource: 'management_tasks',
    dashboards: ['ceo', 'qm', 'admin'],
    drilldownRoute: '/assist/live-monitor',
  },
  {
    id: 'quality_critical_assignments',
    category: 'quality_risk',
    label: 'Kritische Einsätze',
    description: 'Kritische Einsätze im Live-Monitor',
    dataSource: 'assignments',
    dashboards: ['ceo', 'qm', 'admin'],
    drilldownRoute: '/assist/live-monitor',
  },
  // Growth / Management
  {
    id: 'growth_assignments_trend',
    category: 'growth_management',
    label: 'Einsatz-Trend',
    description: 'Monatlicher Einsatz-Trend',
    dataSource: 'assignments',
    dashboards: ['ceo'],
    drilldownRoute: '/business/reporting/dashboard',
  },
  {
    id: 'growth_clients_trend',
    category: 'growth_management',
    label: 'Klient:innen-Trend',
    description: 'Monatlicher Klient:innen-Trend',
    dataSource: 'clients',
    dashboards: ['ceo'],
    drilldownRoute: '/business/reporting/dashboard',
  },
  {
    id: 'growth_connect_prepared',
    category: 'growth_management',
    label: 'Connect vorbereitet',
    description: 'Connect-Integrationen in Vorbereitung',
    dataSource: 'connect_integrations',
    dashboards: ['ceo'],
    drilldownRoute: '/business/connect',
  },
  // Export center (prepared)
  {
    id: 'export_center_prepared',
    category: 'growth_management',
    label: 'Export-Center',
    description: 'Berichtsexport und Report-Center',
    dataSource: 'generated_documents',
    dashboards: ['export_center'],
    drilldownRoute: '/business/reporting/list',
  },
];

export function getKpiDefinition(kpiId: string): KpiDefinition | undefined {
  return KPI_DEFINITIONS.find((k) => k.id === kpiId);
}

export function getKpisForDashboard(kind: import('@/types/reporting/metrics').ReportingDashboardKind): KpiDefinition[] {
  return KPI_DEFINITIONS.filter((k) => k.dashboards.includes(kind));
}

export function getKpisForCategory(category: import('@/types/reporting/metrics').KpiCategory): KpiDefinition[] {
  return KPI_DEFINITIONS.filter((k) => k.category === category);
}
