import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';

export function SupportButton({ label, onPress, disabled, secondary = false }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{ disabled: !!disabled }} disabled={disabled} onPress={onPress} style={({ pressed }) => [supportStyles.button, secondary && supportStyles.buttonSecondary, disabled && { opacity: 0.5 }, pressed && { opacity: 0.8 }]}><Text style={[supportStyles.buttonText, secondary && supportStyles.buttonSecondaryText]}>{label}</Text></Pressable>;
}
export function SupportField({ label, value, onChangeText, multiline = false, maxLength = 10000, disabled = false }: { label: string; value: string; onChangeText: (value: string) => void; multiline?: boolean; maxLength?: number; disabled?: boolean }) {
  return <View style={supportStyles.field}><Text style={supportStyles.label}>{label}</Text><TextInput editable={!disabled} accessibilityState={{ disabled }} accessibilityLabel={label} value={value} onChangeText={onChangeText} multiline={multiline} maxLength={maxLength} placeholderTextColor="#60758E" style={[supportStyles.input, multiline && supportStyles.multiline]} /></View>;
}
export const supportDate = (value: string) => new Date(value).toLocaleString('de-DE', { dateStyle: 'short', timeStyle: 'short' });

export const supportStyles = StyleSheet.create({
  root:{flex:1,minHeight:0,minWidth:0,backgroundColor:'#F2F6FC',borderRadius:20,padding:20,gap:18},
  hero:{flexDirection:'row',flexWrap:'wrap',alignItems:'center',gap:18},heroCopy:{flex:1,minWidth:0,gap:8},title:{color:'#102B49',fontSize:28,lineHeight:36,fontWeight:'800'},copy:{color:'#38546F',fontSize:14,lineHeight:22},small:{color:'#526B82',fontSize:12,lineHeight:18},label:{color:'#203E5C',fontSize:14,lineHeight:21,fontWeight:'700'},eyebrow:{color:'#075EB8',fontSize:12,lineHeight:18,fontWeight:'800'},heading:{color:'#102B49',fontSize:21,lineHeight:28,fontWeight:'800'},
  workspace:{flex:1,minHeight:0,flexDirection:'row',gap:18},stacked:{flexDirection:'column'},queue:{width:320,flexShrink:0,gap:10,minHeight:0},queueCompact:{width:'100%',flex:1},queueScroll:{flex:1,minHeight:100},queueContent:{gap:9,paddingBottom:8},detailScroll:{flex:1,minWidth:0,minHeight:0},detailContent:{gap:16,paddingBottom:24},section:{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#CCDBEA',borderRadius:18,padding:20,gap:14,minWidth:0},row:{flexDirection:'row',flexWrap:'wrap',gap:10,alignItems:'center',justifyContent:'space-between'},chips:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{borderWidth:1,borderColor:'#C8D9EB',borderRadius:12,padding:10},chipActive:{backgroundColor:'#DFEEFF',borderColor:'#3989DD'},chipText:{fontSize:12,color:'#164B82',fontWeight:'700'},ticketCard:{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#CCDBEA',borderRadius:14,padding:14,gap:6},ticketSelected:{backgroundColor:'#EAF3FF',borderColor:'#1477D6'},ticketTitle:{color:'#163652',fontSize:15,lineHeight:22,fontWeight:'700'},field:{gap:6,minWidth:0},input:{backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#9EBBD7',borderRadius:11,paddingHorizontal:12,paddingVertical:11,color:'#102B49',fontSize:15,lineHeight:22,minHeight:46,minWidth:0},multiline:{minHeight:110,textAlignVertical:'top'},button:{backgroundColor:'#0762C6',borderColor:'#0762C6',borderWidth:1,borderRadius:11,paddingHorizontal:14,paddingVertical:11,minHeight:44,justifyContent:'center',alignItems:'center',maxWidth:'100%'},buttonSecondary:{backgroundColor:'#F0F6FE',borderColor:'#B8D1EA'},buttonText:{color:'#FFFFFF',fontSize:14,lineHeight:20,fontWeight:'700',textAlign:'center'},buttonSecondaryText:{color:'#075EB8'},message:{backgroundColor:'#F3F6FA',borderColor:'#DEE7F0',borderWidth:1,borderRadius:14,padding:14,gap:10},messageSupport:{backgroundColor:'#EAF3FF',borderColor:'#BED9F4'},messageBody:{color:'#183951',fontSize:15,lineHeight:24},composer:{borderTopWidth:1,borderTopColor:'#CCDBEA',paddingTop:16,gap:12},error:{backgroundColor:'#FFF1F0',borderColor:'#E9B7B2',borderWidth:1,borderRadius:12,padding:14,gap:10},errorText:{color:'#942A24',fontSize:14,lineHeight:21},notice:{backgroundColor:'#EAF4FF',borderWidth:1,borderColor:'#AECEE9',borderRadius:13,padding:14,gap:8},dangerText:{color:'#B02D35',fontSize:14,fontWeight:'700'},
});
