export {
  fetchCalendarEvents,
  fetchAssistCalendarEvents,
  filterEventsByVisibleTypes,
  filterEventsForAssistModule,
  getCalendarEvents,
  getOfficeCalendarEvents,
  getModuleCalendarEvents,
  getPortalCalendarEvents,
  buildOfficeCalendarConfig,
  buildModuleCalendarConfig,
  archiveCalendarEvent,
  updateCalendarEvent,
  detectCalendarConflicts,
  type FetchCalendarEventsOptions,
} from '@/lib/calendar/calendarEventService';
