import {describe,it,expect,vi} from 'vitest';
import {computeFreeRoute,geocodeFree} from '../../../supabase/functions/_shared/freeGeoEngine';
describe('free routing safety',()=>{
 it('never fabricates transit or makes commercial-forbidden calls',async()=>{const request=vi.fn();const result=await computeFreeRoute({origin:'A',destination:'B',transportMode:'transit'},request);expect(result.source).toBe('unavailable');expect(result.durationMinutes).toBeNull();expect(request).not.toHaveBeenCalled();});
 it.each([['car','car'],['bicycle','bike'],['walking','foot'],['escooter','bike']])('uses the correct %s profile',async(transportMode,profile)=>{const request=vi.fn().mockResolvedValue({code:'Ok',routes:[{duration:360,distance:1800,geometry:'abcd'}]});const result=await computeFreeRoute({origin:'52.5,13.4',destination:'52.51,13.42',transportMode,includeRouteGeometry:true},request);expect(request.mock.calls[0][0]).toContain(`/routed-${profile}/`);expect(request).toHaveBeenCalledTimes(1);expect(result).toMatchObject({source:'osm',durationMinutes:6,distanceMeters:1800,encodedPolyline:'abcd'});});
 it('rejects invalid WGS84 positions before provider calls',async()=>{const request=vi.fn();await expect(geocodeFree('100,13',request)).rejects.toThrow('Koordinaten');expect(request).not.toHaveBeenCalled();});
 it('does not replace a missing house number with a street center',async()=>{const request=vi.fn().mockResolvedValue({features:[{geometry:{coordinates:[13.4,52.5]},properties:{countrycode:'DE',postcode:'10115',street:'Invalidenstraße'}}]});expect(await geocodeFree('Invalidenstraße 44, 10115 Berlin',request)).toBeNull();});
 it('rejects different matching cities as ambiguous',async()=>{const request=vi.fn().mockResolvedValue({features:[{geometry:{coordinates:[13.4,52.5]},properties:{countrycode:'DE'}},{geometry:{coordinates:[13.5,52.6]},properties:{countrycode:'DE'}}]});await expect(geocodeFree('Kirchstraße',request)).rejects.toThrow('nicht eindeutig');});
 it('rejects provider errors instead of accepting their first geometry',async()=>{await expect(computeFreeRoute({origin:'52.5,13.4',destination:'52.51,13.42',transportMode:'car'},vi.fn().mockResolvedValue({code:'NoRoute'}))).rejects.toThrow('Keine');});
});
