// @vitest-environment happy-dom
import {act,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {loadGoogleMapsApi,resetGoogleMapsLoaderForTests} from '@/lib/maps/googleMapsLoader';
import {useStableGoogleMap} from '@/components/maps/useStableGoogleMap';
let errorHandler:(value:{error:Error})=>void; const removed=vi.fn(); const constructed=vi.fn();
function initialize(){window.careSuiteMapLibre={Map:class{constructor(){constructed();}addControl(){}on(event:string,handler:typeof errorHandler){if(event==='error')errorHandler=handler;}off(){}remove(){removed();}resize(){}},NavigationControl:class{},FullscreenControl:class{}} as never;document.querySelector<HTMLScriptElement>('script[data-caresuite-free-maps]')?.dispatchEvent(new Event('load'));}
beforeEach(()=>{(globalThis as Record<string,unknown>).IS_REACT_ACT_ENVIRONMENT=true;vi.useFakeTimers();const happy=window as unknown as {happyDOM:{settings:{disableJavaScriptFileLoading:boolean;handleDisabledFileLoadingAsSuccess:boolean}}};happy.happyDOM.settings.disableJavaScriptFileLoading=true;happy.happyDOM.settings.handleDisabledFileLoadingAsSuccess=false;const append=document.head.appendChild.bind(document.head);vi.spyOn(document.head,'appendChild').mockImplementation(node=>{if(node instanceof HTMLScriptElement)node.type='text/plain';return append(node);});resetGoogleMapsLoaderForTests();delete window.careSuiteMapLibre;removed.mockClear();constructed.mockClear();});
afterEach(()=>{resetGoogleMapsLoaderForTests();document.querySelectorAll('script[data-caresuite-free-maps]').forEach(s=>s.remove());delete window.careSuiteMapLibre;vi.useRealTimers();vi.restoreAllMocks();});
it('bounds SDK loading and permits retry without a paid provider',async()=>{const assertion=expect(loadGoogleMapsApi()).rejects.toThrow(/antwortet nicht/);await vi.advanceTimersByTimeAsync(15000);await assertion;expect(document.querySelector('script[data-caresuite-free-maps]')).toBeNull();const retry=loadGoogleMapsApi();initialize();expect((await retry).maps.Map).toBeDefined();});
it('shares SDK loading but creates tenant-scoped geocoders',async()=>{const first=loadGoogleMapsApi(undefined,'one'),second=loadGoogleMapsApi(undefined,'two');expect(document.querySelectorAll('script[data-caresuite-free-maps]')).toHaveLength(1);initialize();expect(await first).not.toBe(await second);expect(document.querySelector('script')?.src).not.toContain('googleapis');});
it('keeps one camera during GPS refresh, reports late failure, and disposes on retry/unmount',async()=>{function Probe({lat,retry=0}:{lat:number;retry?:number}){const ref=useRef<HTMLDivElement>(null);const state=useStableGoogleMap({apiKey:'openfreemap',containerRef:ref,center:{lat,lng:13},retryKey:retry});return <><div ref={ref}/><output>{state.error??(state.ready?'ready':'loading')}</output></>;}const host=document.createElement('div'),root=createRoot(host);await act(async()=>root.render(<Probe lat={52}/>));await act(async()=>initialize());expect(host.querySelector('output')?.textContent).toBe('ready');await act(async()=>root.render(<Probe lat={53}/>));expect(constructed).toHaveBeenCalledTimes(1);await act(async()=>errorHandler({error:new Error('Provider nicht erreichbar')}));expect(host.querySelector('output')?.textContent).toContain('nicht erreichbar');await act(async()=>root.render(<Probe lat={53} retry={1}/>));expect(constructed).toHaveBeenCalledTimes(2);expect(removed).toHaveBeenCalledTimes(1);await act(async()=>root.unmount());expect(removed).toHaveBeenCalledTimes(2);});
