import { useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Linking, ScrollView, Text, View } from 'react-native';
import { NativeAction, nativeWorkspaceStyles as ui } from '@/components/ui/NativeWorkspaceUi';
import { useGoogleWorkspace } from '@/hooks/useGoogleWorkspace.native';
import { invokeEdgeFunction } from '@/lib/supabase/edgeFunctions';
import { googleTime, WORKSPACE_SERVICES, workspaceTab, type WorkspaceTab } from '@/lib/googleWorkspace/workspaceModel';
import { WorkspaceServicePanel } from './WorkspaceServicePanel.native';
export function WorkspaceDashboard({ initialTab, callbackResult }: { initialTab?: string; callbackResult?: string }) {
  const router = useRouter(); const state = useGoogleWorkspace(); const [tab, setTab] = useState<WorkspaceTab>(workspaceTab(initialTab)); const [disconnectPrompt, setDisconnectPrompt] = useState(false);
  useEffect(() => { setTab(workspaceTab(initialTab)); }, [initialTab]);
  useEffect(() => { if (callbackResult) void state.refresh(); }, [callbackResult, state.refresh]);
  const connected = state.connection?.status === 'connected'; const connection = state.connection;
  return <View style={ui.stack}>
    <View style={ui.surface}><Text accessibilityRole="header" style={ui.title}>Ihr Google-Arbeitsplatz</Text><Text style={ui.body}>E-Mails, Termine, Dateien und Aufgaben.</Text><Text style={ui.label}>{state.loading ? 'Status wird geladen …' : connected ? 'Verbunden' : 'Nicht verbunden'}</Text>{connected ? <><Text style={ui.body}>{connection?.email}</Text><Text style={ui.muted}>{Object.values(connection?.capabilities ?? {}).filter(Boolean).length} von zehn Diensten freigegeben</Text></> : null}
      {state.error ? <Text accessibilityRole="alert" style={ui.error}>{state.error}</Text> : null}{callbackResult === 'error' ? <Text accessibilityRole="alert" style={ui.error}>Die Google-Anmeldung wurde abgebrochen oder konnte nicht gespeichert werden. Starten Sie die Kontoverbindung erneut.</Text> : null}
      <View style={ui.row}><NativeAction label={connected ? 'Freigaben verwalten / Konto wechseln' : 'Google-Konto verbinden'} primary busy={state.actionLoading} disabled={state.loading} onPress={() => void state.connect()} /><NativeAction label="Status aktualisieren" busy={state.loading} onPress={() => void state.refresh()} />{connected ? <NativeAction label="Verbindung trennen" disabled={state.actionLoading} onPress={() => setDisconnectPrompt(true)} /> : null}</View>
    </View>
    {disconnectPrompt ? <View style={ui.surface}><Text style={ui.title}>Verbindung für diesen Betrieb trennen?</Text><Text style={ui.body}>CareSuite kann danach nicht mehr auf dieses Google-Konto zugreifen. Dateien und Nachrichten bleiben bei Google erhalten.</Text><View style={ui.row}><NativeAction label="Jetzt trennen" busy={state.actionLoading} onPress={() => { void state.disconnect().then(() => setDisconnectPrompt(false)); }} /><NativeAction label="Abbrechen" disabled={state.actionLoading} onPress={() => setDisconnectPrompt(false)} /></View></View> : null}
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 10 }}><NativeAction label="Übersicht" selected={tab === 'overview'} onPress={() => setTab('overview')} />{WORKSPACE_SERVICES.map(service => <NativeAction key={service.key} label={service.title} selected={tab === service.key} onPress={() => setTab(service.key)} />)}<NativeAction label="Aktivitäten" selected={tab === 'activity'} onPress={() => setTab('activity')} /></ScrollView>
    {tab === 'overview' ? <>{WORKSPACE_SERVICES.map(service => <View key={service.key} style={ui.surface}><Text style={ui.title}>{service.title}</Text><Text style={ui.body}>{service.description}</Text><Text style={ui.muted}>{connected ? connection?.capabilities[service.key] ? 'Freigegeben' : 'Freigabe fehlt' : 'Nicht verbunden'}</Text><NativeAction label="Arbeitsbereich öffnen" onPress={() => setTab(service.key)} /></View>)}<Text style={ui.muted}>Letzter Google-Abruf: {googleTime(connection?.lastSyncAt)}. Google-Widgets können Sie im Desktop-Center hinzufügen. Die Google-Adresse darf von Ihrer CareSuite-Anmeldung abweichen.</Text></> : tab === 'activity' ? <WorkspaceActivity key={state.scope} /> : connected && connection ? <WorkspaceServicePanel key={`${state.scope}:${connection.connectedAt}:${tab}`} service={tab} connection={connection} scope={state.scope} /> : <Text style={ui.body}>Verbinden Sie Ihr Google-Konto, um diesen Dienst zu verwenden.</Text>}
    <Text style={ui.muted}>Die Verbindung ist freiwillig. Ohne Freigabe werden keine Google-Inhalte geladen. Google-Anmeldung und die Bearbeitung von Google-Dokumenten öffnen den jeweiligen Google-Dienst.</Text><NativeAction label="Datenschutz zur Google-Verbindung" onPress={() => router.push('/datenschutz')} />
  </View>;
}
function WorkspaceActivity() {
  const [events, setEvents] = useState<any[] | null>(null); const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; setError(''); setEvents(null); void invokeEdgeFunction<{ events: any[] }>('google-workspace-auth', { action: 'activity' }).then(result => { if (!active) return; if (result.ok) setEvents(result.data.events); else setError(result.error); }).catch(() => { if (active) setError('Aktivitäten konnten nicht geladen werden.'); }); return () => { active = false; }; }, [attempt]);
  const labels: Record<string, string> = { connect: 'Konto verbunden', disconnect: 'Verbindung getrennt', gmail_send: 'E-Mail gesendet', gmail_draft: 'Entwurf gespeichert', gmail_modify: 'E-Mail aktualisiert', calendar_create: 'Termin erstellt', tasks_create: 'Aufgabe erstellt', tasks_update: 'Aufgabenstatus geändert', contacts_create: 'Kontakt erstellt', chat_send: 'Chat-Nachricht gesendet', drive_upload: 'Datei hochgeladen', drive_create_folder: 'Ordner erstellt', docs_create: 'Dokument erstellt', sheets_create: 'Tabelle erstellt', slides_create: 'Präsentation erstellt' };
  return <View style={ui.surface}><Text style={ui.title}>Letzte Aktivitäten</Text><NativeAction label="Aktualisieren" onPress={() => setAttempt(value => value + 1)} />{error ? <Text style={ui.error}>{error}</Text> : events === null ? <Text style={ui.body}>Aktivitäten werden geladen …</Text> : !events.length ? <Text style={ui.body}>Noch keine Google-Aktivitäten vorhanden.</Text> : events.map(event => <View key={event.id} style={ui.stack}><Text style={ui.label}>{labels[event.action_key] || 'Google · Datenabruf'}</Text><Text style={ui.muted}>{googleTime(event.created_at)} · {event.result_status === 'success' ? 'Erfolgreich' : event.result_status === 'blocked' ? 'Nicht ausgeführt' : 'Fehlgeschlagen'}</Text></View>)}</View>;
}
