import { useEffect, useRef, useState } from 'react';
import { invokeGoogleWorkspaceAction as invoke, type GoogleWorkspaceConnection } from '@/lib/googleWorkspace/googleWorkspaceService';
import { useWorkspacePage, refreshWorkspaceData } from '@/hooks/useGoogleWorkspace.web';
import { googleTime, plainMail, serviceDefinition, type WorkspaceItem, type WorkspaceService } from '@/lib/googleWorkspace/workspaceModel';
import type { WorkspaceFilter } from '@/lib/googleWorkspace/workspaceData.web';
import { WorkspaceActionForm } from './WorkspaceActionForm.web';

export function WorkspaceServicePanel({ service, connection, scope }: { service: WorkspaceService; connection: GoogleWorkspaceConnection; scope: string }) {
  const definition = serviceDefinition(service);
  const [filter, setFilter] = useState<WorkspaceFilter>({});
  const [pages, setPages] = useState<string[]>([]); const [selected, setSelected] = useState<string | null>(null);
  const [form, setForm] = useState(false); const [chatItem, setChatItem] = useState<WorkspaceItem>();
  const [success, setSuccess] = useState<{message: string; url?: string} | null>(null);
  const [lists, setLists] = useState<{id: string; title: string}[]>([]); const [listError, setListError] = useState('');
  const [listAttempt, setListAttempt] = useState(0);
  const needsDrive = ['docs', 'sheets', 'slides'].includes(service);
  const enabled = connection.capabilities[service] && (!needsDrive || connection.capabilities.drive);
  const result = useWorkspacePage(service, filter, enabled, connection.connectedAt ?? connection.email ?? '');
  const resetFilter = (next: WorkspaceFilter) => { setFilter(next); setPages([]); setSelected(null); };
  useEffect(() => {
    if (service !== 'tasks' || !enabled) return;
    let active = true; setListError('');
    const load = async () => { let next: string | undefined; const all: {id: string; title: string}[] = []; do { const page: any = await invoke('tasks_lists', { pageToken: next }); all.push(...(page.items ?? [])); next = page.nextPageToken; } while (next && active); if (active) setLists(all); };
    void load().catch(e => { if (active) setListError(e.message); }); return () => { active = false; };
  }, [service, enabled, listAttempt]);
  const saved = (message: string, url?: string) => { setForm(false); setChatItem(undefined); setSuccess({ message, url }); refreshWorkspaceData(scope); };
  return <section className="cs-w-stack" aria-label={definition.title}>
    <div className="cs-w-row cs-w-between"><div className="cs-w-row"><span className="cs-w-icon" style={{color: definition.color}} aria-hidden="true">{definition.glyph}</span><div><h2>{definition.title}</h2><p className="cs-w-muted">{definition.description}</p></div></div><div className="cs-w-row"><button className="cs-w-button" disabled={!enabled || result.loading} onClick={() => void result.refresh()}>Aktualisieren</button>{service !== 'chat' && <button className="cs-w-button primary" disabled={!connection.capabilities[service]} onClick={() => { setForm(true); setSuccess(null); }}>＋ {service === 'gmail' ? 'E-Mail schreiben' : service === 'drive' ? 'Hinzufügen' : 'Neu erstellen'}</button>}</div></div>
    {success && <div role="status" className="cs-w-notice success">{success.message}{success.url && <> <a href={success.url} target="_blank" rel="noopener noreferrer">In Google öffnen ↗</a></>}</div>}
    {form && <WorkspaceActionForm service={service} taskListId={filter.taskListId} item={chatItem} onSaved={saved} onCancel={() => { setForm(false); setChatItem(undefined); }}/>}
    {!enabled ? <div className="cs-w-notice">{needsDrive && connection.capabilities[service] ? 'Zum Auflisten Ihrer Dateien fehlt die Google-Drive-Freigabe. Neue Dateien können Sie oben erstellen.' : `Die Google-Freigabe für ${definition.title} fehlt.`} Erteilen Sie die fehlenden Berechtigungen über „Freigaben verwalten“.</div> : <>
      <form className="cs-w-filter" onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); const from = String(data.get('from') || ''); const to = String(data.get('to') || ''); if (from && to && from > to) { (e.currentTarget.elements.namedItem('to') as HTMLInputElement).setCustomValidity('Das Ende muss am oder nach dem Beginn liegen.'); e.currentTarget.reportValidity(); return; } resetFilter({ ...filter, pageToken: undefined, query: String(data.get('query') || ''), from, to }); }}>
        {['gmail', 'drive', 'docs', 'sheets', 'slides'].includes(service) && <label className="cs-w-field search">{service === 'gmail' ? 'Postfach durchsuchen' : 'Dateiname suchen'}<input type="search" name="query" placeholder={service === 'gmail' ? 'z. B. is:unread oder from:name@firma.de' : 'Dateiname eingeben …'}/></label>}
        {(service === 'calendar' || service === 'meet') && <><label className="cs-w-field">Von<input type="date" name="from"/></label><label className="cs-w-field">Bis<input type="date" name="to" onInput={e => e.currentTarget.setCustomValidity('')}/></label></>}
        {service === 'tasks' && <><label className="cs-w-field">Aufgabenliste<select value={filter.taskListId || '@default'} onChange={e => resetFilter({ ...filter, pageToken: undefined, taskListId: e.target.value })}><option value="@default">Standardliste</option>{lists.map(l => <option value={l.id} key={l.id}>{l.title}</option>)}</select></label><label className="cs-w-check"><input type="checkbox" checked={!!filter.completed} onChange={e => resetFilter({ ...filter, pageToken: undefined, completed: e.target.checked })}/>Erledigte einbeziehen</label></>}
        {!['tasks', 'contacts', 'chat'].includes(service) && <button className="cs-w-button" type="submit">Anwenden</button>}
      </form>
      {listError && <div className="cs-w-notice error" role="alert">Aufgabenlisten konnten nicht geladen werden: {listError} <button className="cs-w-button small" onClick={() => setListAttempt(n => n + 1)}>Erneut versuchen</button></div>}
      {result.error && <div className="cs-w-notice error" role="alert">{result.error} <button className="cs-w-button small" onClick={() => void result.refresh()}>Erneut versuchen</button>{result.data && <p>Die angezeigten Einträge stammen vom letzten erfolgreichen Abruf.</p>}</div>}
      {result.loading && <div className="cs-w-loading" role="status">{definition.title} wird geladen …</div>}
      {result.data && <div className="cs-w-row cs-w-between cs-w-muted"><span>{result.data.items.length} Einträge auf dieser Seite{result.data.nextPageToken ? ' · Weitere verfügbar' : ''}</span><span>Abgerufen: {googleTime(result.data.fetchedAt)}</span></div>}
      {result.data?.items.length ? <div className="cs-w-results">{result.data.items.map(item => <div className="cs-w-item" key={item.id}><div className="cs-w-item-head"><button className="cs-w-item-main" aria-expanded={selected === item.id} onClick={() => setSelected(selected === item.id ? null : item.id)}><strong>{item.unread && <span aria-label="Ungelesen" style={{color:'#096be0'}}>● </span>}{item.completed ? '✓ ' : ''}{item.title}</strong><span>{item.subtitle}</span></button>{item.when && <span className="cs-w-item-date">{googleTime(item.when)}</span>}{item.url && <a className="cs-w-button small" href={item.url} target="_blank" rel="noopener noreferrer">{service === 'meet' ? 'Teilnehmen' : 'Öffnen'} ↗</a>}{service === 'chat' && <button className="cs-w-button small" onClick={() => { setChatItem(item); setForm(true); }}>Nachricht</button>}</div>{selected === item.id && <ItemDetail service={service} item={item} email={connection.email} taskListId={filter.taskListId} onSaved={saved}/>}</div>)}</div> : !result.loading && !result.error && <div className="cs-w-empty"><h3>Keine Einträge gefunden</h3><p>{service === 'tasks' ? 'In dieser Auswahl sind keine Aufgaben vorhanden.' : service === 'calendar' || service === 'meet' ? 'In diesem Zeitraum sind keine passenden Termine vorhanden.' : 'Passen Sie gegebenenfalls die Auswahl an oder erstellen Sie einen Eintrag.'}</p></div>}
      <div className="cs-w-row"><button className="cs-w-button small" disabled={!pages.length || result.loading} onClick={() => { const previous = [...pages]; const token = previous.pop(); setPages(previous); setFilter({...filter, pageToken: token || undefined}); setSelected(null); }}>Vorherige Seite</button><button className="cs-w-button small" disabled={!result.data?.nextPageToken || result.loading} onClick={() => { setPages([...pages, filter.pageToken || '']); setFilter({...filter, pageToken: result.data?.nextPageToken}); setSelected(null); }}>Weitere laden</button></div>
    </>}
  </section>;
}
function ItemDetail({service, item, email, taskListId, onSaved}: {service: WorkspaceService; item: WorkspaceItem; email: string | null; taskListId?: string; onSaved: (text: string) => void}) {
  const [message, setMessage] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [attempt, setAttempt] = useState(0); const lock = useRef(false);
  useEffect(() => { if (service !== 'gmail') return; let active = true; setError(''); setMessage(null); void invoke<any>('gmail_read', {id: item.id}).then(m => { if (active) setMessage(m); }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [item.id, service, attempt]);
  const change = async () => { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await invoke(service === 'tasks' ? 'tasks_update' : 'gmail_modify', service === 'tasks' ? { id: item.id, taskListId: taskListId || '@default', task: { status: item.completed ? 'needsAction' : 'completed' } } : { id: item.id, removeLabelIds: ['UNREAD'] }, true); onSaved(service === 'tasks' ? 'Aufgabenstatus in Google aktualisiert.' : 'E-Mail als gelesen markiert.'); } catch (e) { setError(e instanceof Error ? e.message : 'Änderung fehlgeschlagen.'); } finally { lock.current = false; setBusy(false); } };
  return <div className="cs-w-detail cs-w-stack">
    {error && <div className="cs-w-notice error" role="alert">{error}{service === 'gmail' && <button className="cs-w-button small" onClick={() => setAttempt(n => n + 1)}>Erneut laden</button>}</div>}
    {service === 'gmail' ? <>{!message && !error ? <p role="status">Nachricht wird geladen …</p> : message && <pre className="cs-w-mail">{plainMail(message.payload) || 'Diese Nachricht enthält keinen lesbaren Klartext. Öffnen Sie sie in Gmail, um die vollständige Darstellung und Anhänge zu sehen.'}</pre>}<div className="cs-w-row"><a className="cs-w-button small" target="_blank" rel="noopener noreferrer" href={`https://mail.google.com/mail/u/?authuser=${encodeURIComponent(email || '')}#inbox/${encodeURIComponent(item.raw?.threadId || item.id)}`}>In Gmail öffnen / antworten ↗</a>{item.unread && <button disabled={busy} onClick={() => void change()} className="cs-w-button small">Als gelesen markieren</button>}</div></> : <><p style={{whiteSpace:'pre-wrap', overflowWrap:'anywhere'}}>{service === 'tasks' ? item.raw?.notes || 'Keine Notizen.' : service === 'calendar' || service === 'meet' ? item.raw?.description?.replace(/<[^>]*>/g, '') || 'Keine Beschreibung.' : item.subtitle}</p>{service === 'tasks' && <button className="cs-w-button small" disabled={busy} onClick={() => void change()}>{busy ? 'Wird gespeichert …' : item.completed ? 'Wieder öffnen' : 'Als erledigt markieren'}</button>}{(service === 'calendar' || service === 'meet') && <p className="cs-w-muted">Ende: {googleTime(item.raw?.end?.dateTime || item.raw?.end?.date)}</p>}</>}
  </div>;
}
