import { useEffect, useState } from 'react';
import { invokeEdgeFunction } from '@/lib/supabase/edgeFunctions';
import { useGoogleWorkspace, useWorkspacePage } from '@/hooks/useGoogleWorkspace.web';
import { googleTime, serviceDefinition, WORKSPACE_SERVICES, workspaceTab, type WorkspaceTab, type WorkspaceService } from '@/lib/googleWorkspace/workspaceModel';
import type { GoogleWorkspaceConnection } from '@/lib/googleWorkspace/googleWorkspaceService';
import { WorkspaceServicePanel } from './WorkspaceServicePanel.web';
import { workspaceCss } from './workspaceCss.web';

export function WorkspaceDashboard({initialTab, callbackResult, fontScale = 1}: {initialTab?: string; callbackResult?: string; fontScale?: number}) {
  const state = useGoogleWorkspace();
  const [tab, setTab] = useState<WorkspaceTab>(workspaceTab(initialTab));
  const [disconnectPrompt, setDisconnectPrompt] = useState(false);
  useEffect(() => { setTab(workspaceTab(initialTab)); }, [initialTab]);
  const connection = state.connection;
  const connected = connection?.status === 'connected';
  const count = Object.values(connection?.capabilities ?? {}).filter(Boolean).length;
  return <div className="cs-workspace cs-w-stack" style={{fontSize:16 * fontScale}}><style>{workspaceCss}</style>
    {callbackResult === 'error' && <div role="alert" className="cs-w-notice error"><strong>Google-Freigabe nicht abgeschlossen</strong><p>Die Anmeldung wurde abgebrochen oder konnte nicht gespeichert werden. Starten Sie die Kontoverbindung erneut und erteilen Sie die benötigten Freigaben.</p></div>}
    {callbackResult === 'connected' && connected && <div role="status" className="cs-w-notice success">Google-Konto erfolgreich verbunden. {count} Dienste sind freigegeben.</div>}
    {state.error && <div className="cs-w-notice error" role="alert">{state.error} <button className="cs-w-button small" onClick={() => void state.refresh()}>Erneut laden</button></div>}
    <section className="cs-w-hero">
      <div className="cs-w-stack"><div><span className="cs-w-eyebrow">CareSuite · Zusammenarbeit</span><h2 className="cs-w-title">Ihr Google-Arbeitsplatz</h2><p>E-Mails, Termine, Dateien und Aufgaben an einem Ort.</p></div><div className="cs-w-row"><span className={`cs-w-pill ${connected ? 'good' : state.error ? 'bad' : 'warn'}`}>{state.loading ? 'Status wird geladen …' : state.error ? 'Status nicht bestätigt' : connected ? '● Verbunden' : '○ Nicht verbunden'}</span>{connected && <span className="cs-w-pill">{count} von 10 Diensten freigegeben</span>}</div>{connected && <strong className="cs-w-account">{connection?.email || 'Google-Konto'}{connection?.domain && <span className="cs-w-muted"> · {connection.domain}</span>}</strong>}</div>
      <div className="cs-w-hero-actions">{connected ? <><button className="cs-w-button primary" disabled={state.actionLoading} onClick={() => void state.connect()}>Freigaben verwalten / Konto wechseln</button><button className="cs-w-button" disabled={state.loading} onClick={() => void state.refresh()}>Status aktualisieren</button><button className="cs-w-button danger" disabled={state.actionLoading} onClick={() => setDisconnectPrompt(true)}>Verbindung trennen</button></> : <button className="cs-w-button primary" disabled={state.loading || state.actionLoading} onClick={() => void state.connect()}>{state.actionLoading ? 'Google wird geöffnet …' : 'Google-Konto verbinden'}</button>}</div>
    </section>
    <p className="cs-w-muted" style={{ fontSize: '0.9em', lineHeight: 1.65 }}>Die Verbindung ist freiwillig. Google-Daten werden für die freigegebenen Workspace-Funktionen verarbeitet. <a href="https://www.caresuiteplus.app/datenschutz#google-workspace" target="_blank" rel="noopener noreferrer" style={{ color: '#0869d4' }}>Datenschutz zur Google-Verbindung</a> · <a href="https://www.caresuiteplus.app/nutzungsbedingungen#abschnitt-6" target="_blank" rel="noopener noreferrer" style={{ color: '#0869d4' }}>Nutzungsbedingungen</a></p>
    {disconnectPrompt && <div className="cs-w-notice cs-w-stack" role="alert"><strong>Verbindung für diesen Betrieb trennen?</strong><p>CareSuite kann danach nicht mehr auf dieses Google-Konto zugreifen. Dateien und Nachrichten bleiben bei Google erhalten.</p><div className="cs-w-row"><button className="cs-w-button danger" disabled={state.actionLoading} onClick={async () => { await state.disconnect(); setDisconnectPrompt(false); }}>Jetzt trennen</button><button className="cs-w-button" disabled={state.actionLoading} onClick={() => setDisconnectPrompt(false)}>Abbrechen</button></div></div>}
    {!connected && !state.loading && !state.error && <div className="cs-w-card cs-w-stack"><h3>Einmal verbinden, direkt arbeiten</h3><p>Wählen Sie Ihr betriebliches Google-Konto aus und geben Sie die gewünschten Dienste frei. Die Google-Adresse darf von Ihrer CareSuite-Anmeldung abweichen.</p><p className="cs-w-muted">Das verbundene Konto wird von der Geschäftsführung und Verwaltung dieses Betriebs genutzt. Ohne Freigabe werden keine Google-Inhalte geladen.</p></div>}
    <nav className="cs-w-nav" aria-label="Google-Dienste"><button className="cs-w-tab" aria-pressed={tab === 'overview'} onClick={() => setTab('overview')}>Übersicht</button>{WORKSPACE_SERVICES.map(s => <button className="cs-w-tab" key={s.key} aria-pressed={tab === s.key} onClick={() => setTab(s.key)}>{s.title.replace('Google ', '')}</button>)}<button className="cs-w-tab" aria-pressed={tab === 'activity'} onClick={() => setTab('activity')}>Aktivitäten</button></nav>
    {tab === 'overview' ? <>
      {connected && connection && <div className="cs-w-metrics">{(['gmail','calendar','drive','tasks'] as const).map(service => <OverviewCard key={`${state.scope}:${connection.connectedAt}:${service}`} service={service} connection={connection} onOpen={() => setTab(service)}/>)}</div>}
      <div className="cs-w-row cs-w-between"><h2>Ihre Dienste</h2><span className="cs-w-muted">Für jeden Dienst ist eine Google-Freigabe erforderlich.</span></div>
      <div className="cs-w-service-grid">{WORKSPACE_SERVICES.map(s => <button className="cs-w-service-card" key={s.key} onClick={() => setTab(s.key)}><div className="cs-w-row cs-w-between"><span className="cs-w-icon" style={{color:s.color}} aria-hidden="true">{s.glyph}</span><span className={`cs-w-pill ${connected && connection?.capabilities[s.key] ? 'good' : ''}`}>{connected ? connection?.capabilities[s.key] ? 'Freigegeben' : 'Freigabe fehlt' : 'Nicht verbunden'}</span></div><h3>{s.title}</h3><p className="cs-w-muted">{s.description}</p><span style={{color:'#0869d4',fontSize:'.85em',fontWeight:650}}>Arbeitsbereich öffnen →</span></button>)}</div>
      <div className="cs-w-card cs-w-stack"><h3>Desktop-Widgets</h3><p>Unter „Apps & Widgets“ auf Ihrem Desktop finden Sie Google Workspace, Gmail, Google-Kalender, Google Drive und Google Tasks. Mit „Zum Desktop“ fügen Sie die gewünschten Widgets hinzu.</p><div className="cs-w-split-info"><div><div className="cs-w-muted">Letzter erfolgreicher Google-Abruf</div><strong>{googleTime(connection?.lastSyncAt)}</strong></div><div><div className="cs-w-muted">Verbunden seit</div><strong>{connection?.connectedAt ? googleTime(connection.connectedAt) : 'Noch nicht verbunden'}</strong></div></div><p className="cs-w-muted">Daten werden beim Öffnen und über „Aktualisieren“ abgerufen. Sichtbare Widgets prüfen ungefähr alle zwei Minuten auf neue Inhalte. Es werden keine Google-Daten automatisch in Klientenakten oder CareSuite-Einsätze übernommen.</p></div>
    </> : tab === 'activity' ? <WorkspaceActivity/> : connected && connection ? <WorkspaceServicePanel key={`${state.scope}:${connection.connectedAt}:${tab}`} service={tab} connection={connection} scope={state.scope}/> : <div className="cs-w-empty"><h3>{serviceDefinition(tab).title} verbinden</h3><p>Verbinden Sie oben Ihr Google-Konto, um diesen Dienst in CareSuite zu verwenden.</p></div>}
  </div>;
}
function OverviewCard({service, connection, onOpen}: {service: WorkspaceService; connection: GoogleWorkspaceConnection; onOpen: () => void}) {
  const def = serviceDefinition(service); const page = useWorkspacePage(service, {}, connection.capabilities[service], connection.connectedAt ?? '');
  return <section className="cs-w-metric"><div className="cs-w-row cs-w-between"><h3>{def.title}</h3><button className="cs-w-button small" onClick={onOpen}>Öffnen →</button></div>{!connection.capabilities[service] ? <p className="cs-w-muted">Google-Freigabe fehlt.</p> : page.error ? <p role="alert" className="cs-w-muted">Abruf fehlgeschlagen. Öffnen Sie den Dienst, um es erneut zu versuchen.</p> : page.loading && !page.data ? <p role="status" className="cs-w-muted">Wird geladen …</p> : <div className="cs-w-preview-list">{page.data?.items.length ? page.data.items.slice(0,3).map(item => <div key={item.id} className="cs-w-preview-item"><strong>{item.unread ? '● ' : ''}{item.title}</strong><span>{item.when ? googleTime(item.when) : item.subtitle}</span></div>) : <p className="cs-w-muted">Keine Einträge vorhanden.</p>}</div>}<span className="cs-w-muted">Abruf: {googleTime(page.data?.fetchedAt)}</span></section>;
}
function WorkspaceActivity() {
  const [events, setEvents] = useState<any[] | null>(null); const [error, setError] = useState(''); const [attempt, setAttempt] = useState(0);
  useEffect(() => { let active = true; setError(''); setEvents(null); void invokeEdgeFunction<{events: any[]}>('google-workspace-auth', { action:'activity' }).then(result => { if (!active) return; if (result.ok) setEvents(result.data.events); else setError(result.error); }).catch(() => { if (active) setError('Aktivitäten konnten nicht geladen werden.'); }); return () => { active = false; }; }, [attempt]);
  const labels: Record<string,string> = { connect:'Konto verbunden',disconnect:'Verbindung getrennt',gmail_send:'E-Mail gesendet',gmail_draft:'Entwurf gespeichert',gmail_modify:'E-Mail aktualisiert',calendar_create:'Termin erstellt',tasks_create:'Aufgabe erstellt',tasks_update:'Aufgabenstatus geändert',contacts_create:'Kontakt erstellt',chat_send:'Chat-Nachricht gesendet',drive_upload:'Datei hochgeladen',drive_create_folder:'Ordner erstellt',docs_create:'Dokument erstellt',sheets_create:'Tabelle erstellt',slides_create:'Präsentation erstellt' };
  return <section className="cs-w-card cs-w-stack"><div className="cs-w-row cs-w-between"><h2>Letzte Aktivitäten</h2><button className="cs-w-button small" onClick={() => setAttempt(n => n + 1)}>Aktualisieren</button></div><p className="cs-w-muted">Die letzten 30 Anfragen dieses Betriebs mit Ergebnis und Zeitpunkt.</p>{error ? <div role="alert" className="cs-w-notice error">{error}</div> : events === null ? <p role="status">Aktivitäten werden geladen …</p> : !events.length ? <p>Noch keine Google-Aktivitäten vorhanden.</p> : events.map(event => <div className="cs-w-audit" key={event.id}><div><strong>{labels[event.action_key] || `${WORKSPACE_SERVICES.find(s => s.key === event.service_key)?.title || 'Google'} · Datenabruf`}</strong><div className="cs-w-muted">{googleTime(event.created_at)}</div></div><span className={`cs-w-pill ${event.result_status === 'success' ? 'good' : 'bad'}`}>{event.result_status === 'success' ? 'Erfolgreich' : event.result_status === 'blocked' ? 'Nicht ausgeführt' : 'Fehlgeschlagen'}</span></div>)}</section>;
}
