"use client";
import {useEffect,useRef} from 'react';
const vertex=`attribute vec2 position;void main(){gl_Position=vec4(position,0.,1.);}`;
const fragment=`precision highp float;
uniform vec2 resolution;uniform vec2 pointer;uniform float time;uniform float scroll;
float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}
void main(){vec2 uv=gl_FragCoord.xy/resolution;vec2 p=(2.*gl_FragCoord.xy-resolution)/resolution.y;float t=time;vec3 col=vec3(.006,.014,.034);vec2 halo=p-vec2(.8,.1);col+=vec3(.006,.027,.08)*exp(-dot(halo,halo)*.58);float light=smoothstep(.06,.92,uv.x);
for(int i=0;i<4;i++){float k=float(i);float phase=k*1.71;vec2 q=p*(1.+k*.1+scroll*.18);q-=pointer*(.05+k*.024);q.y+=scroll*(.2+k*.09);q.x+=.14*sin(q.y*1.7+phase+t*.095);float bend=.36*sin(q.x*1.12+phase+t*.13)+.12*sin(q.x*2.65-phase-t*.09);float center=bend+(k-1.5)*.29-q.x*.24;float d=q.y-center;float width=.13+.025*sin(q.x*1.3+phase);float sheet=exp(-(d*d)/(width*width));float fold=exp(-abs(d+width*.55)*39.);float fibers=pow(.5+.5*sin(d*(82.+k*9.)+1.6*sin(q.x*3.2+phase-t*.13)),9.)*sheet;float pulse=.76+.24*sin(q.x*.9-t*.16+phase);vec3 tint=mix(vec3(.018,.13,.48),vec3(.025,.59,.78),k/3.);col+=tint*(sheet*.12+fold*.40+fibers*.065)*pulse*(.18+light*.82);}
vec2 c=p+pointer*.035;float field=sin(c.x*2.8+sin(c.y*2.2)+t*.11)+sin(c.y*3.9+sin(c.x*1.9)-t*.09);float caustic=pow(max(0.,1.-abs(field)*.5),18.);col+=vec3(.008,.075,.11)*caustic*light*.4;vec2 portal=p-vec2(.5,-.12)-pointer*.09;
float radius=length(portal);float angle=atan(portal.y,portal.x);
float ringRadius=.70+.045*sin(angle*3.-t*.25)+.015*sin(angle*9.+t*.4);
float ring=exp(-abs(radius-ringRadius)*75.);
float bloom=exp(-abs(radius-ringRadius)*8.);
float orbit=pow(.5+.5*sin(angle*8.-radius*14.+t*.48),12.);
col+=vec3(.16,.56,1.)*ring*(.48+orbit*.9)+vec3(.035,.14,.35)*bloom;
for(int j=0;j<3;j++){float n=float(j);float r=.91+n*.17+.016*sin(angle*(4.+n)+t*.14);float seam=exp(-abs(radius-r)*95.);float sweep=pow(.5+.5*sin(angle*2.+t*(.18+n*.045)+n*2.),10.);col+=mix(vec3(.10,.27,.76),vec3(.2,.76,.92),n/2.)*seam*(.035+sweep*.15);}
col+=vec3(.005,.038,.105)*exp(-radius*radius*4.);
float dist=length(p-pointer*vec2(resolution.x/resolution.y,1.));col+=vec3(.012,.09,.16)*exp(-dist*dist*3.)*.4;col*=1.-.3*smoothstep(.25,1.1,length(uv-.5));col+=(hash(gl_FragCoord.xy)-.5)/255.;gl_FragColor=vec4(clamp(col,0.,1.),1.);}`;
export function AmbientField({paused}:{paused:boolean}){
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const node=canvas.current;if(!node)return;const gl=node.getContext('webgl',{alpha:false,antialias:false,depth:false,powerPreference:'low-power'});if(!gl){node.dataset.renderer='fallback';return;}node.dataset.renderer='webgl';const shaders:WebGLShader[]=[];const make=(type:number,code:string)=>{const shader=gl.createShader(type);if(!shader)return null;shaders.push(shader);gl.shaderSource(shader,code);gl.compileShader(shader);return gl.getShaderParameter(shader,gl.COMPILE_STATUS)?shader:null};const vs=make(gl.VERTEX_SHADER,vertex),fs=make(gl.FRAGMENT_SHADER,fragment),program=gl.createProgram();if(!vs||!fs||!program){shaders.forEach(s=>gl.deleteShader(s));node.dataset.renderer='fallback';return;}gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS)){gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s));node.dataset.renderer='fallback';return;}gl.useProgram(program);const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'position');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(program,'resolution'),up=gl.getUniformLocation(program,'pointer'),ut=gl.getUniformLocation(program,'time'),us=gl.getUniformLocation(program,'scroll');let raf=0,last=0,elapsed=10,x=0,y=0,tx=0,ty=0,s=0,targetScroll=0;
 const resize=()=>{const d=Math.min(devicePixelRatio,innerWidth<700?.65:.85);node.width=Math.floor(innerWidth*d);node.height=Math.floor(innerHeight*d);gl.viewport(0,0,node.width,node.height);gl.uniform2f(ur,node.width,node.height)};
 const pointer=(e:PointerEvent)=>{if(e.pointerType==='touch')return;tx=e.clientX/innerWidth*2-1;ty=1-e.clientY/innerHeight*2};const scroll=()=>{targetScroll=scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)};const leave=()=>{tx=0;ty=0};const draw=()=>{gl.uniform2f(up,x,y);gl.uniform1f(ut,elapsed);gl.uniform1f(us,s);gl.drawArrays(gl.TRIANGLES,0,3)};const render=(now:number)=>{raf=requestAnimationFrame(render);if(document.hidden){last=now;return;}if(now-last<32)return;const dt=Math.min((now-last)/1000,.06);last=now;elapsed+=dt;const f=1-Math.exp(-dt*4);x+=(tx-x)*f;y+=(ty-y)*f;s+=(targetScroll-s)*f;draw()};resize();scroll();draw();if(!paused){raf=requestAnimationFrame(render);window.addEventListener('pointermove',pointer,{passive:true});window.addEventListener('scroll',scroll,{passive:true});document.addEventListener('pointerleave',leave);}window.addEventListener('resize',resize);return()=>{cancelAnimationFrame(raf);window.removeEventListener('pointermove',pointer);window.removeEventListener('scroll',scroll);document.removeEventListener('pointerleave',leave);window.removeEventListener('resize',resize);gl.deleteBuffer(buffer);gl.deleteProgram(program);shaders.forEach(s=>gl.deleteShader(s));};},[paused]);
 return <canvas ref={canvas} className="ambient-field" aria-hidden="true"/>
}
