"use client";
import {useEffect,useRef,useState} from 'react';
import {AudioLines,Grip,RotateCcw,Volume2,VolumeX} from 'lucide-react';
const introduction='Ich bin Neo, dein kleiner Assistent in deinem CareSuite Health OS.';
type AudioStatus='idle'|'loading'|'speaking'|'blocked'|'error';
export function NeoCompanion(){
 const root=useRef<HTMLDivElement>(null),robot=useRef<HTMLButtonElement>(null),audio=useRef<HTMLAudioElement>(null),attempt=useRef(0),gestureMoved=useRef(false);
 const position=useRef({x:0,y:0}),drag=useRef<{id:number;x:number;y:number;ox:number;oy:number}|null>(null);
 const [status,setStatus]=useState<AudioStatus>('idle'),[muted,setMuted]=useState(false),[moved,setMoved]=useState(false);
 const stop=()=>{attempt.current++;const player=audio.current;if(player){player.pause();player.currentTime=0}setStatus('idle')};
 useEffect(()=>{const player=audio.current;const hide=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',hide);const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)stop()},{threshold:.05});if(root.current)observer.observe(root.current);return()=>{attempt.current++;player?.pause();document.removeEventListener('visibilitychange',hide);observer.disconnect()}},[]);
 const speak=()=>{const player=audio.current;if(!player||muted)return;const request=++attempt.current;if(player.error)player.load();player.muted=false;player.volume=1;player.currentTime=0;setStatus('loading');
 // Keep play() in the trusted tap/click call stack. No fetch, timeout or voice lookup.
 const playback=player.play();playback?.then(()=>{if(attempt.current===request&&!player.paused)setStatus('speaking')}).catch((error:DOMException)=>{if(attempt.current!==request)return;setStatus(error.name==='NotAllowedError'?'blocked':error.name==='AbortError'?'idle':'error')});
 };
 const move=(x:number,y:number)=>{if(!root.current||!robot.current)return;const rect=root.current.getBoundingClientRect();position.current={x:Math.max(-rect.width*.19,Math.min(rect.width*.19,x)),y:Math.max(-rect.height*.13,Math.min(rect.height*.13,y))};robot.current.style.setProperty('--neo-x',position.current.x+'px');robot.current.style.setProperty('--neo-y',position.current.y+'px')};
 const end=()=>{drag.current=null;robot.current?.classList.remove('is-dragging')};
 return <div className={'neo-companion '+(status==='speaking'?'is-speaking':'')} ref={root}><div className="neo-sphere" aria-hidden="true"/><div className="neo-hologram-ring ring-a" aria-hidden="true"/><div className="neo-hologram-ring ring-b" aria-hidden="true"/><div className="neo-hologram-ring ring-c" aria-hidden="true"/>
 <button className="neo-avatar" ref={robot} aria-label="Neo anhören. Zum Verschieben ziehen oder Pfeiltasten verwenden." onClick={()=>{if(!gestureMoved.current){if(status==='speaking'||status==='loading')stop();else speak()}gestureMoved.current=false}} onPointerDown={e=>{if(e.button!==0)return;gestureMoved.current=false;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,ox:position.current.x,oy:position.current.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>8){gestureMoved.current=true;setMoved(true);e.currentTarget.classList.add('is-dragging');move(d.ox+e.clientX-d.x,d.oy+e.clientY-d.y)}}} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{const directions:Record<string,[number,number]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};const d=directions[e.key];if(d){e.preventDefault();move(position.current.x+d[0],position.current.y+d[1]);setMoved(true)}if(e.key==='Home'){move(0,0);setMoved(false)}}}><img src="/landingpage/media/neo.png" alt="Neo, der männliche CareSuite-Assistent" width="1000" height="1000" draggable={false} fetchPriority="high"/><span className="neo-drag-pill"><Grip size={14}/> Frei beweglich</span></button>
 <div className="neo-voice-card"><div className="neo-voice-heading"><AudioLines size={24}/><div><strong>Hi. Ich bin Neo.</strong><span aria-live="polite">{muted?'Ton ist ausgeschaltet.':status==='speaking'?'Schön, dich kennenzulernen.':status==='loading'?'Meine Stimme wird geladen …':status==='blocked'?'Tippe noch einmal auf „Neo anhören“.':status==='error'?'Audio konnte nicht geladen werden. Bitte erneut versuchen.':'Tippe auf Play. Wir lernen uns kennen.'}</span></div><button className="round-control" onClick={()=>{if(!muted)stop();if(audio.current){audio.current.muted=!muted;if(muted)audio.current.volume=1}setMuted(!muted)}} aria-label={muted?'Neo-Ton einschalten':'Neo stummschalten'} aria-pressed={muted}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button></div><div className="neo-voice-actions"><button className="voice-play" disabled={muted} aria-pressed={status==='speaking'||status==='loading'} onClick={()=>status==='speaking'||status==='loading'?stop():speak()}>{status==='speaking'||status==='loading'?'Vorstellung stoppen':status==='error'?'Erneut versuchen':'Neo anhören'}</button><button className="neo-reset" onClick={()=>{move(0,0);setMoved(false)}} disabled={!moved} aria-label="Neo zurücksetzen"><RotateCcw size={15}/></button><span className="voice-wave" aria-hidden="true">{Array.from({length:15},(_,i)=><i key={i} style={{animationDelay:`${i*.07}s`,height:`${6+i*11%22}px`}}/>)}</span></div><details className="neo-transcript"><summary>Vorstellung & Audioplayer</summary><p>{introduction}</p><audio className="neo-native-audio" ref={audio} controls preload="auto" src="/landingpage/media/neo-introduction.mp3" aria-label="Neos Originalstimme" onPlay={()=>setStatus('loading')} onPlaying={()=>setStatus('speaking')} onWaiting={()=>setStatus('loading')} onVolumeChange={e=>setMuted(e.currentTarget.muted||e.currentTarget.volume===0)} onEnded={()=>setStatus('idle')} onPause={()=>setStatus('idle')} onError={()=>setStatus('error')}/></details></div>
 </div>
}
