"use client";
import {useEffect,useRef,useState} from 'react';
import {selectNeoVoice} from './neo-voice';
import {AudioLines,Grip,RotateCcw,Volume2,VolumeX} from 'lucide-react';

const introduction='Hallo, ich bin Neo. Dein persönlicher Assistent. Ich helfe dir, dich zurechtzufinden, und begleite dich durch deinen digitalen Arbeitsalltag. Schön, dass du da bist.';
export function NeoCompanion(){
  const root=useRef<HTMLDivElement>(null),robot=useRef<HTMLButtonElement>(null);
  const gestureMoved=useRef(false);
  const position=useRef({x:0,y:0}),drag=useRef<{id:number;x:number;y:number;ox:number;oy:number}|null>(null);
  const voices=useRef<SpeechSynthesisVoice[]>([]),speech=useRef<SpeechSynthesisUtterance|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),watchdog=useRef<ReturnType<typeof setTimeout>|null>(null),source=useRef<'hover'|'click'>('click'),hovered=useRef(false);
  const [status,setStatus]=useState<'idle'|'speaking'|'blocked'|'unsupported'|'unavailable'|'loading'>('idle'),[muted,setMuted]=useState(false),[moved,setMoved]=useState(false);
  const clearTimers=()=>{if(timer.current)clearTimeout(timer.current);if(watchdog.current)clearTimeout(watchdog.current);timer.current=null;watchdog.current=null;};
  const stop=()=>{clearTimers();speech.current=null;if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();setStatus(v=>v==='unsupported'?'unsupported':'idle');};
  useEffect(()=>{if(!('speechSynthesis' in window)){setStatus('unsupported');return;}const synth=window.speechSynthesis;const update=()=>{voices.current=synth.getVoices();if(selectNeoVoice(voices.current))setStatus(v=>v==='unavailable'?'idle':v)};update();synth.addEventListener('voiceschanged',update);const hide=()=>{if(document.hidden)stop()};document.addEventListener('visibilitychange',hide);const node=root.current;const observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting)stop()},{threshold:.05});if(node)observer.observe(node);return()=>{clearTimers();speech.current=null;synth.cancel();synth.removeEventListener('voiceschanged',update);document.removeEventListener('visibilitychange',hide);observer.disconnect()}},[]);
  const speak=(kind:'hover'|'click')=>{if(muted||speech.current||status==='speaking'||status==='loading')return;if(!('speechSynthesis' in window)){setStatus('unsupported');return;}clearTimers();const synth=window.speechSynthesis;synth.cancel();const utterance=new SpeechSynthesisUtterance(introduction);const available=voices.current.length?voices.current:synth.getVoices();const voice=selectNeoVoice(available);if(!voice){setStatus('unavailable');return;}utterance.voice=voice;let started=false;utterance.lang='de-DE';utterance.rate=.9;utterance.pitch=1;utterance.volume=.85;speech.current=utterance;source.current=kind;setStatus('loading');utterance.onstart=()=>{if(speech.current!==utterance)return;started=true;if(watchdog.current)clearTimeout(watchdog.current);setStatus('speaking');hovered.current=true};utterance.onend=()=>{if(speech.current!==utterance)return;if(watchdog.current)clearTimeout(watchdog.current);speech.current=null;setStatus('idle')};utterance.onerror=event=>{if(speech.current!==utterance)return;if(watchdog.current)clearTimeout(watchdog.current);speech.current=null;setStatus(event.error==='canceled'||event.error==='interrupted'?'idle':event.error==='not-allowed'?'blocked':'unavailable')};synth.speak(utterance);watchdog.current=setTimeout(()=>{if(speech.current===utterance&&!started){speech.current=null;synth.cancel();setStatus('blocked')}},6000)};
  const enter=()=>{if(timer.current)clearTimeout(timer.current);if(hovered.current||muted||drag.current)return;timer.current=setTimeout(()=>speak('hover'),600)};
  const leave=()=>{if(timer.current)clearTimeout(timer.current);if(source.current==='hover'&&speech.current)stop()};
  const move=(x:number,y:number)=>{if(!root.current||!robot.current)return;const rect=root.current.getBoundingClientRect();position.current={x:Math.max(-rect.width*.19,Math.min(rect.width*.19,x)),y:Math.max(-rect.height*.13,Math.min(rect.height*.13,y))};robot.current.style.setProperty('--neo-x',position.current.x+'px');robot.current.style.setProperty('--neo-y',position.current.y+'px')};
  const end=()=>{drag.current=null;robot.current?.classList.remove('is-dragging')};
  return <div className={'neo-companion '+(status==='speaking'?'is-speaking':'')} ref={root}>
    <div className="neo-sphere" aria-hidden="true"/><div className="neo-hologram-ring ring-a"/><div className="neo-hologram-ring ring-b"/><div className="neo-hologram-ring ring-c"/>
    <button className="neo-avatar" ref={robot} aria-label="Neo kennenlernen. Zum Verschieben ziehen oder Pfeiltasten verwenden." onMouseEnter={enter} onMouseLeave={leave} onFocus={enter} onBlur={leave} onClick={()=>{if(!gestureMoved.current)speak('click');gestureMoved.current=false}} onPointerDown={e=>{if(e.button!==0)return;gestureMoved.current=false;drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,ox:position.current.x,oy:position.current.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||d.id!==e.pointerId)return;if(Math.abs(e.clientX-d.x)+Math.abs(e.clientY-d.y)>5){gestureMoved.current=true;setMoved(true);if(timer.current)clearTimeout(timer.current);e.currentTarget.classList.add('is-dragging');move(d.ox+e.clientX-d.x,d.oy+e.clientY-d.y)}}} onPointerUp={end} onPointerCancel={end} onLostPointerCapture={end} onKeyDown={e=>{const directions:Record<string,[number,number]>={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]};const d=directions[e.key];if(d){e.preventDefault();move(position.current.x+d[0],position.current.y+d[1]);setMoved(true)}if(e.key==='Home'){move(0,0);setMoved(false)}}}><img src="/landingpage/media/neo.png" alt="Neo, der männliche CareSuite-Assistent" width="1000" height="1000" draggable={false} fetchPriority="high"/><span className="neo-drag-pill"><Grip size={14}/> Frei beweglich</span></button>
    <div className="neo-voice-card"><div className="neo-voice-heading"><AudioLines size={24}/><div><strong>Hi. Ich bin Neo.</strong><span>{status==='speaking'?'Ich stelle mich gerade vor.':status==='loading'?'Einen kleinen Moment …':status==='blocked'?'Zum Anhören bitte kurz klicken.':status==='unsupported'||status==='unavailable'?'Meine männliche Stimme ist hier gerade nicht verfügbar.':'Berühre meine Welt. Hör meine Stimme.'}</span></div><button className="round-control" onClick={()=>{if(!muted)stop();setMuted(!muted)}} aria-label={muted?'Neo-Ton einschalten':'Neo stummschalten'}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}</button></div><div className="neo-voice-actions"><button className="voice-play" disabled={muted||status==='unsupported'} onClick={()=>status==='speaking'||status==='loading'?stop():speak('click')}>{status==='speaking'||status==='loading'?'Vorstellung stoppen':status==='unavailable'?'Erneut versuchen':'Neo anhören'}</button><button className="neo-reset" onClick={()=>{move(0,0);setMoved(false)}} disabled={!moved} aria-label="Neo zurücksetzen"><RotateCcw size={15}/></button><span className="voice-wave" aria-hidden="true">{Array.from({length:15},(_,i)=><i key={i} style={{animationDelay:`${i*.07}s`,height:`${6+i*11%22}px`}}/>)}</span></div><details className="neo-transcript"><summary>Vorstellung lesen</summary><p>{introduction}</p></details></div>
  </div>
}
