"use client";
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Compass,Globe2,Link2,Menu,Monitor,Mouse,Pause,Play,ShieldCheck,Smartphone,Users,X,ZoomIn,ZoomOut} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {AmbientField} from './ambient-field';
import {NeoCompanion} from './neo-companion';
import {ProductExplorer,type ProductCapture} from './product-explorer';
import {WorkflowExperience} from './workflow-experience';
import {SpatialJourney} from './spatial-journey';
import {captures} from './product-data';
import {VisionChapter,RoleChapters,ProcessChapters,DeviceChapter,AdoptionChapter,KnowledgeChapter} from './expanded-content';
import {links} from './site-links';
import AppStoreShowcase from './app-store-showcase';
const portals=[{name:'Verwaltung',icon:Monitor,href:'https://www.caresuiteplus.app/auth/business-login',text:'Planung & Organisation',code:'01'},{name:'Mitarbeitende',icon:Smartphone,href:'https://www.caresuiteplus.app/auth/employee-portal-login',text:'Einsätze & Dokumentation',code:'02'},{name:'Klient:innen',icon:Users,href:'https://www.caresuiteplus.app/auth/client-login',text:'Termine & Unterlagen',code:'03'}];
export default function Home(){
 const [paused,setPaused]=useState(false),[menu,setMenu]=useState(false),[lightbox,setLightbox]=useState<ProductCapture|null>(null),[zoom,setZoom]=useState(false),[scrolled,setScrolled]=useState(false),[chapter,setChapter]=useState('home');
 const root=useRef<HTMLDivElement>(null),hero=useRef<HTMLElement>(null),progress=useRef<HTMLDivElement>(null);
 useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');setPaused(query.matches);const change=()=>setPaused(query.matches);query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[]);
 useEffect(()=>{let raf=0,mouseFrame=0;let x=0,y=0;const read=()=>{raf=0;const y=scrollY,h=innerHeight;progress.current?.style.setProperty('transform',`scaleX(${y/Math.max(1,document.documentElement.scrollHeight-h)})`);hero.current?.style.setProperty('--hero-scroll',String(paused?0:Math.min(1,y/h)));setScrolled(y>60)};const schedule=()=>{if(!raf)raf=requestAnimationFrame(read)};read();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');reveal.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));const chapters=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setChapter(entry.target.id)}),{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main>section[id]').forEach(el=>chapters.observe(el));const pointer=(event:PointerEvent)=>{if(paused||event.pointerType==='touch')return;x=event.clientX;y=event.clientY;if(!mouseFrame)mouseFrame=requestAnimationFrame(()=>{mouseFrame=0;root.current?.style.setProperty('--pointer-x',`${x}px`);root.current?.style.setProperty('--pointer-y',`${y}px`);root.current?.style.setProperty('--look-x',`${(x/innerWidth-.5)*12}deg`);root.current?.style.setProperty('--look-y',`${(y/innerHeight-.5)*-8}deg`)});};window.addEventListener('pointermove',pointer,{passive:true});return()=>{cancelAnimationFrame(raf);cancelAnimationFrame(mouseFrame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);window.removeEventListener('pointermove',pointer);reveal.disconnect();chapters.disconnect()}},[paused]);
 const open=(image:ProductCapture)=>{setLightbox(image);setZoom(false)};
 const nextImage=(direction:number)=>{if(!lightbox)return;const i=captures.findIndex(c=>c.src===lightbox.src);setLightbox(captures[(i+direction+captures.length)%captures.length]);setZoom(false)};
 return <div className={'experience cinematic '+(paused?'motion-paused':'')} ref={root}><a className="skip-link" href="#produkt">Zum Produkt</a><AmbientField paused={paused}/><div className="ambient-ribbons" aria-hidden="true"><i/><i/><i/></div><div className="pointer-aura" aria-hidden="true"/><div className="reading-progress" ref={progress}/>
 <header className={scrolled?'site-header scrolled':'site-header'}><a href="#home" className="brand" aria-label="CareSuite HealthOS Startseite"><img src="/landingpage/media/brand.png" alt="CareSuite HealthOS" width="2048" height="256"/></a><nav aria-label="Hauptnavigation" className={menu?'main-nav open':'main-nav'}>{[['#dimension','HealthOS'],['#android-app','App'],['#produkt','Produktwelt'],['#details','Mehr erfahren']].map(([href,label])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="header-actions"><button className="round-control" aria-label={paused?'Animationen einschalten':'Animationen pausieren'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><a href={links.register} className="button small" target="_blank" rel="noopener noreferrer">Firma registrieren</a><button className="menu-toggle" aria-label={menu?'Menü schließen':'Menü öffnen'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <nav className="chapter-rail" aria-label="Kapitel">{[['home','Start'],['dimension','HealthOS'],['android-app','Android-App'],['produkt','Produktwelt'],['ablauf','Im Alltag'],['start','Registrieren']].map(([id,label],i)=><a href={'#'+id} key={id} aria-label={label} aria-current={chapter===id?'location':undefined}><span>{label}</span><i/><small>0{i+1}</small></a>)}</nav>
 <main>
 <section className="hero section-anchor" id="home" ref={hero}><img className="hero-environment" src="/landingpage/media/healthos-orbit.webp" alt="" width="1536" height="1024" fetchPriority="high"/><div className="hero-stars" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} style={{left:(i*37%100)+'%',top:(i*23%100)+'%',animationDelay:(i%7)+'s',animationDuration:(5+i%5)+'s'}}/>)}</div><div className="hero-grid" aria-hidden="true"/><div className="hero-type" aria-hidden="true">HealthOS</div><div className="hero-layout wrap"><div className="hero-copy"><div className="eyebrow"><span className="brand-cross">+</span> CARESUITE HEALTHOS</div><h1>Dein Alltag.<br/><em>Neue Dimension.</em></h1><p>Planen. Begleiten. Verbinden.<br/>Ein Betriebssystem für eure Versorgung.</p><div className="hero-actions"><a className="button register-button" href={links.register} target="_blank" rel="noopener noreferrer">Unternehmen kostenlos registrieren</a><a className="quiet-link" href="#dimension"><Compass size={17}/> HealthOS erleben</a><a className="quiet-link hero-app-link" href={links.playStore} target="_blank" rel="noopener noreferrer"><Smartphone size={17}/> Android-App herunterladen</a></div><div className="hero-meta"><span>WEB & ANDROID</span><i/><span>MADE IN GERMANY</span></div><div className="hero-socials"><a href={links.facebook} target="_blank" rel="noopener noreferrer"><Link2 size={17}/> Facebook</a><a href={links.instagram} target="_blank" rel="noopener noreferrer"><Link2 size={17}/> Instagram</a></div></div><div className="hero-neo-world"><div className="hero-screen-preview" aria-hidden="true"><img src="/landingpage/media/admin-desktop.jpg" alt="" width="1363" height="936"/></div><NeoCompanion/></div></div><div className="hero-bottom wrap"><a href="#dimension"><Mouse size={17}/><span>Die nächste Dimension entdecken</span></a><span>HUMAN FIRST. HEALTHOS.</span></div><div className="hero-fade"/></section>
 <SpatialJourney paused={paused} onOpen={open}/>
 <div className="kinetic-strip" aria-hidden="true"><div>{Array.from({length:4},(_,i)=><span key={i}>PLANEN <i>+</i> BEGLEITEN <i>+</i> VERBINDEN <i>+</i></span>)}</div></div>
 <AppStoreShowcase/>
 <ProductExplorer paused={paused} onOpen={open}/>
 <WorkflowExperience/>
 <section className="foundation wrap" id="vertrauen"><div className="foundation-head reveal"><span className="eyebrow">EINE KLARE BASIS.</span><h2>Fortschritt.<br/><em>Mit Vertrauen.</em></h2></div><div className="foundation-facts reveal"><div><Globe2/><strong>Made in Germany</strong><span>Entwickelt in Deutschland.</span></div><div><ShieldCheck/><strong>Hosting in Deutschland</strong><a href="https://www.caresuiteplus.app/datenschutz" target="_blank" rel="noopener noreferrer">Datenschutz ansehen</a></div><div><Monitor/><strong>Web & Android</strong><span>Im Büro. Im Einsatz. Im Portal.</span></div></div></section>
 <section className="start-section wrap section-anchor" id="start"><div className="start-heading reveal"><div><span className="price-label">KOSTENLOSE SOFTWARE.</span><h2>Dein Unternehmen.<br/><em>Dein HealthOS.</em></h2><a className="button register-button" href={links.register} target="_blank" rel="noopener noreferrer">Unternehmen jetzt registrieren</a></div><div className="price-mark" aria-label="0 Euro"><span>0</span><small>€</small><i>KOSTENLOS STARTEN.</i></div></div><div className="portal-intro"><span>Bereits dabei?</span><span>Direkt in euren Arbeitsbereich.</span></div><div className="portal-doors">{portals.map(p=><a className="portal-door" href={p.href} key={p.name} target="_blank" rel="noopener noreferrer"><div><span>{p.code}</span><p.icon size={27} strokeWidth={1.2}/></div><h3>{p.name}</h3><p>{p.text}</p><strong>Portal öffnen <Globe2 size={16}/></strong></a>)}</div><p className="access-note">Für bestehende Konten. Die Registrierung öffnet die offizielle CareSuite-Software.</p></section>
 <section id="details" className="detail-vault wrap"><div className="vault-heading"><BookOpen size={22}/><h2>Mehr wissen?</h2><p>Öffne, was dich interessiert.</p></div><details className="vault-item"><summary>Die HealthOS-Idee</summary><VisionChapter/></details><details className="vault-item"><summary>Arbeitsbereiche im Detail</summary><RoleChapters onOpen={open}/></details><details className="vault-item"><summary>Funktionen & Abläufe</summary><ProcessChapters onOpen={open}/></details><details className="vault-item"><summary>Web, Android & der Einstieg</summary><DeviceChapter/><AdoptionChapter/></details><details className="vault-item"><summary>Fragen & Antworten durchsuchen</summary><KnowledgeChapter/></details></section>
 </main><footer className="site-footer wrap"><div><a href="#home" className="brand"><img src="/landingpage/media/brand.png" alt="CareSuite HealthOS" width="2048" height="256"/></a><p>Human first. HealthOS.</p></div><div className="footer-links"><a href={links.playStore} target="_blank" rel="noopener noreferrer">Android-App bei Google Play</a><a href={links.register} target="_blank" rel="noopener noreferrer">Firmenregistrierung</a><a href="https://www.caresuiteplus.app/impressum" target="_blank" rel="noopener noreferrer">Kontakt & Impressum</a><a href="https://www.caresuiteplus.app/datenschutz" target="_blank" rel="noopener noreferrer">Datenschutz</a><a href="#home">Nach oben</a></div><div className="footer-socials"><a href={links.facebook} target="_blank" rel="noopener noreferrer"><Link2 size={21}/>Facebook</a><a href={links.instagram} target="_blank" rel="noopener noreferrer"><Link2 size={21}/>Instagram</a></div><div className="footer-line"><span>© 2026 CareSuite HealthOS</span><span>MADE IN GERMANY.</span></div></footer>
 <Dialog open={!!lightbox} onOpenChange={value=>{if(!value){setLightbox(null);setZoom(false)}}}><DialogContent className="product-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();nextImage(1)}if(e.key==='ArrowLeft'){e.preventDefault();nextImage(-1)}}}><DialogTitle>{lightbox?.title}</DialogTitle><DialogDescription>{lightbox?.role} · Originalaufnahme mit fiktiven Demo-Daten.</DialogDescription><div className={zoom?'lightbox-image is-zoomed':'lightbox-image'}>{lightbox&&<img src={lightbox.src} alt={lightbox.title}/>}</div><div className="lightbox-controls"><button onClick={()=>nextImage(-1)}>Vorheriges Bild</button><button aria-pressed={zoom} onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut size={17}/>:<ZoomIn size={17}/>} {zoom?'Einpassen':'100 %'}</button><button onClick={()=>nextImage(1)}>Nächstes Bild</button></div></DialogContent></Dialog>
 </div>
}
