"use client";
import {useEffect,useRef,useState} from 'react';
import {Compass,Globe2,Menu,Monitor,Mouse,Pause,Play,ShieldCheck,Smartphone,Users,X,ZoomIn,ZoomOut} from 'lucide-react';
import {Dialog,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Accordion,AccordionContent,AccordionItem,AccordionTrigger} from '@/components/ui/accordion';
import {AmbientField} from './ambient-field';
import {NeoCompanion} from './neo-companion';
import {ProductExplorer,type ProductCapture} from './product-explorer';
import {WorkflowExperience} from './workflow-experience';
import {captures} from './product-data';
import {ReadingGuide,VisionChapter,RoleChapters,ProcessChapters,DeviceChapter,AdoptionChapter,KnowledgeChapter} from './expanded-content';
const portals=[{name:'Verwaltung',icon:Monitor,href:'https://www.caresuiteplus.app/auth/business-login',text:'Planung, Personal und betriebliche Organisation',code:'01'},{name:'Mitarbeitende',icon:Smartphone,href:'https://www.caresuiteplus.app/auth/employee-portal-login',text:'Einsätze, Zeiten und der persönliche Arbeitstag',code:'02'},{name:'Klient:innen',icon:Users,href:'https://www.caresuiteplus.app/auth/client-login',text:'Termine, Unterlagen und der Kontakt zum Team',code:'03'}];
const questions=[['Wie kann ich CareSuite ausprobieren?','Wählt den Zugang, der zu eurer Rolle passt. Die Links öffnen die offizielle CareSuite-Software. Für die geschützten Bereiche benötigt ihr ein eigenes Konto oder bereitgestellte Demo-Zugangsdaten.'],['Kann ich auch unterwegs arbeiten?','CareSuite bietet Webzugänge und einen Android-Zugang. Welche Funktionen bereitstehen, richtet sich nach dem jeweiligen Arbeitsbereich und den zugewiesenen Rechten.'],['Was bedeutet kostenlos nutzbar?','Ihr könnt CareSuite HealthOS kostenlos nutzen und prüfen, wie die Software zu euren Abläufen passt. Maßgeblich sind die aktuellen Nutzungsbedingungen auf der offiziellen Produktseite.']];
export default function Home(){
 const [paused,setPaused]=useState(false),[menu,setMenu]=useState(false),[lightbox,setLightbox]=useState<ProductCapture|null>(null),[zoom,setZoom]=useState(false),[scrolled,setScrolled]=useState(false),[chapter,setChapter]=useState('home');
 const root=useRef<HTMLDivElement>(null),hero=useRef<HTMLElement>(null),progress=useRef<HTMLDivElement>(null);
 useEffect(()=>{const query=matchMedia('(prefers-reduced-motion: reduce)');setPaused(query.matches);const change=()=>setPaused(query.matches);query.addEventListener('change',change);return()=>query.removeEventListener('change',change)},[]);
 useEffect(()=>{let raf=0,mouseFrame=0;const read=()=>{raf=0;const y=scrollY,h=innerHeight;progress.current?.style.setProperty('transform',`scaleX(${y/Math.max(1,document.documentElement.scrollHeight-h)})`);hero.current?.style.setProperty('--hero-scroll',String(paused?0:Math.min(1,y/h)));setScrolled(y>60)};const schedule=()=>{if(!raf)raf=requestAnimationFrame(read)};read();window.addEventListener('scroll',schedule,{passive:true});window.addEventListener('resize',schedule);const reveal=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');reveal.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>reveal.observe(el));const chapters=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting)setChapter(entry.target.id)}),{rootMargin:'-15% 0px -65% 0px'});document.querySelectorAll('main>section[id]').forEach(el=>chapters.observe(el));const pointer=(event:PointerEvent)=>{if(paused||event.pointerType==='touch')return;const x=event.clientX,y=event.clientY;if(!mouseFrame)mouseFrame=requestAnimationFrame(()=>{mouseFrame=0;root.current?.style.setProperty('--pointer-x',`${x}px`);root.current?.style.setProperty('--pointer-y',`${y}px`)});};window.addEventListener('pointermove',pointer,{passive:true});return()=>{cancelAnimationFrame(raf);cancelAnimationFrame(mouseFrame);window.removeEventListener('scroll',schedule);window.removeEventListener('resize',schedule);window.removeEventListener('pointermove',pointer);reveal.disconnect();chapters.disconnect()}},[paused]);
 const open=(image:ProductCapture)=>{setLightbox(image);setZoom(false)};
 const nextImage=(direction:number)=>{if(!lightbox)return;const i=captures.findIndex(c=>c.src===lightbox.src);setLightbox(captures[(i+direction+captures.length)%captures.length]);setZoom(false)};
 return <div className={paused?'experience motion-paused':'experience'} ref={root}><a className="skip-link" href="#produkt">Zum Produkt</a><AmbientField paused={paused}/><div className="ambient-ribbons" aria-hidden="true"><i/><i/><i/></div><div className="pointer-aura" aria-hidden="true"/><div className="reading-progress" ref={progress}/>
 <header className={scrolled?'site-header scrolled':'site-header'}><a href="#home" className="brand" aria-label="CareSuite HealthOS Startseite"><img src="/landingpage/media/brand.png" alt="CareSuite HealthOS" width="2048" height="256"/></a><nav aria-label="Hauptnavigation" className={menu?'main-nav open':'main-nav'}>{[['#produkt','Produktwelt'],['#arbeitsbereiche','Arbeitsbereiche'],['#funktionen','Funktionen'],['#wissen','Wissenswertes']].map(([href,label])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="header-actions"><button className="round-control" aria-label={paused?'Animationen einschalten':'Animationen pausieren'} onClick={()=>setPaused(!paused)}>{paused?<Play size={14}/>:<Pause size={14}/>}</button><a href="#start" className="button small">HealthOS öffnen</a><button className="menu-toggle" aria-label={menu?'Menü schließen':'Menü öffnen'} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <nav className="chapter-rail" aria-label="Kapitel">{[['home','Start'],['vision','HealthOS-Idee'],['produkt','Produktwelt'],['arbeitsbereiche','Arbeitsbereiche'],['funktionen','Funktionen'],['einfuehrung','Einführung'],['wissen','Wissenswertes'],['start','Zugänge']].map(([id,label],i)=><a href={'#'+id} key={id} aria-label={label} aria-current={chapter===id?'location':undefined}><span>{label}</span><i/><small>0{i+1}</small></a>)}</nav>
 <main>
 <section className="hero section-anchor" id="home" ref={hero}><img className="hero-environment" src="/landingpage/media/healthos-orbit.webp" alt="" width="1536" height="1024" fetchPriority="high"/><div className="hero-stars" aria-hidden="true">{Array.from({length:28},(_,i)=><i key={i} style={{left:(i*37%100)+'%',top:(i*23%100)+'%',animationDelay:(i%7)+'s',animationDuration:(5+i%5)+'s'}}/>)}</div><div className="hero-grid" aria-hidden="true"/><div className="hero-type" aria-hidden="true">HealthOS</div><div className="hero-layout wrap"><div className="hero-copy"><div className="eyebrow"><span className="brand-cross">+</span> CARESUITE HEALTHOS</div><h1>Für Menschen.<br/>In einer neuen<br/><em>Dimension.</em></h1><p>Planung, Begleitung und Organisation.<br/>Ein digitaler Arbeitsplatz für alles, was gute Versorgung möglich macht.</p><div className="hero-actions"><a className="button" href="#produkt"><Compass size={18}/> Produktwelt entdecken</a><a className="quiet-link" href="#ablauf">Den Alltag weiterdenken</a></div><div className="hero-meta"><span>WEB & ANDROID</span><i/><span>KOSTENLOS NUTZBAR</span></div></div><NeoCompanion/></div><div className="hero-bottom wrap"><a href="#produkt"><Mouse size={17}/><span>Scrollen. Entdecken. Ausprobieren.</span></a><span>ENTWICKELT FÜR EURE VERSORGUNG</span></div><div className="hero-fade"/></section>
 <ReadingGuide active={chapter}/><VisionChapter/>
 <ProductExplorer paused={paused} onOpen={open}/>
 <RoleChapters onOpen={open}/>
 <div className="chapter-transition" aria-hidden="true"><div/><span>VON DER OBERFLÄCHE IN DEN ALLTAG</span><div/></div>
 <WorkflowExperience/>
 <ProcessChapters onOpen={open}/><DeviceChapter/>
 <section className="trust-section section-anchor" id="vertrauen"><div className="trust-beam" aria-hidden="true"/><div className="wrap"><div className="chapter-label reveal"><span>07</span> DIE BASIS FÜR EURE ARBEIT</div><div className="heading-row reveal"><h2>Fortschritt braucht<br/><em>ein gutes Fundament.</em></h2><p>Technologie berührt Menschen und ihre Informationen. Herkunft, Verarbeitung und passende Zugänge gehören deshalb zur Produktentscheidung.</p></div><div className="trust-grid">{[{icon:Globe2,num:'DE',title:'Made in Germany.',text:'CareSuite HealthOS ist Software aus Deutschland. Der Blick auf die Aufgaben ambulanter Alltagsbegleitung und Versorgung prägt die gemeinsame Arbeitsumgebung.',label:'ENTWICKLUNG'},{icon:ShieldCheck,num:'DE',title:'Hosting in Deutschland.',text:'Der Hostingstandort ist Teil der Vertrauensbasis. Die aktuellen Datenschutz- und Vertragsunterlagen beschreiben die konkreten Regelungen zur Datenverarbeitung.',label:'DATENVERARBEITUNG'},{icon:Users,num:'03',title:'Zugänge mit Verantwortung.',text:'Verwaltung, Mitarbeitende und Klient:innen haben unterschiedliche Aufgaben. Getrennte Zugänge und passende Rechte unterstützen die Zusammenarbeit.',label:'ROLLEN & BERECHTIGUNGEN'}].map(card=><article className="trust-card reveal" key={card.title} onPointerMove={e=>{if(paused||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--card-x',((e.clientX-r.left)/r.width*100)+'%');e.currentTarget.style.setProperty('--card-y',((e.clientY-r.top)/r.height*100)+'%')}}><div className="trust-card-top"><card.icon size={27} strokeWidth={1}/><span>{card.num}</span></div><span className="eyebrow">{card.label}</span><h3>{card.title}</h3><p>{card.text}</p></article>)}</div><a className="quiet-link trust-link" href="https://www.caresuiteplus.app/datenschutz" target="_blank" rel="noopener noreferrer">Datenschutzinformationen ansehen <ShieldCheck size={16}/></a></div></section>
 <AdoptionChapter/><KnowledgeChapter/>
 <section className="start-section wrap section-anchor" id="start"><div className="chapter-label reveal"><span>10</span> EUER NÄCHSTER SCHRITT</div><div className="start-heading reveal"><div><span className="price-label">KOSTENLOSE SOFTWARE</span><h2>Jetzt wird es<br/><em>euer HealthOS.</em></h2><p>Öffnet euren Arbeitsbereich und lernt die Software selbst kennen.</p></div><div className="price-mark" aria-label="0 Euro"><span>0</span><small>€</small><i>FÜR DEN EINSTIEG IN EURE PRODUKTWELT</i></div></div><div className="portal-doors">{portals.map(p=><a className="portal-door" href={p.href} key={p.name} target="_blank" rel="noopener noreferrer"><div><span>{p.code}</span><p.icon size={28} strokeWidth={1}/></div><h3>{p.name}</h3><p>{p.text}</p><strong>Portal öffnen <Globe2 size={16}/></strong></a>)}</div><p className="access-note">Die Zugänge öffnen die offizielle CareSuite-Software. Ein eigenes Konto oder bereitgestellter Demo-Zugang ist erforderlich.</p><div className="practical-questions"><h3>Vor dem Einstieg.</h3><Accordion type="single" collapsible>{questions.map(([q,a],i)=><AccordionItem value={'question-'+i} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent><p>{a}</p></AccordionContent></AccordionItem>)}</Accordion></div></section>
 </main><footer className="site-footer wrap"><div><a href="#home" className="brand"><img src="/landingpage/media/brand.png" alt="CareSuite HealthOS" width="2048" height="256"/></a><p>Für Menschen. Für einen besseren Arbeitsalltag.</p></div><div className="footer-links"><a href="https://www.caresuiteplus.app/impressum" target="_blank" rel="noopener noreferrer">Kontakt & Impressum</a><a href="https://www.caresuiteplus.app/datenschutz" target="_blank" rel="noopener noreferrer">Datenschutz</a><a href="https://www.caresuiteplus.app/" target="_blank" rel="noopener noreferrer">CareSuite-Webseite</a><a href="#home">Nach oben</a></div><div className="footer-line"><span>© 2026 CareSuite HealthOS</span><span>HUMAN FIRST. HEALTHOS.</span></div></footer>
 <Dialog open={!!lightbox} onOpenChange={value=>{if(!value){setLightbox(null);setZoom(false)}}}><DialogContent className="product-lightbox" onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();nextImage(1)}if(e.key==='ArrowLeft'){e.preventDefault();nextImage(-1)}}}><DialogTitle>{lightbox?.title}</DialogTitle><DialogDescription>{lightbox?.role} · Originalaufnahme mit fiktiven Demo-Daten.</DialogDescription><div className={zoom?'lightbox-image is-zoomed':'lightbox-image'}>{lightbox&&<img src={lightbox.src} alt={lightbox.title}/>}</div><div className="lightbox-controls"><button onClick={()=>nextImage(-1)}>Vorheriges Bild</button><button aria-pressed={zoom} onClick={()=>setZoom(!zoom)}>{zoom?<ZoomOut size={17}/>:<ZoomIn size={17}/>} {zoom?'Einpassen':'100 %'}</button><button onClick={()=>nextImage(1)}>Nächstes Bild</button></div></DialogContent></Dialog>
 </div>
}
