export const captures = [
  {src:'/landingpage/media/admin-desktop.jpg',title:'Dein HealthOS-Desktop',role:'Verwaltung',short:'Der Arbeitsplatz',detail:'Der gemeinsame Einstieg in den Arbeitstag: Apps, Widgets und zentrale Aufgaben finden auf dem persönlichen Desktop zusammen. Die Aufnahme zeigt die reale Arbeitsumgebung des Demo-Betriebs.',tags:['Zwölf aktive Widgets','Apps & Widgets','Seitensuche und Navigation']},
  {src:'/landingpage/media/admin-calendar.jpg',title:'Planung mit Perspektive',role:'Verwaltung',short:'Die Kalenderansicht',detail:'Der Kalender verbindet Zeiträume, Mitarbeitende und Einsatzplanung. Ansichten und Filter helfen dabei, den Ausschnitt zu wählen, der für die aktuelle Planungsaufgabe gebraucht wird.',tags:['Sechs Kalenderansichten','Mitarbeiterauswahl','Verfügbarkeiten & Abwesenheiten']},
  {src:'/landingpage/media/calendar-grid.jpg',title:'Der Monat im Zusammenhang',role:'Verwaltung',short:'Der Monatskalender',detail:'Ein ganzer Monat als gemeinsame Planungsfläche. Einsätze mit Zeitangaben, Urlaub, Weiterbildung und Geburtstage finden im Monatsraster zusammen. Hinweise auf weitere Einträge halten auch volle Tage zugänglich.',tags:['Einsätze mit Zeitangaben','Urlaub & Weiterbildung','Weitere Einträge je Tag']},
  {src:'/landingpage/media/employee-desktop.jpg',title:'Der eigene Tag im Fokus',role:'Mitarbeitende',short:'Der Einsatzalltag',detail:'Die persönliche Begrüßung führt direkt in den Arbeitstag. Eigene Einsätze, geplante Stunden und offene Dokumentation sind in der Tagesübersicht sichtbar. Schnellzugriffe verbinden Nachrichten, Arbeitszeit und Dokumente.',tags:['Direkt zum aktuellen Einsatz','Geplante Stunden im Blick','Offene Dokumentation']},
  {src:'/landingpage/media/client-desktop.jpg',title:'Eine eigene Verbindung',role:'Klient:innen',short:'Das Klientenportal',detail:'Der nächste Einsatz erscheint mit Datum, Uhrzeit und Leistung. Klient:innen können ihn ansehen oder eine Änderung mitteilen. Schnellzugriffe führen zu Nachrichten, Dokumentupload, Einsatzanfrage und Rückrufanforderung.',tags:['Nächster Einsatz im Überblick','Änderung mitteilen','Nachricht & Rückruf anfordern']},
  {src:'/landingpage/media/client-appointments.jpg',title:'Die nächsten Termine',role:'Klient:innen',short:'Die Terminübersicht',detail:'Kommende und vergangene Einsätze haben eigene Register. Die Einsatzkarte zeigt Status, Zeitraum, geplante Dauer, Mitarbeitende und Leistung. Über die Vorschau lässt sich der jeweilige Einsatz weiter ansehen.',tags:['Kommende & vergangene Einsätze','Zeitraum, Dauer und Leistung','Vorschau zum Einsatz']},
  {src:'/landingpage/media/client-budget.jpg',title:'Budget, das verständlich bleibt',role:'Klient:innen',short:'Budget & Stunden',detail:'Gebuchte Leistungen und zusätzliche Möglichkeiten sind getrennt dargestellt. Die echte Budgetansicht verbindet verfügbare Beträge mit möglichen Stunden und zeigt verbrauchte sowie für Einsätze geplante Anteile.',tags:['Gebuchte Leistungen','Beträge und mögliche Stunden','Verbrauch und Planung']},
  {src:'/landingpage/media/client-documents.jpg',title:'Die eigenen Unterlagen. An einem Ort.',role:'Klient:innen',short:'Dokumentenübersicht',detail:'Die Übersicht zeigt Dokumentarten, Freigaben und pflegerelevante Unterlagen. Vereinbarungen und Unterstützungspläne sind direkt erreichbar. Benötigte Unterschriften führen in einen eigenen Bereich.',tags:['Dokumentarten und Freigaben','Vereinbarungen und Pflegepläne','Eigener Unterschriftenbereich']},
  {src:'/landingpage/media/client-plan.jpg',title:'Der Unterstützungsplan im Portal',role:'Klient:innen',short:'Unterstützungsplan',detail:'Freigegebene Dokumente lassen sich direkt im Portal lesen. Der gezeigte fiktive Unterstützungsplan verbindet Ziele, Schwerpunkte und persönliche Wünsche mit dem Dokumentstatus und dem Aktualisierungsdatum.',tags:['Im Portal lesbarer Inhalt','Ziele und persönliche Wünsche','Status und Aktualisierung']},
  {src:'/landingpage/media/client-signatures.jpg',title:'Freigaben mit einem klaren Platz',role:'Klient:innen',short:'Unterschriften',detail:'Offene und erledigte Dokumente haben getrennte Register. Hinweise erklären das Lesen und Unterschreiben mit Finger, Stift oder Maus. Die Aufnahme zeigt den Zustand ohne bereits erledigte Dokumente.',tags:['Offen und erledigt','Hinweise zur Unterschrift','Übersichtlicher Leerzustand']},
  {src:'/landingpage/media/client-proofs.jpg',title:'Leistungen nachvollziehen',role:'Klient:innen',short:'Leistungsnachweise',detail:'Freigegebene Nachweise erscheinen mit Leistungsbezeichnung, Monat und Unterschriftsstatus. Jede Zeile bietet den Einstieg in die zugehörige PDF-Ansicht. So bleiben zurückliegende Leistungen wieder auffindbar.',tags:['Leistung und Zeitraum','Unterschriftsstatus','PDF-Ansicht je Nachweis']},
  {src:'/landingpage/media/client-messages.jpg',title:'Abstimmung, die zusammenbleibt',role:'Klient:innen',short:'Nachrichten & Chat',detail:'Die Nachrichtenansicht ordnet Gespräche nach Themen. Ein ausgewählter Chat zeigt Status und Verlauf; die Oberfläche bietet Eingabe, Anhänge und Sprachnachrichten. Das Beispiel zeigt eine fiktive Terminabstimmung.',tags:['Gesprächsliste und Suche','Status und Chatverlauf','Anhänge und Sprachnachrichten']},
];
