"use client";
import {useEffect,useRef,useState} from 'react';
import {Expand,Grid2X2,Layers3,Pause,Play,Square} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {captures} from './product-data';
export type ProductCapture=(typeof captures)[number];
const roleCopy:Record<string,string>={Alle:'Wählt einen Bereich und entdeckt, wie HealthOS im Alltag aussieht.',Verwaltung:'Der betriebliche Arbeitsplatz für Planung, Organisation und die gemeinsame Übersicht.',Mitarbeitende:'Der persönliche Einstieg in Einsätze, Arbeitszeiten und Dokumentation.', 'Klient:innen':'Ein eigener Zugang zu Terminen, Unterlagen, Nachrichten und persönlichen Informationen.'};
export function ProductExplorer({paused,onOpen}:{paused:boolean;onOpen:(image:ProductCapture)=>void}){
 const [role,setRole]=useState('Alle'),[selected,setSelected]=useState(0),[grid,setGrid]=useState(false),[playing,setPlaying]=useState(false),[spatial,setSpatial]=useState(true),[visible,setVisible]=useState(false);
 const root=useRef<HTMLElement>(null),scene=useRef<HTMLDivElement>(null),track=useRef<HTMLDivElement>(null),frame=useRef<HTMLButtonElement>(null);
 const filtered=captures.map((capture,index)=>({...capture,index})).filter(c=>role==='Alle'||c.role===role);
 const current=captures[selected];
 const choose=(index:number)=>{setSelected(index);setPlaying(false)};
 const advance=(direction:number)=>{const index=filtered.findIndex(c=>c.index===selected);setSelected(filtered[(index+direction+filtered.length)%filtered.length].index)};
 useEffect(()=>{const element=root.current;if(!element)return;const io=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.08});io.observe(element);return()=>io.disconnect()},[]);
 useEffect(()=>{if(!playing||paused||!visible||grid)return;const id=setInterval(()=>{if(!document.hidden)setSelected(previous=>{const list=captures.map((c,i)=>({...c,index:i})).filter(c=>role==='Alle'||c.role===role);return list[(list.findIndex(c=>c.index===previous)+1)%list.length].index})},7000);return()=>clearInterval(id)},[playing,paused,visible,grid,role]);
 useEffect(()=>{const node=track.current?.querySelector<HTMLElement>('[aria-pressed="true"]');if(node&&track.current){const scroll=node.offsetLeft-track.current.offsetLeft-track.current.clientWidth/2+node.clientWidth/2;track.current.scrollTo({left:scroll,behavior:paused?'instant':'smooth'})}},[selected,role,paused]);
 useEffect(()=>{let raf=0,value=0,target=0,last=0;const read=()=>{if(!root.current)return;const rect=root.current.getBoundingClientRect();target=paused?1:Math.max(0,Math.min(1,(innerHeight-rect.top)/(innerHeight*.85)))};const tick=(now:number)=>{const dt=Math.min((now-last)/1000,.07);last=now;value+=(target-value)*(1-Math.exp(-dt*7));scene.current?.style.setProperty('--arrival',String(paused?1:value));if(Math.abs(value-target)>.0005)raf=requestAnimationFrame(tick);else raf=0};const update=()=>{read();if(!raf)raf=requestAnimationFrame(tick)};update();window.addEventListener('scroll',update,{passive:true});window.addEventListener('resize',update);return()=>{cancelAnimationFrame(raf);window.removeEventListener('scroll',update);window.removeEventListener('resize',update)}},[paused]);
 return <section className="product-universe section-anchor" id="produkt" ref={root}>
   <div className="universe-heading wrap reveal"><div className="chapter-label"><span>02</span> DIE PRODUKTWELT</div><div className="heading-row"><h2>Dein System.<br/><em>Zum Anfassen.</em></h2><p>{captures.length} echte Ansichten. Deine Perspektive.</p></div></div>
   <div className="explorer-shell wrap" ref={scene}>
     <div className="explorer-light" aria-hidden="true"/><div className="explorer-topline"><span><Layers3 size={16}/> HEALTHOS EXPLORER</span><span>{String(captures.length).padStart(2,'0')} ORIGINALANSICHTEN</span></div>
     <div className="explorer-filters"><Tabs value={role} onValueChange={v=>{setRole(v);setSelected(captures.findIndex(c=>v==='Alle'||c.role===v));setPlaying(false)}}><TabsList className="role-tabs">{['Alle','Verwaltung','Mitarbeitende','Klient:innen'].map(r=><TabsTrigger value={r} key={r}>{r}<span>{captures.filter(c=>r==='Alle'||c.role===r).length}</span></TabsTrigger>)}</TabsList></Tabs><button className={grid?'explorer-control active':'explorer-control'} aria-pressed={grid} onClick={()=>{setGrid(!grid);setPlaying(false)}}><Grid2X2 size={17}/>{grid?'Einzelansicht':'Alle Bilder'}</button></div>
     <div className="role-context"><p>{roleCopy[role]}</p><span>WEB · DEMO-MANDANT</span></div>
     {grid?<div className="capture-grid">{filtered.map(c=><button className="capture-tile" key={c.src} onClick={()=>{choose(c.index);setGrid(false)}}><div><img src={c.src} alt={c.title} loading="lazy" width="1363" height="936"/><span><Expand size={18}/> Entdecken</span></div><small>{c.role}</small><strong>{c.short}</strong></button>)}</div>:<>
       <div className="explorer-stage" data-spatial={spatial&&!paused}>
         <div className="stage-orbit orbit-a" aria-hidden="true"/><div className="stage-orbit orbit-b" aria-hidden="true"/>
         <div className="screen-spine spine-left" aria-hidden="true"/><div className="screen-spine spine-right" aria-hidden="true"/>
         <button className="primary-screen" ref={frame} onClick={()=>{setPlaying(false);onOpen(current)}} onPointerMove={e=>{if(paused||!spatial||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',`${(e.clientY-r.top-r.height/2)/r.height*-4}deg`);e.currentTarget.style.setProperty('--tilt-y',`${(e.clientX-r.left-r.width/2)/r.width*5}deg`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg')}} aria-label={current.title+' in Großansicht öffnen'}><div className="screen-top"><span><i/><i/><i/></span><strong>CareSuite HealthOS</strong><small>{current.role}</small></div><div className="screen-image"><img key={current.src} src={current.src} alt={current.title+' – tatsächliche CareSuite-Oberfläche'} loading="lazy" width="1363" height="936"/><div className="screen-shine"/></div><span className="screen-expand"><Expand size={15}/> Großansicht</span></button>
         <div className="stage-floor" aria-hidden="true"/><div className="stage-caption"><span>{String(selected+1).padStart(2,'0')} / {String(captures.length).padStart(2,'0')}</span><span>{current.short}</span></div>
       </div>
       <div className="explorer-toolbar"><div><button className="explorer-control" onClick={()=>{advance(-1);setPlaying(false)}}>Vorherige</button><span className="toolbar-counter">{filtered.findIndex(c=>c.index===selected)+1} / {filtered.length}</span><button className="explorer-control" onClick={()=>{advance(1);setPlaying(false)}}>Nächste</button></div><div><button className="explorer-control" disabled={paused} aria-pressed={playing&&!paused} onClick={()=>setPlaying(!playing)}>{playing&&!paused?<Pause size={15}/>:<Play size={15}/>} {playing&&!paused?'Pause':'Abspielen'}</button><button className={spatial?'explorer-control active':'explorer-control'} aria-pressed={spatial} onClick={()=>setSpatial(!spatial)}>{spatial?<Layers3 size={15}/>:<Square size={15}/>} {spatial?'Räumlich':'Frontal'}</button></div></div>
       <details className="capture-details" key={current.src}><summary>{current.title} <span>Details ansehen</span></summary><div className="explorer-detail"><div><span className="eyebrow">{current.role}</span><h3>{current.title}</h3></div><p>{current.detail}</p><ul>{current.tags.map(tag=><li key={tag}>{tag}</li>)}</ul></div></details>
       <div className="filmstrip" ref={track} aria-label="Produktbild auswählen">{filtered.map(c=><button aria-pressed={selected===c.index} key={c.src} onClick={()=>choose(c.index)}><div><img src={c.src} alt="" loading="lazy" width="1363" height="936"/>{playing&&!paused&&visible&&selected===c.index&&<span className="film-progress" key={selected}/>}</div><span><small>{String(c.index+1).padStart(2,'0')}</small>{c.short}</span></button>)}</div>
     </>}
     <div className="explorer-footnote"><span>Alle Produktbilder stammen aus der tatsächlichen Software.</span><span>Personen und Vorgänge gehören zur Demo.</span></div>
   </div>
 </section>
}
