-- =============================================================================
-- CareSuite+ — Live-Pilot Seed (generated by scripts/seed-live-pilot.mjs)
-- Tenant: 11111111-1111-1111-1111-111111111101
-- Safe INSERT only — ON CONFLICT DO NOTHING. No DROP/TRUNCATE/DELETE.
-- Run manually in Supabase SQL Editor or: node scripts/seed-live-pilot.mjs --apply
-- =============================================================================

-- trips (Assist Fahrtenbuch — Migrations 0021/0022)
INSERT INTO public.trips (
  id, tenant_id, title, status, distance_km,
  employee_name, vehicle_label, purpose, started_at, ended_at,
  start_address, end_address, notes,
  created_at, updated_at
) VALUES
  (
    'c1000000-0000-4000-8000-000000000001',
    '11111111-1111-1111-1111-111111111101',
    'Büro Mitte → Musterstraße 12',
    'abgeschlossen',
    8.40,
    'Thomas Keller',
    'VW Caddy · K-CS 1001',
    'einsatz',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour 10 minutes',
    'Büro Mitte, Köln',
    'Musterstraße 12, Köln',
    'Anfahrt Einsatz Alltagsbegleitung',
    NOW() - INTERVAL '2 hours',
    NOW() - INTERVAL '1 hour 10 minutes'
  ),
  (
    'c1000000-0000-4000-8000-000000000002',
    '11111111-1111-1111-1111-111111111101',
    'Depot Ehrenfeld → Pflegevisit (läuft)',
    'in_bearbeitung',
    NULL,
    'Anna Krüger',
    'E-Bike · Flotte 3',
    'einsatz',
    NOW() - INTERVAL '45 minutes',
    NULL,
    'Depot Ehrenfeld, Köln',
    NULL,
    'Unterwegs zur Pflegevisit',
    NOW() - INTERVAL '45 minutes',
    NOW() - INTERVAL '5 minutes'
  ),
  (
    'c1000000-0000-4000-8000-000000000003',
    '11111111-1111-1111-1111-111111111101',
    'Lager Süd → Büro Mitte',
    'abgeschlossen',
    12.10,
    'Maria Schmidt',
    'VW Caddy · K-CS 1003',
    'material',
    NOW() - INTERVAL '5 hours',
    NOW() - INTERVAL '4 hours 30 minutes',
    'Lager Süd, Köln',
    'Büro Mitte, Köln',
    NULL,
    NOW() - INTERVAL '5 hours',
    NOW() - INTERVAL '4 hours 30 minutes'
  )
ON CONFLICT (id) DO NOTHING;

-- care_records (Stationär Bewohner:innen — Migrations 0023/0024)
INSERT INTO public.care_records (
  id, tenant_id, title, status,
  record_type, first_name, last_name, wing, admission_date, care_level, room_name,
  room_id, notes,
  created_at, updated_at
) VALUES
  (
    'c2000000-0000-4000-8000-000000000001',
    '11111111-1111-1111-1111-111111111101',
    'Gertrud Meier — Wohnbereich A',
    'aktiv',
    'resident',
    'Gertrud',
    'Meier',
    'Wohnbereich A',
    NOW() - INTERVAL '180 days',
    'PG 3',
    'A-101',
    'room-a101',
    'Mobilität eingeschränkt, Rollator',
    NOW() - INTERVAL '180 days',
    NOW() - INTERVAL '1 day'
  ),
  (
    'c2000000-0000-4000-8000-000000000002',
    '11111111-1111-1111-1111-111111111101',
    'Heinrich Bauer — Wohnbereich B',
    'aktiv',
    'resident',
    'Heinrich',
    'Bauer',
    'Wohnbereich B',
    NOW() - INTERVAL '90 days',
    'PG 2',
    'B-204',
    'room-b204',
    'Diabetes, regelmäßige BZ-Kontrolle',
    NOW() - INTERVAL '90 days',
    NOW() - INTERVAL '2 days'
  )
ON CONFLICT (id) DO NOTHING;

-- catalogs (Akademie Kurse — Migrations 0025/0026)
INSERT INTO public.catalogs (
  id, tenant_id, title, catalog_type, status,
  category, duration_minutes, is_mandatory, starts_at, enrollment_count,
  description, ends_at, instructor_name, completion_rate_percent,
  created_at, updated_at
) VALUES
  (
    'c3000000-0000-4000-8000-000000000001',
    '11111111-1111-1111-1111-111111111101',
    'Hygiene und Infektionsschutz',
    'course',
    'aktiv',
    'Pflichtschulung',
    90,
    TRUE,
    NOW() + INTERVAL '7 days',
    18,
    'Jährliche Pflichtfortbildung gemäß IfSG.',
    NOW() + INTERVAL '7 days' + INTERVAL '90 minutes',
    'Dr. Sandra Vogt',
    72,
    NOW() - INTERVAL '14 days',
    NOW() - INTERVAL '1 day'
  ),
  (
    'c3000000-0000-4000-8000-000000000002',
    '11111111-1111-1111-1111-111111111101',
    'Demenz: Kommunikation im Alltag',
    'course',
    'in_bearbeitung',
    'Fachfortbildung',
    120,
    FALSE,
    NOW() + INTERVAL '14 days',
    9,
    'Praxisnahe Kommunikationsstrategien bei Demenz.',
    NOW() + INTERVAL '14 days' + INTERVAL '2 hours',
    'PDL Schmidt',
    45,
    NOW() - INTERVAL '7 days',
    NOW()
  )
ON CONFLICT (id) DO NOTHING;

-- reporting_reports (Business Reporting — Migrations 0027/0028)
INSERT INTO public.reporting_reports (
  id, tenant_id, title, category, period, status,
  summary, kpi_snapshot,
  created_at, updated_at
) VALUES
  (
    'c4000000-0000-4000-8000-000000000001',
    '11111111-1111-1111-1111-111111111101',
    'PDL-Wochenbericht KW 24',
    'pdl',
    'KW 24 / 2026',
    'aktiv',
    'Ambulanter Pflegedienst — Wochenübersicht Einsätze, Personal und Qualität.',
    '[{"label":"Einsätze","value":"156"},{"label":"Auslastung","value":"87%"},{"label":"Offene Maßnahmen","value":"3"}]'::jsonb,
    NOW() - INTERVAL '3 days',
    NOW() - INTERVAL '1 day'
  ),
  (
    'c4000000-0000-4000-8000-000000000002',
    '11111111-1111-1111-1111-111111111101',
    'Qualitätsbericht Q2',
    'quality',
    'Q2 2026',
    'entwurf',
    'Quartalsbericht QM — MDK-Vorbereitung und Maßnahmenplan.',
    '[{"label":"Audits","value":"2"},{"label":"Maßnahmen offen","value":"5"}]'::jsonb,
    NOW() - INTERVAL '1 day',
    NOW()
  )
ON CONFLICT (id) DO NOTHING;
