#!/usr/bin/env node
/**
 * CareSuite+ Smoke-Check (WP 019)
 * Prüft Kern-Dateien und führt TypeScript-Check aus.
 */
import { existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const REQUIRED_FILES = [
  'package.json',
  'tsconfig.json',
  'app/_layout.tsx',
  'app/office/(tabs)/index.tsx',
  'app/office/(tabs)/clients.tsx',
  'app/office/(tabs)/employees.tsx',
  'app/office/(tabs)/appointments.tsx',
  'app/office/(tabs)/invoices.tsx',
  'app/office/employees/[id]/index.tsx',
  'app/office/invoices/[id]/index.tsx',
  'app/office/clients/create.tsx',
  'app/office/clients/[id]/index.tsx',
  'app/office/clients/[id]/edit.tsx',
  'app/business/(tabs)/index.tsx',
  'app/business/(tabs)/modules.tsx',
  'app/business/(tabs)/subscription.tsx',
  'app/business/(tabs)/platform.tsx',
  'app/business/(tabs)/integrations.tsx',
  'app/business/reporting/index.tsx',
  'app/business/reporting/list.tsx',
  'app/business/reporting/create.tsx',
  'app/business/reporting/[id]/index.tsx',
  'src/types/reporting/index.ts',
  'src/data/demo/reportingDemo.ts',
  'src/lib/reporting/reportingService.ts',
  'src/lib/reporting/index.ts',
  'src/hooks/usePdlCockpit.ts',
  'src/hooks/useReportList.ts',
  'src/hooks/useReportDetail.ts',
  'src/screens/reporting/PdlCockpitScreen.tsx',
  'src/screens/reporting/ReportListScreen.tsx',
  'src/screens/reporting/ReportDetailScreen.tsx',
  'src/screens/reporting/ReportCreateScreen.tsx',
  'docs/architecture/501-520-reporting.md',
  'app/business/reporting/portal-preview.tsx',
  'src/lib/documents/reportingDocumentService.ts',
  'src/screens/reporting/ReportingComposeMessageScreen.tsx',
  'docs/architecture/wp-509-reporting-permissions.md',
  'app/business/(tabs)/ops.tsx',
  'app/business/ops/index.tsx',
  'app/business/release/index.tsx',
  'app/business/release/list.tsx',
  'app/business/release/create.tsx',
  'app/business/release/[id]/index.tsx',
  'app/business/security/index.tsx',
  'app/business/security/list.tsx',
  'app/business/security/data-requests.tsx',
  'app/business/qa/index.tsx',
  'app/business/qa/list.tsx',
  'app/business/roadmap/index.tsx',
  'app/business/roadmap/list.tsx',
  'src/types/release/index.ts',
  'src/types/security/index.ts',
  'src/types/qa/index.ts',
  'src/types/roadmap/index.ts',
  'src/lib/release/releaseService.ts',
  'src/lib/security/securityService.ts',
  'src/lib/qa/qaService.ts',
  'src/lib/roadmap/roadmapService.ts',
  'src/screens/release/ReleaseHubScreen.tsx',
  'src/screens/security/SecurityHubScreen.tsx',
  'src/screens/security/DataSubjectRequestsAdminScreen.tsx',
  'src/lib/privacy/dataSubjectRequestAdminService.ts',
  'src/components/privacy/DataSubjectRequestsAdminListView.tsx',
  'src/components/portal/PortalDashboardHero.tsx',
  'src/components/portal/PortalTabHero.tsx',
  'src/components/templates/TemplateCenterHero.tsx',
  'src/screens/qa/QaHubScreen.tsx',
  'src/screens/roadmap/RoadmapHubScreen.tsx',
  'src/screens/ops/OpsHubScreen.tsx',
  'docs/architecture/wp-521-release.md',
  'docs/architecture/wp-540-release-abschluss.md',
  'docs/architecture/wp-541-security.md',
  'docs/architecture/wp-560-security-abschluss.md',
  'docs/architecture/wp-561-qa.md',
  'docs/architecture/wp-580-qa-abschluss.md',
  'docs/architecture/wp-581-roadmap.md',
  'docs/architecture/wp-600-roadmap-abschluss.md',
  'scripts/wp501-600-catalog.generated.mjs',
  'scripts/wp-600-audit.mjs',
  'app/business/platform/ocr/index.tsx',
  'app/business/platform/ocr/[id]/index.tsx',
  'app/business/platform/ai/index.tsx',
  'app/business/integrations/[id]/index.tsx',
  'app/business/integrations/outbox/index.tsx',
  'app/office/catalogs/index.tsx',
  'app/office/catalogs/[id]/index.tsx',
  'app/office/employees/[id]/edit.tsx',
  'app/office/(tabs)/_layout.tsx',
  'app/portal/employee/(tabs)/index.tsx',
  'app/portal/employee/(tabs)/assignments.tsx',
  'app/portal/employee/(tabs)/profile.tsx',
  'app/portal/employee/assignments/[id]/index.tsx',
  'app/portal/employee/messages/[id]/index.tsx',
  'app/portal/employee/documents/[id]/index.tsx',
  'app/assist/(tabs)/nachweise.tsx',
  'app/assist/(tabs)/fahrten.tsx',
  'app/assist/nachweise/[id]/index.tsx',
  'app/assist/fahrten/[id]/index.tsx',
  'app/portal/client/(tabs)/index.tsx',
  'app/portal/client/(tabs)/appointments.tsx',
  'app/portal/client/(tabs)/profile.tsx',
  'app/portal/client/appointments/[id]/index.tsx',
  'app/portal/client/messages/[id]/index.tsx',
  'app/portal/client/documents/[id]/index.tsx',
  'app/assist/(tabs)/index.tsx',
  'app/assist/(tabs)/assignments.tsx',
  'app/assist/assignments/[id]/index.tsx',
  'app/+not-found.tsx',
  'src/lib/navigation/shellConfig.ts',
  'src/components/layout/AppTabBar.tsx',
  'src/components/layout/ShellLayout.tsx',
  'src/hooks/useAppShell.ts',
  'docs/architecture/062-080-app-shell.md',
  'app/design-system/index.tsx',
  'src/theme/index.ts',
  'src/theme/accessibility.ts',
  'src/hooks/useAccessibility.ts',
  'src/hooks/useEmployeeList.ts',
  'src/hooks/useEmployeeDetail.ts',
  'src/hooks/useInvoiceDetail.ts',
  'src/hooks/useAppointmentList.ts',
  'src/hooks/useClientEditWizard.ts',
  'src/components/ui/PremiumButton.tsx',
  'src/components/layout/ScreenShell.tsx',
  'src/lib/services/index.ts',
  'src/lib/auth/context.ts',
  'src/lib/navigation/breadcrumbs.ts',
  'src/lib/navigation/routes.ts',
  'src/lib/office/employeeListService.ts',
  'src/lib/office/employeeDetailService.ts',
  'src/lib/office/invoiceDetailService.ts',
  'src/lib/office/appointmentListService.ts',
  'src/screens/office/EmployeesListScreen.tsx',
  'src/screens/office/EmployeeDetailScreen.tsx',
  'src/screens/office/InvoiceDetailScreen.tsx',
  'src/screens/office/AppointmentsListScreen.tsx',
  'src/screens/office/ClientEditScreen.tsx',
  'src/screens/portal/PortalViewScreen.tsx',
  'src/screens/portal/PortalAssignmentDetailScreen.tsx',
  'src/screens/portal/EmployeeProfileScreen.tsx',
  'src/lib/portal/employeeProfileService.ts',
  'src/hooks/usePortalAppointmentDetail.ts',
  'src/hooks/useEmployeePortalProfile.ts',
  'src/hooks/useClientPortalProfile.ts',
  'src/hooks/usePortalClientAppointmentDetail.ts',
  'src/screens/portal/ClientPortalProfileScreen.tsx',
  'src/lib/portal/clientProfileService.ts',
  'src/lib/catalog/catalogService.ts',
  'src/lib/business/subscriptionService.ts',
  'src/lib/platform/ocrJobService.ts',
  'src/lib/integrations/integrationService.ts',
  'src/screens/catalog/CatalogsListScreen.tsx',
  'src/screens/business/SubscriptionScreen.tsx',
  'src/screens/platform/PlatformHubScreen.tsx',
  'src/screens/integrations/IntegrationsListScreen.tsx',
  'src/screens/office/EmployeeEditScreen.tsx',
  'docs/architecture/441-460-kataloge.md',
  'docs/architecture/461-480-ai-ocr.md',
  'docs/architecture/481-500-integrationen.md',
  'docs/architecture/001-fundament.md',
  'docs/architecture/018-accessibility.md',
  'docs/architecture/019-testing.md',
  'docs/architecture/020-fundament-abschluss.md',
  'scripts/wp-m-catalog.mjs',
  'scripts/wp-substance.mjs',
  'scripts/generate-full-wp-catalog.mjs',
  'docs/architecture/wp-121-business.md',
  'src/lib/office/appointmentCreateService.ts',
  'src/lib/office/invoiceCreateService.ts',
  'src/lib/platform/platformHubService.ts',
  'src/lib/integrations/integrationHubService.ts',
  'src/__tests__/e2e/serviceFlows.test.ts',
  'supabase/migrations/0006_appointments_invoices.sql',
  'supabase/migrations/0007_assist_platform.sql',
  'src/lib/services/repositories/createTenantTableRepository.ts',
  'src/lib/services/repositories/authRlsPolicy.ts',
  'src/lib/communication/domainMessageService.ts',
  'src/hooks/useDomainComposeMessage.ts',
  'src/screens/shared/MessageComposeScreenShell.tsx',
  'src/lib/permissions/testMatrix.ts',
  'src/lib/auth/context.tsx',
  'app/business/ti/index.tsx',
  'app/business/ti/kim/index.tsx',
  'app/business/ti/kim/[id].tsx',
  'app/business/ti/providers/index.tsx',
  'app/business/ti/audit/index.tsx',
  'app/business/ti/consent/index.tsx',
  'app/business/ti/egk/index.tsx',
  'app/business/ti/epa/index.tsx',
  'app/business/ti/emp/index.tsx',
  'app/business/ti/erezept/index.tsx',
  'app/business/ti/documents/index.tsx',
  'src/types/modules/ti/index.ts',
  'src/data/demo/ti/index.ts',
  'src/data/demo/ti/kimQuery.ts',
  'src/lib/ti/index.ts',
  'src/lib/ti/tiAuditService.ts',
  'src/lib/ti/tiConsentService.ts',
  'src/lib/ti/tiPermissionService.ts',
  'src/lib/ti/tiProviderService.ts',
  'src/lib/ti/kimMailboxService.ts',
  'src/lib/ti/kimMessageService.ts',
  'src/lib/ti/kimAttachmentService.ts',
  'src/lib/ti/adapters/MockKIMProvider.ts',
  'src/hooks/ti/index.ts',
  'src/hooks/ti/useTIDashboard.ts',
  'src/hooks/ti/useKIMMailbox.ts',
  'src/hooks/ti/useKIMMessageDetail.ts',
  'src/hooks/ti/useTIProviders.ts',
  'src/hooks/ti/useTIAuditLog.ts',
  'src/hooks/ti/useTIConsents.ts',
  'src/components/ti/index.ts',
  'src/screens/ti/index.ts',
  'src/screens/ti/TIDashboardScreen.tsx',
  'src/screens/ti/KIMMailboxScreen.tsx',
  'src/screens/ti/KIMMessageDetailScreen.tsx',
  'src/screens/ti/TIProviderSettingsScreen.tsx',
  'src/screens/ti/TIAuditLogScreen.tsx',
  'src/screens/ti/TIConsentManagementScreen.tsx',
  'src/features/ti/index.ts',
  'docs/architecture/ti-module.md',
  'supabase/migrations/0009_ti_module.sql',
  'supabase/functions/ti-provider-proxy/index.ts',
  'src/__tests__/ti/tiConsent.test.ts',
  'src/__tests__/ti/tiAudit.test.ts',
  'src/__tests__/ti/kimMailbox.test.ts',
  'src/__tests__/ti/tiPermissions.test.ts',
  'src/lib/clients/index.ts',
  'src/lib/clients/clientFullDetailService.ts',
  'src/types/modules/client/index.ts',
  'src/hooks/useClientFullDetail.ts',
  'src/data/demo/clients/index.ts',
  'docs/architecture/client-data-model.md',
  'supabase/migrations/0010_client_extended.sql',
  'src/__tests__/office/clientFullDetail.test.ts',
  'app/business/messages/index.tsx',
  'app/business/messages/[threadId].tsx',
  'app/business/messages/new.tsx',
  'app/business/messages/archived.tsx',
  'app/business/messages/assignments.tsx',
  'app/business/messages/settings.tsx',
  'app/portal/employee/messages/index.tsx',
  'app/portal/employee/messages/[threadId].tsx',
  'app/portal/client/messages/index.tsx',
  'app/portal/client/messages/[threadId].tsx',
  'app/portal/relative/messages/index.tsx',
  'app/portal/relative/messages/[threadId].tsx',
  'src/features/communication/index.ts',
  'src/features/communication/communication.service.ts',
  'src/features/communication/communication.demoData.ts',
  'src/hooks/communication/index.ts',
  'src/components/communication/index.ts',
  'src/screens/communication/index.ts',
  'src/screens/communication/CommunicationCenterScreen.tsx',
  'docs/architecture/communication-center.md',
  'supabase/migrations/0011_communication_center.sql',
  'src/__tests__/communication/communicationCenter.test.ts',
  'README.md',
];

function fail(message) {
  console.error(`\n✗ Smoke-Check fehlgeschlagen: ${message}\n`);
  process.exit(1);
}

console.log('CareSuite+ Smoke-Check\n');

const missing = REQUIRED_FILES.filter((rel) => !existsSync(join(root, rel)));
if (missing.length > 0) {
  fail(`Fehlende Dateien:\n  - ${missing.join('\n  - ')}`);
}

console.log(`✓ ${REQUIRED_FILES.length} Kern-Dateien vorhanden`);

const regenerateTypes = spawnSync('npm', ['run', 'regenerate-router-types'], {
  cwd: root,
  stdio: 'inherit',
  shell: true,
});

if (regenerateTypes.status !== 0) {
  fail('Expo Router Types (npm run regenerate-router-types) fehlgeschlagen');
}

console.log('✓ Expo Router Types regeneriert');

const typecheck = spawnSync('npm', ['run', 'typecheck'], {
  cwd: root,
  stdio: 'inherit',
  shell: true,
});

if (typecheck.status !== 0) {
  fail('TypeScript-Check (npm run typecheck) fehlgeschlagen');
}

console.log('\n✓ Smoke-Check bestanden\n');
