import type { LiquidModuleDefinition, LiquidModuleKey, LiquidWorkArea } from '../types';

export const liquidModules: readonly LiquidModuleDefinition[] = [
  {
    key: 'home',
    label: 'Command Center',
    shortLabel: 'Heute',
    glyph: '⌂',
    route: '/liquid-command',
    description: 'Unternehmenslage, Live-Situation und nächste Entscheidungen.',
    primaryAction: 'Neue Aktion',
  },
  {
    key: 'office',
    label: 'Office',
    shortLabel: 'Office',
    glyph: '▣',
    route: '/liquid-command/office',
    description: 'Unternehmen, Personal, Abrechnung, Dokumente und Audit.',
    primaryAction: 'Datensatz anlegen',
  },
  {
    key: 'assist',
    label: 'Assist',
    shortLabel: 'Assist',
    glyph: '◇',
    route: '/liquid-command/assist',
    description: 'Einsätze, Planung, Live-Status, Nachweise und Budgets.',
    primaryAction: 'Einsatz planen',
  },
  {
    key: 'pflege',
    label: 'Pflege',
    shortLabel: 'Pflege',
    glyph: '✚',
    route: '/liquid-command/pflege',
    description: 'SIS, Maßnahmen, Medikation, Diagnosen und Wunden.',
    primaryAction: 'Dokumentieren',
  },
  {
    key: 'stationaer',
    label: 'Stationär',
    shortLabel: 'Stationär',
    glyph: '▦',
    route: '/liquid-command/stationaer',
    description: 'Bewohner:innen, Wohnbereiche, Schichten und Übergaben.',
    primaryAction: 'Übergabe starten',
  },
  {
    key: 'beratung',
    label: 'Beratung',
    shortLabel: 'Beratung',
    glyph: '◎',
    route: '/liquid-command/beratung',
    description: 'Fälle, Assessments, Empfehlungen und Follow-up.',
    primaryAction: 'Beratungsfall anlegen',
  },
  {
    key: 'akademie',
    label: 'Akademie',
    shortLabel: 'Akademie',
    glyph: '△',
    route: '/liquid-command/akademie',
    description: 'Lernpfade, Kurse, Prüfungen und Pflichtunterweisungen.',
    primaryAction: 'Lerninhalt anlegen',
  },
  {
    key: 'robotics',
    label: 'Robotics',
    shortLabel: 'Robotics',
    glyph: '⬡',
    route: '/liquid-command/robotics',
    description: 'Geräte, Aufgaben, Telemetrie, Wartung und Sicherheitszonen.',
    primaryAction: 'Gerät verbinden',
  },
  {
    key: 'platform',
    label: 'Platform Console',
    shortLabel: 'Platform',
    glyph: '◈',
    route: '/liquid-command/platform',
    description: 'Mandanten, Tarife, Flags, Support, Releases und Audit.',
    primaryAction: 'Mandant öffnen',
  },
  {
    key: 'settings',
    label: 'Einstellungen',
    shortLabel: 'Mehr',
    glyph: '⚙',
    route: '/liquid-command/settings',
    description: 'Organisation, Rollen, Integrationen, Datenschutz und Vorlagen.',
    primaryAction: 'Einstellung suchen',
  },
] as const;

export const liquidWorkAreas: Record<LiquidModuleKey, readonly LiquidWorkArea[]> = {
  home: [
    { id: 'situation', label: 'Live-Situation', description: 'Aktive Einsätze und Risiken', pageType: 'command-center', route: '/liquid-command' },
    { id: 'decisions', label: 'Entscheidungen', description: 'Freigaben und Eskalationen', pageType: 'review', route: '/liquid-command?area=decisions' },
  ],
  office: [
    { id: 'company', label: 'Unternehmen', description: 'Stammdaten, Standorte und Organisation', pageType: 'record', route: '/liquid-command/office?area=company' },
    { id: 'people', label: 'Personal', description: 'Mitarbeitende, Zeitkonten und Gehalt', pageType: 'work-list', route: '/liquid-command/office?area=people' },
    { id: 'billing', label: 'Rechnungen', description: 'Abrechnung, Zahlungen und Mahnungen', pageType: 'review', route: '/liquid-command/office?area=billing' },
    { id: 'documents', label: 'Dokumente', description: 'Vorschau, Download, Versionen und Signaturen', pageType: 'work-list', route: '/liquid-command/office?area=documents' },
    { id: 'communication', label: 'Kommunikation', description: 'Nachrichten, Aufgaben und Vorlagen', pageType: 'work-list', route: '/liquid-command/office?area=communication' },
    { id: 'inventory', label: 'Inventar', description: 'Geräte, Ausgabe und Rückgabe', pageType: 'work-list', route: '/liquid-command/office?area=inventory' },
    { id: 'audit', label: 'Audit', description: 'Nachvollziehbare Änderungen und Exporte', pageType: 'analytics', route: '/liquid-command/office?area=audit' },
  ],
  assist: [
    { id: 'clients', label: 'Klient:innen', description: 'Versorgungskontext und Budgets', pageType: 'work-list', route: '/liquid-command/assist?area=clients' },
    { id: 'assignments', label: 'Einsätze', description: 'Status, Bearbeitung und Abschluss', pageType: 'work-list', route: '/liquid-command/assist?area=assignments' },
    { id: 'planning', label: 'Planung', description: 'Kalender, Ressourcen und Konflikte', pageType: 'planning', route: '/liquid-command/assist?area=planning' },
    { id: 'live', label: 'Live-Status', description: 'GPS, Anfahrt und Abweichungen', pageType: 'command-center', route: '/liquid-command/assist?area=live' },
    { id: 'proofs', label: 'Nachweise', description: 'Prüfung, Unterschrift und Freigabe', pageType: 'review', route: '/liquid-command/assist?area=proofs' },
    { id: 'budgets', label: 'Budgets', description: 'Anspruch, Verbrauch und Prognose', pageType: 'analytics', route: '/liquid-command/assist?area=budgets' },
    { id: 'portals', label: 'Portale', description: 'Zugänge und Freigaben', pageType: 'settings', route: '/liquid-command/assist?area=portals' },
  ],
  pflege: [
    { id: 'sis', label: 'SIS', description: 'Strukturierte Informationssammlung', pageType: 'editor', route: '/liquid-command/pflege?area=sis' },
    { id: 'measures', label: 'Maßnahmen', description: 'Planung und Evaluation', pageType: 'planning', route: '/liquid-command/pflege?area=measures' },
    { id: 'medication', label: 'Medikation', description: 'Plan, Gabe und Abweichung', pageType: 'review', route: '/liquid-command/pflege?area=medication' },
    { id: 'diagnoses', label: 'Diagnosen', description: 'Diagnosen und Verordnungen', pageType: 'record', route: '/liquid-command/pflege?area=diagnoses' },
    { id: 'wounds', label: 'Wunden', description: 'BodyMap, Dekubitus und Verlauf', pageType: 'editor', route: '/liquid-command/pflege?area=wounds' },
    { id: 'vitals', label: 'Vitalwerte', description: 'Erfassung, Verlauf und Grenzwerte', pageType: 'analytics', route: '/liquid-command/pflege?area=vitals' },
    { id: 'reports', label: 'Pflegeberichte', description: 'Chronologie und Freigabe', pageType: 'work-list', route: '/liquid-command/pflege?area=reports' },
  ],
  stationaer: [
    { id: 'residents', label: 'Bewohner:innen', description: 'Akte und Versorgung', pageType: 'work-list', route: '/liquid-command/stationaer?area=residents' },
    { id: 'wards', label: 'Wohnbereiche', description: 'Belegung und Ressourcen', pageType: 'planning', route: '/liquid-command/stationaer?area=wards' },
    { id: 'shifts', label: 'Schichten', description: 'Besetzung und Übergaben', pageType: 'planning', route: '/liquid-command/stationaer?area=shifts' },
    { id: 'handover', label: 'Übergaben', description: 'Risiken, Aufgaben und Bestätigung', pageType: 'review', route: '/liquid-command/stationaer?area=handover' },
    { id: 'services', label: 'Leistungen', description: 'Durchführung und Nachweise', pageType: 'work-list', route: '/liquid-command/stationaer?area=services' },
    { id: 'occupancy', label: 'Belegung', description: 'Kapazität und Prognose', pageType: 'analytics', route: '/liquid-command/stationaer?area=occupancy' },
  ],
  beratung: [
    { id: 'cases', label: 'Beratungsfälle', description: 'Status, Verantwortung und Verlauf', pageType: 'work-list', route: '/liquid-command/beratung?area=cases' },
    { id: 'appointments', label: 'Termine', description: 'Planung und Vorbereitung', pageType: 'planning', route: '/liquid-command/beratung?area=appointments' },
    { id: 'assessments', label: 'Assessments', description: 'Geführte Erhebung', pageType: 'editor', route: '/liquid-command/beratung?area=assessments' },
    { id: 'recommendations', label: 'Empfehlungen', description: 'Maßnahmen und Freigabe', pageType: 'review', route: '/liquid-command/beratung?area=recommendations' },
    { id: 'proofs', label: 'Nachweise', description: 'Dokumentation und Export', pageType: 'work-list', route: '/liquid-command/beratung?area=proofs' },
    { id: 'follow-up', label: 'Follow-up', description: 'Wiedervorlagen und Ergebnisse', pageType: 'planning', route: '/liquid-command/beratung?area=follow-up' },
  ],
  akademie: [
    { id: 'paths', label: 'Lernpfade', description: 'Rollenbasierte Entwicklung', pageType: 'planning', route: '/liquid-command/akademie?area=paths' },
    { id: 'courses', label: 'Kurse', description: 'Inhalte und Termine', pageType: 'work-list', route: '/liquid-command/akademie?area=courses' },
    { id: 'exams', label: 'Prüfungen', description: 'Durchführung und Bewertung', pageType: 'review', route: '/liquid-command/akademie?area=exams' },
    { id: 'certificates', label: 'Zertifikate', description: 'Nachweis und Gültigkeit', pageType: 'work-list', route: '/liquid-command/akademie?area=certificates' },
    { id: 'mandatory', label: 'Pflichtunterweisungen', description: 'Fristen und Eskalation', pageType: 'analytics', route: '/liquid-command/akademie?area=mandatory' },
  ],
  robotics: [
    { id: 'devices', label: 'Geräte', description: 'Zustand und Zuordnung', pageType: 'work-list', route: '/liquid-command/robotics?area=devices' },
    { id: 'tasks', label: 'Aufgaben', description: 'Aufträge und Prioritäten', pageType: 'planning', route: '/liquid-command/robotics?area=tasks' },
    { id: 'telemetry', label: 'Telemetrie', description: 'Live-Daten und Abweichungen', pageType: 'analytics', route: '/liquid-command/robotics?area=telemetry' },
    { id: 'maintenance', label: 'Wartung', description: 'Intervalle und Nachweise', pageType: 'review', route: '/liquid-command/robotics?area=maintenance' },
    { id: 'zones', label: 'Sicherheitszonen', description: 'Freigaben und Grenzen', pageType: 'settings', route: '/liquid-command/robotics?area=zones' },
    { id: 'handover', label: 'Übergaben', description: 'Mensch-Maschine-Verantwortung', pageType: 'review', route: '/liquid-command/robotics?area=handover' },
  ],
  platform: [
    { id: 'tenants', label: 'Mandanten', description: 'Status, Module und Limits', pageType: 'work-list', route: '/liquid-command/platform?area=tenants' },
    { id: 'plans', label: 'Tarife', description: 'Pläne, Rabatte und Grenzen', pageType: 'settings', route: '/liquid-command/platform?area=plans' },
    { id: 'billing', label: 'Abrechnung', description: 'Rechnungen und Zahlungen', pageType: 'review', route: '/liquid-command/platform?area=billing' },
    { id: 'flags', label: 'Feature Flags', description: 'Kontrollierte Freigaben', pageType: 'settings', route: '/liquid-command/platform?area=flags' },
    { id: 'support', label: 'Support', description: 'Fälle und Systemdiagnose', pageType: 'work-list', route: '/liquid-command/platform?area=support' },
    { id: 'releases', label: 'Releases', description: 'Versionen und Deploy-Status', pageType: 'review', route: '/liquid-command/platform?area=releases' },
    { id: 'audit', label: 'Audit', description: 'Systemweite Ereignisse', pageType: 'analytics', route: '/liquid-command/platform?area=audit' },
  ],
  settings: [
    { id: 'organization', label: 'Organisation', description: 'Stammdaten und Standorte', pageType: 'settings', route: '/liquid-command/settings?area=organization' },
    { id: 'roles', label: 'Rollen & Rechte', description: 'Berechtigungen und Wirkung', pageType: 'settings', route: '/liquid-command/settings?area=roles' },
    { id: 'integrations', label: 'Integrationen', description: 'Workspace, DATEV und Telemedizin', pageType: 'settings', route: '/liquid-command/settings?area=integrations' },
    { id: 'privacy', label: 'Datenschutz', description: 'Einwilligungen und Aufbewahrung', pageType: 'settings', route: '/liquid-command/settings?area=privacy' },
    { id: 'templates', label: 'Vorlagen', description: 'Dokumente und Kommunikation', pageType: 'settings', route: '/liquid-command/settings?area=templates' },
    { id: 'branding', label: 'Branding', description: 'Mandantenidentität ohne Modulfarben', pageType: 'settings', route: '/liquid-command/settings?area=branding' },
  ],
};

export function getLiquidModule(key: LiquidModuleKey): LiquidModuleDefinition {
  return liquidModules.find((module) => module.key === key) ?? liquidModules[0];
}
