import { DEMO_TENANT_ID } from '@/data/constants/testTenant';
import type {
  CommunicationAttachment,
  CommunicationAuditEvent,
  CommunicationMessage,
  CommunicationNotification,
  CommunicationParticipant,
  CommunicationSettings,
  CommunicationThread,
  MessageAssignment,
  MessageReaction,
} from './communication.types';

const TENANT = DEMO_TENANT_ID;
const NOW = '2026-06-13T10:00:00.000Z';

function daysAgo(days: number, hour = 10): string {
  const d = new Date('2026-06-13T10:00:00.000Z');
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

function msg(
  partial: Partial<CommunicationMessage> &
    Pick<CommunicationMessage, 'id' | 'threadId' | 'senderType' | 'senderDisplayName' | 'contentType'>,
): CommunicationMessage {
  const createdAt = partial.createdAt ?? partial.sentAt ?? NOW;
  return {
    tenantId: TENANT,
    senderUserId: null,
    senderPortalSessionId: null,
    bodyText: null,
    hasAttachments: false,
    hasVoice: false,
    emojiReactionsCount: 0,
    status: 'sent',
    isInternalNote: false,
    isVisibleToBusiness: true,
    isVisibleToEmployee: false,
    isVisibleToClient: false,
    isVisibleToRelative: false,
    sentAt: null,
    deliveredAt: null,
    readAt: null,
    editedAt: null,
    editedBy: null,
    deletedAt: null,
    deletedBy: null,
    deleteReason: null,
    replyToMessageId: null,
    createdAt,
    updatedAt: partial.updatedAt ?? createdAt,
    ...partial,
  };
}

function thread(partial: Omit<CommunicationThread, 'tenantId' | 'createdAt' | 'updatedAt'>): CommunicationThread {
  return {
    tenantId: TENANT,
    createdAt: daysAgo(30),
    updatedAt: partial.lastMessageAt ?? NOW,
    ...partial,
  };
}

export type CommunicationDemoBundle = {
  threads: CommunicationThread[];
  messages: CommunicationMessage[];
  participants: CommunicationParticipant[];
  attachments: CommunicationAttachment[];
  reactions: MessageReaction[];
  assignments: MessageAssignment[];
  notifications: CommunicationNotification[];
  auditEvents: CommunicationAuditEvent[];
  settings: CommunicationSettings;
};

export function buildCommunicationDemoData(): CommunicationDemoBundle {
  const threads: CommunicationThread[] = [];
  const messages: CommunicationMessage[] = [];
  const participants: CommunicationParticipant[] = [];
  const attachments: CommunicationAttachment[] = [];
  const reactions: MessageReaction[] = [];
  const assignments: MessageAssignment[] = [];

  const addThread = (t: CommunicationThread, ps: CommunicationParticipant[]) => {
    threads.push(t);
    participants.push(...ps);
  };

  const addMsgs = (...items: CommunicationMessage[]) => {
    messages.push(...items);
  };

  // --- 5 Klient:innen-Threads ---
  const clientSpecs = [
    { id: 'thread-client-001', clientId: 'client-001', title: 'Helga Schneider', preview: 'Wann kommt morgen meine Betreuung?' },
    { id: 'thread-client-002', clientId: 'client-002', title: 'Werner Müller', preview: 'Terminverschiebung nächste Woche' },
    { id: 'thread-client-003', clientId: 'client-003', title: 'Ingrid Hoffmann', preview: 'Danke für die schnelle Antwort!' },
    { id: 'thread-client-004', clientId: 'client-004', title: 'Erika Wagner', preview: 'Rezept wurde zugestellt' },
    { id: 'thread-client-005', clientId: 'client-005', title: 'Hans Becker', preview: 'Rückfrage zum Pflegeplan' },
  ];

  clientSpecs.forEach((spec, i) => {
    const m1 = msg({
      id: `msg-${spec.id}-1`,
      threadId: spec.id,
      senderType: 'client_portal',
      senderUserId: 'profile-client-001',
      senderPortalSessionId: null,
      senderDisplayName: spec.title,
      contentType: 'text',
      bodyText: i === 0 ? 'Wann kommt morgen meine Betreuung?' : `Rückfrage von ${spec.title} (${i + 1})`,
      hasAttachments: false,
      hasVoice: false,
      status: i === 0 ? 'delivered' : 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: true,
      isVisibleToRelative: i === 0,
      sentAt: daysAgo(2 - i, 9),
      deliveredAt: daysAgo(2 - i, 9),
      readAt: i === 0 ? null : daysAgo(1),
      replyToMessageId: null,
    });
    const m2 = msg({
      id: `msg-${spec.id}-2`,
      threadId: spec.id,
      senderType: 'business_user',
      senderUserId: 'profile-admin-001',
      senderPortalSessionId: null,
      senderDisplayName: 'CareSuite Büro',
      contentType: 'text',
      bodyText: 'Wir haben Ihre Rückfrage erhalten und melden uns schnellstmöglich.',
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: true,
      isVisibleToRelative: true,
      sentAt: daysAgo(2 - i, 11),
      deliveredAt: daysAgo(2 - i, 11),
      readAt: daysAgo(1),
      replyToMessageId: m1.id,
    });
    const m3 = msg({
      id: `msg-${spec.id}-internal`,
      threadId: spec.id,
      senderType: 'business_user',
      senderUserId: 'profile-admin-001',
      senderPortalSessionId: null,
      senderDisplayName: 'Sabine Muster',
      contentType: 'internal_note',
      bodyText:
        i === 0
          ? 'Bitte nicht im Portal sichtbar machen. Erst mit Frau Schmidt abstimmen.'
          : `Interne Klient:innennotiz ${spec.title}`,
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: true,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: false,
      isVisibleToRelative: false,
      sentAt: daysAgo(1, 14),
      deliveredAt: daysAgo(1, 14),
      readAt: daysAgo(1, 15),
      replyToMessageId: null,
    });
    addMsgs(m1, m2, m3);
    addThread(
      thread({
        id: spec.id,
        threadType: 'client',
        status: i === 4 ? 'waiting_for_business' : 'open',
        priority: i === 0 ? 'high' : 'normal',
        subject: null,
        title: spec.title,
        previewText: spec.preview,
        moduleKey: 'office',
        clientId: spec.clientId,
        employeeId: null,
        relativeContactId: null,
        assignmentId: null,
        documentId: null,
        invoiceId: null,
        consultationCaseId: null,
        courseId: null,
        supportTicketId: null,
        createdByUserId: 'profile-admin-001',
        createdByPortalSessionId: null,
        lastMessageId: m3.id,
        lastMessageAt: m3.sentAt,
        lastMessageByDisplayName: m3.senderDisplayName,
        unreadCountBusiness: i === 0 ? 1 : 0,
        unreadCountEmployee: 0,
        unreadCountClient: i === 0 ? 1 : 0,
        unreadCountRelative: 0,
        isInternalOnly: false,
        isPortalVisible: true,
        allowClientReplies: true,
        allowEmployeeReplies: false,
        allowRelativeReplies: i === 0,
        archivedAt: null,
        archivedBy: null,
        deletedAt: null,
        deletedBy: null,
      }),
      [
        {
          id: `part-${spec.id}-client`,
          tenantId: TENANT,
          threadId: spec.id,
          participantType: 'client',
          participantId: spec.clientId,
          displayName: spec.title,
          avatarUrl: null,
          role: 'portal_user',
          canRead: true,
          canWrite: true,
          canUpload: true,
          canVoiceMessage: true,
          canArchive: false,
          canDelete: false,
          canAssign: false,
          lastReadMessageId: m1.id,
          lastReadAt: m1.sentAt,
          muted: false,
          pinned: false,
          createdAt: daysAgo(30),
          updatedAt: NOW,
        },
        {
          id: `part-${spec.id}-office`,
          tenantId: TENANT,
          threadId: spec.id,
          participantType: 'business_user',
          participantId: 'profile-admin-001',
          displayName: 'CareSuite Büro',
          avatarUrl: null,
          role: 'admin',
          canRead: true,
          canWrite: true,
          canUpload: true,
          canVoiceMessage: true,
          canArchive: true,
          canDelete: true,
          canAssign: true,
          lastReadMessageId: m2.id,
          lastReadAt: m2.readAt,
          muted: false,
          pinned: i === 0,
          createdAt: daysAgo(30),
          updatedAt: NOW,
        },
      ],
    );
  });

  // --- 5 Mitarbeitenden-Threads ---
  const employeeSpecs = [
    { id: 'thread-employee-001', employeeId: 'employee-003', title: 'Sandra Meier', preview: 'Ich finde den Eingang nicht.' },
    { id: 'thread-employee-002', employeeId: 'employee-001', title: 'Thomas Keller', preview: 'Einsatz morgen bestätigt' },
    { id: 'thread-employee-003', employeeId: 'employee-002', title: 'Anna Krüger', preview: 'Material fehlt im Auto' },
    { id: 'thread-employee-004', employeeId: 'employee-004', title: 'Michael Braun', preview: 'Urlaubsantrag Juni' },
    { id: 'thread-employee-005', employeeId: 'employee-005', title: 'Lisa Hoffmann', preview: 'Schulung nächste Woche' },
  ];

  employeeSpecs.forEach((spec, i) => {
    const m1 = msg({
      id: `msg-${spec.id}-1`,
      threadId: spec.id,
      senderType: 'employee_portal',
      senderUserId: 'profile-portal-employee-001',
      senderPortalSessionId: null,
      senderDisplayName: spec.title,
      contentType: i === 0 ? 'text' : 'text',
      bodyText: i === 0 ? 'Ich finde den Eingang nicht.' : `Nachricht von ${spec.title}`,
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: true,
      isVisibleToClient: false,
      isVisibleToRelative: false,
      sentAt: daysAgo(3 - i, 8),
      deliveredAt: daysAgo(3 - i, 8),
      readAt: daysAgo(2),
      replyToMessageId: null,
    });
    const m2 = msg({
      id: `msg-${spec.id}-2`,
      threadId: spec.id,
      senderType: 'business_user',
      senderUserId: 'profile-dispatch-001',
      senderPortalSessionId: null,
      senderDisplayName: 'Einsatzplanung',
      contentType: 'text',
      bodyText: i === 0 ? 'Der Eingang ist hinten am Hof — bitte klingeln Sie bei Schneider.' : 'Vielen Dank, wir haben das notiert.',
      hasAttachments: false,
      hasVoice: false,
      status: 'delivered',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: true,
      isVisibleToClient: false,
      isVisibleToRelative: false,
      sentAt: daysAgo(2 - i, 9),
      deliveredAt: daysAgo(2 - i, 9),
      readAt: null,
      replyToMessageId: m1.id,
    });
    addMsgs(m1, m2);
    addThread(
      thread({
        id: spec.id,
        threadType: 'employee',
        status: 'open',
        priority: i === 0 ? 'urgent' : 'normal',
        subject: null,
        title: spec.title,
        previewText: spec.preview,
        moduleKey: 'assist',
        clientId: null,
        employeeId: spec.employeeId,
        relativeContactId: null,
        assignmentId: i === 0 ? 'assignment-001' : null,
        documentId: null,
        invoiceId: null,
        consultationCaseId: null,
        courseId: null,
        supportTicketId: null,
        createdByUserId: null,
        createdByPortalSessionId: 'portal-session-emp-001',
        lastMessageId: m2.id,
        lastMessageAt: m2.sentAt,
        lastMessageByDisplayName: m2.senderDisplayName,
        unreadCountBusiness: 0,
        unreadCountEmployee: 1,
        unreadCountClient: 0,
        unreadCountRelative: 0,
        isInternalOnly: false,
        isPortalVisible: true,
        allowClientReplies: false,
        allowEmployeeReplies: true,
        allowRelativeReplies: false,
        archivedAt: null,
        archivedBy: null,
        deletedAt: null,
        deletedBy: null,
      }),
      [
        {
          id: `part-${spec.id}-emp`,
          tenantId: TENANT,
          threadId: spec.id,
          participantType: 'employee',
          participantId: spec.employeeId,
          displayName: spec.title,
          avatarUrl: null,
          role: 'portal_user',
          canRead: true,
          canWrite: true,
          canUpload: true,
          canVoiceMessage: true,
          canArchive: false,
          canDelete: false,
          canAssign: false,
          lastReadMessageId: m1.id,
          lastReadAt: m1.sentAt,
          muted: false,
          pinned: false,
          createdAt: daysAgo(20),
          updatedAt: NOW,
        },
      ],
    );
  });

  // --- 3 Angehörigen-Threads ---
  ['thread-relative-001', 'thread-relative-002', 'thread-relative-003'].forEach((id, i) => {
    const m1 = msg({
      id: `msg-${id}-1`,
      threadId: id,
      senderType: 'relative_portal',
      senderUserId: 'profile-family-001',
      senderPortalSessionId: null,
      senderDisplayName: 'Karin Schneider',
      contentType: 'text',
      bodyText:
        i === 0
          ? 'Kann ich den Leistungsnachweis für Mai erhalten?'
          : `Angehörigenanfrage ${i + 1}`,
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: false,
      isVisibleToRelative: true,
      sentAt: daysAgo(5 - i, 10),
      deliveredAt: daysAgo(5 - i, 10),
      readAt: daysAgo(4),
      replyToMessageId: null,
    });
    addMsgs(m1);
    addThread(
      thread({
        id,
        threadType: 'relative',
        status: 'open',
        priority: 'normal',
        subject: null,
        title: 'Karin Schneider (Angehörige)',
        previewText: m1.bodyText,
        moduleKey: 'office',
        clientId: 'client-001',
        employeeId: null,
        relativeContactId: 'contact-hs-relative-1',
        assignmentId: null,
        documentId: null,
        invoiceId: null,
        consultationCaseId: null,
        courseId: null,
        supportTicketId: null,
        createdByUserId: null,
        createdByPortalSessionId: 'portal-session-rel-001',
        lastMessageId: m1.id,
        lastMessageAt: m1.sentAt,
        lastMessageByDisplayName: m1.senderDisplayName,
        unreadCountBusiness: 0,
        unreadCountEmployee: 0,
        unreadCountClient: 0,
        unreadCountRelative: 0,
        isInternalOnly: false,
        isPortalVisible: true,
        allowClientReplies: false,
        allowEmployeeReplies: false,
        allowRelativeReplies: true,
        archivedAt: null,
        archivedBy: null,
        deletedAt: null,
        deletedBy: null,
      }),
      [],
    );
  });

  // --- 4 interne Threads ---
  const internalTitles = ['Büro Allgemein', 'Einsatzplanung', 'Abrechnung Q2', 'Geschäftsführung'];
  internalTitles.forEach((title, i) => {
    const id = `thread-internal-${String(i + 1).padStart(3, '0')}`;
    const m1 = msg({
      id: `msg-${id}-1`,
      threadId: id,
      senderType: 'business_user',
      senderUserId: 'profile-admin-001',
      senderPortalSessionId: null,
      senderDisplayName: 'Sabine Muster',
      contentType: 'text',
      bodyText: `Interne Teamnachricht: ${title}`,
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: false,
      isVisibleToRelative: false,
      sentAt: daysAgo(7 - i, 13),
      deliveredAt: daysAgo(7 - i, 13),
      readAt: daysAgo(6),
      replyToMessageId: null,
    });
    const note = msg({
      id: `msg-${id}-note`,
      threadId: id,
      senderType: 'business_user',
      senderUserId: 'profile-admin-001',
      senderPortalSessionId: null,
      senderDisplayName: 'Sabine Muster',
      contentType: 'internal_note',
      bodyText: 'Nur für internes Team — nicht an Portale weiterleiten.',
      hasAttachments: false,
      hasVoice: false,
      status: 'read',
      isInternalNote: true,
      isVisibleToBusiness: true,
      isVisibleToEmployee: false,
      isVisibleToClient: false,
      isVisibleToRelative: false,
      sentAt: daysAgo(6 - i, 14),
      deliveredAt: daysAgo(6 - i, 14),
      readAt: daysAgo(5),
      replyToMessageId: null,
    });
    addMsgs(m1, note);
    addThread(
      thread({
        id,
        threadType: 'internal',
        status: 'open',
        priority: 'normal',
        subject: null,
        title,
        previewText: note.bodyText,
        moduleKey: 'core',
        clientId: null,
        employeeId: null,
        relativeContactId: null,
        assignmentId: null,
        documentId: null,
        invoiceId: null,
        consultationCaseId: null,
        courseId: null,
        supportTicketId: null,
        createdByUserId: 'profile-admin-001',
        createdByPortalSessionId: null,
        lastMessageId: note.id,
        lastMessageAt: note.sentAt,
        lastMessageByDisplayName: note.senderDisplayName,
        unreadCountBusiness: 0,
        unreadCountEmployee: 0,
        unreadCountClient: 0,
        unreadCountRelative: 0,
        isInternalOnly: true,
        isPortalVisible: false,
        allowClientReplies: false,
        allowEmployeeReplies: false,
        allowRelativeReplies: false,
        archivedAt: null,
        archivedBy: null,
        deletedAt: null,
        deletedBy: null,
      }),
      [],
    );
  });

  // --- Spezial-Threads: assignment, document, invoice, consultation, course ---
  const specialThreads: Array<Omit<CommunicationThread, 'tenantId' | 'createdAt' | 'updatedAt'>> = [
    {
      id: 'thread-assignment-001',
      threadType: 'assignment',
      status: 'open',
      priority: 'high',
      subject: 'Einsatz Helga Schneider',
      title: 'Einsatz 12.06. — Helga Schneider',
      previewText: 'Verspätung wegen Verkehr',
      moduleKey: 'assist',
      clientId: 'client-001',
      employeeId: 'employee-003',
      relativeContactId: null,
      assignmentId: 'assignment-001',
      documentId: null,
      invoiceId: null,
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-dispatch-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(1, 7),
      lastMessageByDisplayName: 'Sandra Meier',
      unreadCountBusiness: 1,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: true,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-assignment-002',
      threadType: 'assignment',
      status: 'resolved',
      priority: 'normal',
      subject: null,
      title: 'Einsatz Werner Müller',
      previewText: 'Check-out erfolgreich',
      moduleKey: 'assist',
      clientId: 'client-002',
      employeeId: 'employee-003',
      relativeContactId: null,
      assignmentId: 'assignment-002',
      documentId: null,
      invoiceId: null,
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-dispatch-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(3),
      lastMessageByDisplayName: 'System',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: true,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-assignment-003',
      threadType: 'assignment',
      status: 'archived',
      priority: 'low',
      subject: null,
      title: 'Einsatz Ingrid Hoffmann',
      previewText: 'Archiviert',
      moduleKey: 'assist',
      clientId: 'client-003',
      employeeId: 'employee-001',
      relativeContactId: null,
      assignmentId: 'assignment-003',
      documentId: null,
      invoiceId: null,
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-dispatch-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(20),
      lastMessageByDisplayName: 'Thomas Keller',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: true,
      allowRelativeReplies: false,
      archivedAt: daysAgo(15),
      archivedBy: 'profile-dispatch-001',
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-document-001',
      threadType: 'document',
      status: 'open',
      priority: 'normal',
      subject: 'Pflegeplan PDF',
      title: 'Dokument: Pflegeplan Helga Schneider',
      previewText: 'Dokument wurde dem Klienten zugeordnet.',
      moduleKey: 'office',
      clientId: 'client-001',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: 'doc-hs-1',
      invoiceId: null,
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-admin-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(4),
      lastMessageByDisplayName: 'System',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 1,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: true,
      allowEmployeeReplies: false,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-document-002',
      threadType: 'document',
      status: 'open',
      priority: 'normal',
      subject: null,
      title: 'Dokument: Vertrag Werner Müller',
      previewText: 'Bitte unterschreiben',
      moduleKey: 'office',
      clientId: 'client-002',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: 'doc-wm-1',
      invoiceId: null,
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-admin-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(6),
      lastMessageByDisplayName: 'CareSuite Büro',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: true,
      allowEmployeeReplies: false,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-invoice-001',
      threadType: 'invoice',
      status: 'waiting_for_portal_user',
      priority: 'normal',
      subject: 'Rechnung 2026-042',
      title: 'Rechnung Helga Schneider',
      previewText: 'Zahlungserinnerung',
      moduleKey: 'office',
      clientId: 'client-001',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: 'invoice-001',
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-billing-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(8),
      lastMessageByDisplayName: 'Abrechnung',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 1,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: true,
      allowEmployeeReplies: false,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-invoice-002',
      threadType: 'invoice',
      status: 'open',
      priority: 'low',
      subject: null,
      title: 'Rechnung Werner Müller',
      previewText: 'Kostenträger klären',
      moduleKey: 'office',
      clientId: 'client-002',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: 'invoice-002',
      consultationCaseId: null,
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-billing-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(10),
      lastMessageByDisplayName: 'Abrechnung',
      unreadCountBusiness: 1,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: false,
      allowClientReplies: false,
      allowEmployeeReplies: false,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-consultation-001',
      threadType: 'consultation',
      status: 'open',
      priority: 'normal',
      subject: 'Beratungsfall Pflegegrad',
      title: 'Beratung: Pflegegrad Helga Schneider',
      previewText: 'Unterlagen angefordert',
      moduleKey: 'beratung',
      clientId: 'client-001',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: null,
      consultationCaseId: 'case-001',
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-counselor-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(5),
      lastMessageByDisplayName: 'Beratungskraft',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: true,
      allowEmployeeReplies: false,
      allowRelativeReplies: true,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-consultation-002',
      threadType: 'consultation',
      status: 'resolved',
      priority: 'normal',
      subject: null,
      title: 'Beratung: Entlastungsleistungen',
      previewText: 'Fall abgeschlossen',
      moduleKey: 'beratung',
      clientId: 'client-003',
      employeeId: null,
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: null,
      consultationCaseId: 'case-002',
      courseId: null,
      supportTicketId: null,
      createdByUserId: 'profile-counselor-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(12),
      lastMessageByDisplayName: 'Beratungskraft',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: false,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-course-001',
      threadType: 'course',
      status: 'open',
      priority: 'normal',
      subject: 'Hygiene-Schulung',
      title: 'Akademie: Basishygiene Pflege',
      previewText: 'Teilnahme bestätigt 👍',
      moduleKey: 'akademie',
      clientId: null,
      employeeId: 'employee-002',
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: null,
      consultationCaseId: null,
      courseId: 'course-001',
      supportTicketId: null,
      createdByUserId: 'profile-akademie-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(2),
      lastMessageByDisplayName: 'Akademie-Admin',
      unreadCountBusiness: 0,
      unreadCountEmployee: 1,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: true,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
    {
      id: 'thread-course-002',
      threadType: 'course',
      status: 'open',
      priority: 'low',
      subject: null,
      title: 'Akademie: Erste Hilfe Auffrischung',
      previewText: 'Termin verschoben',
      moduleKey: 'akademie',
      clientId: null,
      employeeId: 'employee-001',
      relativeContactId: null,
      assignmentId: null,
      documentId: null,
      invoiceId: null,
      consultationCaseId: null,
      courseId: 'course-002',
      supportTicketId: null,
      createdByUserId: 'profile-akademie-001',
      createdByPortalSessionId: null,
      lastMessageId: null,
      lastMessageAt: daysAgo(4),
      lastMessageByDisplayName: 'Akademie-Admin',
      unreadCountBusiness: 0,
      unreadCountEmployee: 0,
      unreadCountClient: 0,
      unreadCountRelative: 0,
      isInternalOnly: false,
      isPortalVisible: true,
      allowClientReplies: false,
      allowEmployeeReplies: true,
      allowRelativeReplies: false,
      archivedAt: null,
      archivedBy: null,
      deletedAt: null,
      deletedBy: null,
    },
  ];

  specialThreads.forEach((st) => {
    const sys = msg({
      id: `msg-${st.id}-sys`,
      threadId: st.id,
      senderType: 'system',
      senderUserId: null,
      senderPortalSessionId: null,
      senderDisplayName: 'System',
      contentType: 'system',
      bodyText:
        st.threadType === 'document'
          ? 'Dokument wurde dem Klienten zugeordnet.'
          : `Thread ${st.title} erstellt.`,
      hasAttachments: st.threadType === 'document',
      hasVoice: false,
      status: 'read',
      isInternalNote: false,
      isVisibleToBusiness: true,
      isVisibleToEmployee: st.employeeId !== null,
      isVisibleToClient: st.clientId !== null && st.isPortalVisible,
      isVisibleToRelative: false,
      sentAt: st.lastMessageAt,
      deliveredAt: st.lastMessageAt,
      readAt: st.lastMessageAt,
      replyToMessageId: null,
    });
    st.lastMessageId = sys.id;
    addMsgs(sys);
    addThread(thread(st), []);

    if (st.threadType === 'document' && st.documentId) {
      attachments.push({
        id: `att-${st.id}`,
        tenantId: TENANT,
        threadId: st.id,
        messageId: sys.id,
        attachmentType: 'pdf',
        filename: 'Pflegeplan.pdf',
        mimeType: 'application/pdf',
        sizeBytes: 245_000,
        storagePath: `tenant/${TENANT}/threads/${st.id}/attachments/att-${st.id}/Pflegeplan.pdf`,
        publicUrl: null,
        scanStatus: 'safe',
        durationSeconds: null,
        waveformPreview: null,
        linkedDocumentId: st.documentId,
        uploadedBy: 'profile-admin-001',
        createdAt: sys.sentAt!,
        updatedAt: sys.sentAt!,
      });
    }
  });

  // Bulk messages to reach 80+
  let msgCounter = 100;
  threads.forEach((t) => {
    const existing = messages.filter((m) => m.threadId === t.id).length;
    const needed = Math.max(0, 3 - existing);
    for (let j = 0; j < needed; j += 1) {
      msgCounter += 1;
      const m = msg({
        id: `msg-bulk-${msgCounter}`,
        threadId: t.id,
        senderType: j % 2 === 0 ? 'business_user' : 'client_portal',
        senderUserId: j % 2 === 0 ? 'profile-admin-001' : 'profile-client-001',
        senderPortalSessionId: null,
        senderDisplayName: j % 2 === 0 ? 'CareSuite Büro' : t.title,
        contentType: 'text',
        bodyText: `Demo-Nachricht ${msgCounter} im Thread ${t.title}. 😊`,
        hasAttachments: false,
        hasVoice: false,
        status: j === 0 ? 'failed' : 'read',
        isInternalNote: false,
        isVisibleToBusiness: true,
        isVisibleToEmployee: t.threadType === 'employee',
        isVisibleToClient: t.threadType === 'client',
        isVisibleToRelative: t.threadType === 'relative',
        sentAt: daysAgo(j + 1, 12 + j),
        deliveredAt: daysAgo(j + 1, 12 + j),
        readAt: j === 0 ? null : daysAgo(j),
        replyToMessageId: null,
      });
      addMsgs(m);
    }
  });

  // Voice message demo
  const voiceMsg = msg({
    id: 'msg-voice-001',
    threadId: 'thread-client-001',
    senderType: 'client_portal',
    senderUserId: 'profile-client-001',
    senderPortalSessionId: null,
    senderDisplayName: 'Helga Schneider',
    contentType: 'voice',
    bodyText: null,
    hasAttachments: true,
    hasVoice: true,
    status: 'delivered',
    isInternalNote: false,
    isVisibleToBusiness: true,
    isVisibleToEmployee: false,
    isVisibleToClient: true,
    isVisibleToRelative: false,
    sentAt: daysAgo(0, 8),
    deliveredAt: daysAgo(0, 8),
    readAt: null,
    replyToMessageId: null,
  });
  addMsgs(voiceMsg);
  attachments.push({
    id: 'att-voice-001',
    tenantId: TENANT,
    threadId: 'thread-client-001',
    messageId: voiceMsg.id,
    attachmentType: 'voice',
    filename: 'sprachnachricht.m4a',
    mimeType: 'audio/m4a',
    sizeBytes: 48_000,
    storagePath: `tenant/${TENANT}/communication/thread-client-001/voice/${voiceMsg.id}.m4a`,
    publicUrl: null,
    scanStatus: 'safe',
    durationSeconds: 12,
    waveformPreview: [0.2, 0.5, 0.8, 0.4, 0.6],
    linkedDocumentId: null,
    uploadedBy: 'profile-client-001',
    createdAt: voiceMsg.sentAt!,
    updatedAt: voiceMsg.sentAt!,
  });

  // Deleted message demo
  const deletedMsg = msg({
    id: 'msg-deleted-001',
    threadId: 'thread-client-002',
    senderType: 'client_portal',
    senderUserId: 'profile-client-001',
    senderPortalSessionId: null,
    senderDisplayName: 'Werner Müller',
    contentType: 'text',
    bodyText: null,
    hasAttachments: false,
    hasVoice: false,
    status: 'deleted',
    isInternalNote: false,
    isVisibleToBusiness: true,
    isVisibleToEmployee: false,
    isVisibleToClient: false,
    isVisibleToRelative: false,
    sentAt: daysAgo(3),
    deliveredAt: daysAgo(3),
    readAt: daysAgo(2),
    deletedAt: daysAgo(1),
    deletedBy: 'profile-admin-001',
    deleteReason: 'Datenschutzanfrage',
    replyToMessageId: null,
  });
  addMsgs(deletedMsg);

  // Reactions
  const reactTarget = messages.find((m) => m.id === 'msg-thread-course-001-sys');
  if (reactTarget) {
    reactions.push({
      id: 'react-001',
      tenantId: TENANT,
      threadId: reactTarget.threadId,
      messageId: reactTarget.id,
      emoji: '👍',
      reactedByType: 'employee_portal',
      reactedById: 'employee-002',
      reactedByDisplayName: 'Anna Krüger',
      createdAt: daysAgo(1),
      updatedAt: daysAgo(1),
    });
    reactTarget.emojiReactionsCount = 1;
  }

  // Assignments
  assignments.push(
    {
      id: 'assign-001',
      tenantId: TENANT,
      threadId: 'thread-client-001',
      messageId: 'msg-thread-client-001-1',
      targetType: 'client',
      targetId: 'client-001',
      suggestedTargetId: 'client-001',
      suggestionConfidence: 0.95,
      status: 'assigned',
      assignedBy: 'profile-admin-001',
      assignedAt: daysAgo(2),
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'assign-002',
      tenantId: TENANT,
      threadId: 'thread-invoice-002',
      messageId: null,
      targetType: 'invoice',
      targetId: 'invoice-002',
      suggestedTargetId: 'invoice-002',
      suggestionConfidence: 0.88,
      status: 'open',
      assignedBy: null,
      assignedAt: null,
      createdAt: daysAgo(10),
      updatedAt: daysAgo(10),
    },
    {
      id: 'assign-003',
      tenantId: TENANT,
      threadId: 'thread-employee-001',
      messageId: 'msg-thread-employee-001-1',
      targetType: 'assignment',
      targetId: 'assignment-001',
      suggestedTargetId: 'assignment-001',
      suggestionConfidence: 0.72,
      status: 'in_review',
      assignedBy: null,
      assignedAt: null,
      createdAt: daysAgo(3),
      updatedAt: daysAgo(3),
    },
  );

  const settings: CommunicationSettings = {
    id: 'comm-settings-001',
    tenantId: TENANT,
    centerEnabled: true,
    clientPortalEnabled: true,
    employeePortalEnabled: true,
    relativePortalEnabled: true,
    voiceMessagesEnabled: true,
    attachmentsEnabled: true,
    emojisEnabled: true,
    reactionsEnabled: true,
    internalNotesEnabled: true,
    autoArchiveMonths: 12,
    maxFileSizeMb: 25,
    allowedFileTypes: ['pdf', 'jpg', 'png', 'docx', 'm4a'],
    pushEnabled: false,
    emailEnabled: true,
    smsEnabled: false,
    realtimeEnabled: true,
    showReadReceipts: true,
    showTypingIndicator: true,
    createdAt: daysAgo(365),
    updatedAt: NOW,
  };

  const auditEvents: CommunicationAuditEvent[] = [
    {
      id: 'audit-comm-001',
      tenantId: TENANT,
      userId: 'profile-admin-001',
      portalSessionId: null,
      action: 'thread_created',
      entityType: 'communication_thread',
      entityId: 'thread-client-001',
      threadId: 'thread-client-001',
      messageId: null,
      clientId: 'client-001',
      employeeId: null,
      result: 'success',
      metadata: { title: 'Helga Schneider' },
      createdAt: daysAgo(30),
      updatedAt: daysAgo(30),
    },
    {
      id: 'audit-comm-002',
      tenantId: TENANT,
      userId: 'profile-admin-001',
      portalSessionId: null,
      action: 'message_sent',
      entityType: 'communication_message',
      entityId: 'msg-thread-client-001-2',
      threadId: 'thread-client-001',
      messageId: 'msg-thread-client-001-2',
      clientId: 'client-001',
      employeeId: null,
      result: 'success',
      metadata: null,
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
  ];

  const notifications: CommunicationNotification[] = [
    {
      id: 'notif-comm-001',
      tenantId: TENANT,
      type: 'new_client_message',
      threadId: 'thread-client-001',
      messageId: 'msg-thread-client-001-1',
      title: 'Neue Klient:innennachricht',
      body: 'Helga Schneider: Wann kommt morgen meine Betreuung?',
      readAt: null,
      actionRoute: '/business/messages/thread-client-001',
      createdAt: daysAgo(2),
      updatedAt: daysAgo(2),
    },
    {
      id: 'notif-comm-002',
      tenantId: TENANT,
      type: 'high_priority',
      threadId: 'thread-employee-001',
      messageId: 'msg-thread-employee-001-1',
      title: 'Dringende Mitarbeiternachricht',
      body: 'Sandra Meier: Ich finde den Eingang nicht.',
      readAt: daysAgo(1),
      actionRoute: '/business/messages/thread-employee-001',
      createdAt: daysAgo(3),
      updatedAt: daysAgo(1),
    },
  ];

  return {
    threads,
    messages,
    participants,
    attachments,
    reactions,
    assignments,
    notifications,
    auditEvents,
    settings,
  };
}

export const COMMUNICATION_DEMO_MESSAGE_COUNT = buildCommunicationDemoData().messages.length;
