import type { ClientCareContext } from '@/lib/clients/clientIntakeFieldRules';

export type ClientIntakeFormData = {
  careContexts: ClientCareContext[];
  firstName: string;
  lastName: string;
  salutation: string;
  gender: string;
  dateOfBirth: string;
  birthPlace: string;
  nationality: string;
  language: string;
  maritalStatus: string;
  housingForm: string;
  specialNotes: string;
  status: string;
  admissionDate: string;
  serviceStart: string;
  street: string;
  houseNumber: string;
  zip: string;
  city: string;
  addressExtra: string;
  floor: string;
  elevatorAvailable: boolean;
  phone: string;
  mobile: string;
  email: string;
  preferredContact: string;
  availabilityNotes: string;
  careLevel: string;
  careLevelStatus: string;
  careLevelValidFrom: string;
  careFundName: string;
  careFundStreet: string;
  careFundZip: string;
  careFundCity: string;
  healthInsurance: string;
  healthInsuranceStreet: string;
  healthInsuranceZip: string;
  healthInsuranceCity: string;
  costBearerIk: string;
  healthInsuranceIk: string;
  insuranceNumber: string;
  billingTypes: string[];
  costBearerTypes: string[];
  selfPay: boolean;
  familyDoctor: string;
  consultingReason: string;
  consultingType: string;
  followUpDate: string;
  facilityName: string;
  facilityLocation: string;
  careArea: string;
  roomNumber: string;
  bedPosition: string;
  admissionDateStationary: string;
  residentStatus: string;
  roomStatus: string;
  primaryNurse: string;
  areaManager: string;
  costForm: string;
  mealNotes: string;
  dailyStructure: string;
  homeAccess: string;
  keyStatus: string;
  keyNumber: string;
  keySafeCode: string;
  doorCode: string;
  bellName: string;
  parkingNotes: string;
  accessNotes: string;
  hazardNotes: string;
  pets: string;
  smokerHousehold: boolean;
  aidsOnSite: string;
  hygieneNotes: string;
  infectionNotes: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  supportWishes: string[];
  preferredTimes: string[];
  excludedTimes: string[];
  mobility: string;
  orientation: string;
  communication: string;
  assignedModules: string[];
  consentDatenschutz: boolean;
  consentVertrag: boolean;
  consentTypes: string[];
  contractTypes: string[];
  documentCategories: string[];
  hourlyRate: string;
  taskCategories: string[];
};

export const EMPTY_CLIENT_INTAKE_FORM: ClientIntakeFormData = {
  careContexts: [],
  firstName: '',
  lastName: '',
  salutation: '',
  gender: '',
  dateOfBirth: '',
  birthPlace: '',
  nationality: 'DE',
  language: 'de',
  maritalStatus: '',
  housingForm: '',
  specialNotes: '',
  status: 'in_aufnahme',
  admissionDate: new Date().toISOString().slice(0, 10),
  serviceStart: '',
  street: '',
  houseNumber: '',
  zip: '',
  city: '',
  addressExtra: '',
  floor: '',
  elevatorAvailable: false,
  phone: '',
  mobile: '',
  email: '',
  preferredContact: '',
  availabilityNotes: '',
  careLevel: '',
  careLevelStatus: '',
  careLevelValidFrom: '',
  careFundName: '',
  careFundStreet: '',
  careFundZip: '',
  careFundCity: '',
  healthInsurance: '',
  healthInsuranceStreet: '',
  healthInsuranceZip: '',
  healthInsuranceCity: '',
  costBearerIk: '',
  healthInsuranceIk: '',
  insuranceNumber: '',
  billingTypes: [],
  costBearerTypes: [],
  selfPay: false,
  familyDoctor: '',
  consultingReason: '',
  consultingType: '',
  followUpDate: '',
  facilityName: '',
  facilityLocation: '',
  careArea: '',
  roomNumber: '',
  bedPosition: '',
  admissionDateStationary: '',
  residentStatus: '',
  roomStatus: '',
  primaryNurse: '',
  areaManager: '',
  costForm: '',
  mealNotes: '',
  dailyStructure: '',
  homeAccess: '',
  keyStatus: '',
  keyNumber: '',
  keySafeCode: '',
  doorCode: '',
  bellName: '',
  parkingNotes: '',
  accessNotes: '',
  hazardNotes: '',
  pets: '',
  smokerHousehold: false,
  aidsOnSite: '',
  hygieneNotes: '',
  infectionNotes: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  supportWishes: [],
  preferredTimes: [],
  excludedTimes: [],
  mobility: '',
  orientation: '',
  communication: '',
  assignedModules: ['office'],
  consentDatenschutz: false,
  consentVertrag: false,
  consentTypes: [],
  contractTypes: [],
  documentCategories: [],
  hourlyRate: '',
  taskCategories: [],
};

export type ClientIntakeErrors = Partial<Record<string, string>>;
