import type { ClientCareContext } from '@/lib/clients/clientIntakeFieldRules';
import type { IntakeDocumentState } from '@/features/intakeDocuments/intakeDocumentTypes';

export type ClientIntakeFormData = {
  careContexts: ClientCareContext[];
  firstName: string;
  lastName: string;
  salutation: string;
  gender: string;
  dateOfBirth: string;
  birthPlace: string;
  nationality: string;
  language: string;
  maritalStatus: string;
  housingForm: string;
  specialNotes: string;
  status: string;
  admissionDate: string;
  serviceStart: string;
  street: string;
  houseNumber: string;
  zip: string;
  city: string;
  addressExtra: string;
  floor: string;
  elevatorAvailable: boolean;
  phone: string;
  mobile: string;
  email: string;
  preferredContact: string;
  availabilityNotes: string;
  careLevel: string;
  careLevelStatus: string;
  careLevelValidFrom: string;
  careFundName: string;
  careFundStreet: string;
  careFundZip: string;
  careFundCity: string;
  healthInsurance: string;
  healthInsuranceStreet: string;
  healthInsuranceZip: string;
  healthInsuranceCity: string;
  costBearerIk: string;
  healthInsuranceIk: string;
  privatversicherungName: string;
  privatversicherungStreet: string;
  privatversicherungZip: string;
  privatversicherungCity: string;
  privatversicherungIk: string;
  sozialamtName: string;
  sozialamtStreet: string;
  sozialamtZip: string;
  sozialamtCity: string;
  sozialamtIk: string;
  beihilfeName: string;
  beihilfeStreet: string;
  beihilfeZip: string;
  beihilfeCity: string;
  selbstzahlerName: string;
  selbstzahlerStreet: string;
  selbstzahlerZip: string;
  selbstzahlerCity: string;
  berufsgenossenschaftName: string;
  berufsgenossenschaftStreet: string;
  berufsgenossenschaftZip: string;
  berufsgenossenschaftCity: string;
  berufsgenossenschaftIk: string;
  unfallversicherungName: string;
  unfallversicherungStreet: string;
  unfallversicherungZip: string;
  unfallversicherungCity: string;
  unfallversicherungIk: string;
  sonstigerName: string;
  sonstigerStreet: string;
  sonstigerZip: string;
  sonstigerCity: string;
  insuranceNumber: string;
  billingTypes: string[];
  costBearerTypes: string[];
  activeCostBearerType: string;
  costBearerTemplateIds: Partial<Record<string, string>>;
  costBearerDbTypes: Partial<Record<string, string>>;
  selfPay: boolean;
  familyDoctor: string;
  consultingReason: string;
  consultingType: string;
  followUpDate: string;
  facilityName: string;
  facilityLocation: string;
  careArea: string;
  roomNumber: string;
  bedPosition: string;
  admissionDateStationary: string;
  residentStatus: string;
  roomStatus: string;
  primaryNurse: string;
  areaManager: string;
  costForm: string;
  mealNotes: string;
  dailyStructure: string;
  homeAccess: string;
  keyStatus: string;
  keyNumber: string;
  keySafeCode: string;
  doorCode: string;
  bellName: string;
  parkingNotes: string;
  accessNotes: string;
  hazardNotes: string;
  pets: string;
  smokerHousehold: boolean;
  aidsOnSite: string;
  hygieneNotes: string;
  infectionNotes: string;
  emergencyContactName: string;
  emergencyContactPhone: string;
  supportWishes: string[];
  preferredTimes: string[];
  excludedTimes: string[];
  mobility: string;
  orientation: string;
  communication: string;
  assignedModules: string[];
  consentDatenschutz: boolean;
  consentVertrag: boolean;
  intakeContractType: string;
  intakeAssignmentEnabled: boolean;
  intakeOptionalConsents: string[];
  intakeDocuments: IntakeDocumentState[];
  consentTypes: string[];
  contractTypes: string[];
  documentCategories: string[];
  hourlyRate: string;
  taskCategories: string[];
};

export const EMPTY_CLIENT_INTAKE_FORM: ClientIntakeFormData = {
  careContexts: [],
  firstName: '',
  lastName: '',
  salutation: '',
  gender: '',
  dateOfBirth: '',
  birthPlace: '',
  nationality: 'DE',
  language: 'de',
  maritalStatus: '',
  housingForm: '',
  specialNotes: '',
  status: 'in_aufnahme',
  admissionDate: new Date().toISOString().slice(0, 10),
  serviceStart: '',
  street: '',
  houseNumber: '',
  zip: '',
  city: '',
  addressExtra: '',
  floor: '',
  elevatorAvailable: false,
  phone: '',
  mobile: '',
  email: '',
  preferredContact: '',
  availabilityNotes: '',
  careLevel: '',
  careLevelStatus: '',
  careLevelValidFrom: '',
  careFundName: '',
  careFundStreet: '',
  careFundZip: '',
  careFundCity: '',
  healthInsurance: '',
  healthInsuranceStreet: '',
  healthInsuranceZip: '',
  healthInsuranceCity: '',
  costBearerIk: '',
  healthInsuranceIk: '',
  privatversicherungName: '',
  privatversicherungStreet: '',
  privatversicherungZip: '',
  privatversicherungCity: '',
  privatversicherungIk: '',
  sozialamtName: '',
  sozialamtStreet: '',
  sozialamtZip: '',
  sozialamtCity: '',
  sozialamtIk: '',
  beihilfeName: '',
  beihilfeStreet: '',
  beihilfeZip: '',
  beihilfeCity: '',
  selbstzahlerName: '',
  selbstzahlerStreet: '',
  selbstzahlerZip: '',
  selbstzahlerCity: '',
  berufsgenossenschaftName: '',
  berufsgenossenschaftStreet: '',
  berufsgenossenschaftZip: '',
  berufsgenossenschaftCity: '',
  berufsgenossenschaftIk: '',
  unfallversicherungName: '',
  unfallversicherungStreet: '',
  unfallversicherungZip: '',
  unfallversicherungCity: '',
  unfallversicherungIk: '',
  sonstigerName: '',
  sonstigerStreet: '',
  sonstigerZip: '',
  sonstigerCity: '',
  insuranceNumber: '',
  billingTypes: [],
  costBearerTypes: [],
  activeCostBearerType: '',
  costBearerTemplateIds: {},
  costBearerDbTypes: {},
  selfPay: false,
  familyDoctor: '',
  consultingReason: '',
  consultingType: '',
  followUpDate: '',
  facilityName: '',
  facilityLocation: '',
  careArea: '',
  roomNumber: '',
  bedPosition: '',
  admissionDateStationary: '',
  residentStatus: '',
  roomStatus: '',
  primaryNurse: '',
  areaManager: '',
  costForm: '',
  mealNotes: '',
  dailyStructure: '',
  homeAccess: '',
  keyStatus: '',
  keyNumber: '',
  keySafeCode: '',
  doorCode: '',
  bellName: '',
  parkingNotes: '',
  accessNotes: '',
  hazardNotes: '',
  pets: '',
  smokerHousehold: false,
  aidsOnSite: '',
  hygieneNotes: '',
  infectionNotes: '',
  emergencyContactName: '',
  emergencyContactPhone: '',
  supportWishes: [],
  preferredTimes: [],
  excludedTimes: [],
  mobility: '',
  orientation: '',
  communication: '',
  assignedModules: ['office'],
  consentDatenschutz: false,
  consentVertrag: false,
  intakeContractType: '',
  intakeAssignmentEnabled: false,
  intakeOptionalConsents: [],
  intakeDocuments: [],
  consentTypes: [],
  contractTypes: [],
  documentCategories: [],
  hourlyRate: '',
  taskCategories: [],
};

export type ClientIntakeErrors = Partial<Record<string, string>>;
