-- entries
INSERT INTO public.catalog_entries (
  id, tenant_id, catalog_type, value_key, label, description, module_key, is_system, is_active, sort_order
) VALUES
('cat-client-st-001', NULL, 'client_status', 'aktiv', 'Aktiv', 'RegulÃ¤re Betreuung lÃ¤uft', 'office', true, true, 1),
('cat-client-st-002', NULL, 'client_status', 'aufnahme', 'Aufnahme', 'Aufnahmeprozess / Intake', 'office', true, true, 2),
('cat-client-st-003', NULL, 'client_status', 'warteliste', 'Warteliste', 'Wartet auf KapazitÃ¤t', 'office', true, true, 3),
('cat-client-st-004', NULL, 'client_status', 'neu', 'Neu angelegt', 'Stammdaten erfasst, noch nicht aktiv', 'office', true, true, 4),
('cat-client-st-005', NULL, 'client_status', 'entwurf', 'Entwurf', 'UnvollstÃ¤ndige Anlage', 'office', true, true, 5),
('cat-client-st-006', NULL, 'client_status', 'in_bearbeitung', 'In Bearbeitung', 'Unter KlÃ¤rung / Bearbeitung', 'office', true, true, 6),
('cat-client-st-007', NULL, 'client_status', 'wartet_auf_vertrag', 'Wartet auf Vertrag', 'Vertragsunterzeichnung ausstehend', 'office', true, true, 7),
('cat-client-st-008', NULL, 'client_status', 'pausiert', 'Pausiert', 'Leistungen vorÃ¼bergehend ausgesetzt', 'office', true, true, 8),
('cat-client-st-009', NULL, 'client_status', 'beurlaubt', 'Beurlaubt', 'TemporÃ¤re Beurlaubung', 'office', true, true, 9),
('cat-client-st-010', NULL, 'client_status', 'urlaub_abwesend', 'Abwesend', 'Klient:in vorÃ¼bergehend nicht erreichbar', 'office', true, true, 10),
('cat-client-st-011', NULL, 'client_status', 'kurzzeitpflege', 'Kurzzeitpflege', 'Kurzzeitpflege / Ãœbergang', 'office', true, true, 11),
('cat-client-st-012', NULL, 'client_status', 'nachsorge', 'Nachsorge', 'Nachsorgephase nach Entlassung', 'office', true, true, 12),
('cat-client-st-013', NULL, 'client_status', 'entlassung_geplant', 'Entlassung geplant', 'Entlassung vorbereitet', 'office', true, true, 13),
('cat-client-st-014', NULL, 'client_status', 'gesperrt', 'Gesperrt', 'Datensatz gesperrt', 'office', true, true, 14),
('cat-client-st-015', NULL, 'client_status', 'archiviert', 'Archiviert', 'Inaktiv / archiviert', 'office', true, true, 15),
('cat-client-st-016', NULL, 'client_status', 'verstorben', 'Verstorben', 'Trauerfall â€” Dokumentation abgeschlossen', 'office', true, true, 16),
('cat-emp-st-001', NULL, 'employee_status', 'aktiv', 'Aktiv', 'Im Einsatz', 'office', true, true, 1),
('cat-emp-st-002', NULL, 'employee_status', 'probezeit', 'Probezeit', 'Probezeit lÃ¤uft', 'office', true, true, 2),
('cat-emp-st-003', NULL, 'employee_status', 'einarbeitung', 'Einarbeitung', 'Einarbeitungsphase', 'office', true, true, 3),
('cat-emp-st-004', NULL, 'employee_status', 'urlaub', 'Im Urlaub', 'Genehmigter Urlaub', 'office', true, true, 4),
('cat-emp-st-005', NULL, 'employee_status', 'krank', 'Krankgemeldet', 'AU / Krankmeldung', 'office', true, true, 5),
('cat-emp-st-006', NULL, 'employee_status', 'elternzeit', 'Elternzeit', 'Elternzeit / Mutterschutz', 'office', true, true, 6),
('cat-emp-st-007', NULL, 'employee_status', 'fortbildung', 'Fortbildung', 'Schulung / Fortbildung', 'office', true, true, 7),
('cat-emp-st-008', NULL, 'employee_status', 'teilzeit', 'Teilzeit', 'Reduzierte Arbeitszeit', 'office', true, true, 8),
('cat-emp-st-009', NULL, 'employee_status', 'freigestellt', 'Freigestellt', 'VorÃ¼bergehend freigestellt', 'office', true, true, 9),
('cat-emp-st-010', NULL, 'employee_status', 'kuendigung_laeuft', 'KÃ¼ndigung lÃ¤uft', 'KÃ¼ndigungsfrist', 'office', true, true, 10),
('cat-emp-st-011', NULL, 'employee_status', 'ausgeschieden', 'Ausgeschieden', 'Nicht mehr im Unternehmen', 'office', true, true, 11),
('cat-emp-st-012', NULL, 'employee_status', 'gesperrt', 'Gesperrt', 'Zugang gesperrt', 'office', true, true, 12),
('cat-emp-st-013', NULL, 'employee_status', 'archiviert', 'Archiviert', 'Archivierter Datensatz', 'office', true, true, 13),
('cat-asg-st-001', NULL, 'assignment_status', 'geplant', 'Geplant', 'Einsatz geplant', 'assist', true, true, 1),
('cat-asg-st-002', NULL, 'assignment_status', 'bestaetigt', 'BestÃ¤tigt', 'Vom Team bestÃ¤tigt', 'assist', true, true, 2),
('cat-asg-st-003', NULL, 'assignment_status', 'zugewiesen', 'Zugewiesen', 'Mitarbeiter:in zugewiesen', 'assist', true, true, 3),
('cat-asg-st-004', NULL, 'assignment_status', 'unterwegs', 'Unterwegs', 'Anfahrt zum Einsatz', 'assist', true, true, 4),
('cat-asg-st-005', NULL, 'assignment_status', 'eingetroffen', 'Eingetroffen', 'Vor Ort eingetroffen', 'assist', true, true, 5),
('cat-asg-st-006', NULL, 'assignment_status', 'in_ausfuehrung', 'In AusfÃ¼hrung', 'Leistung wird erbracht', 'assist', true, true, 6),
('cat-asg-st-007', NULL, 'assignment_status', 'unterbrochen', 'Unterbrochen', 'Einsatz unterbrochen', 'assist', true, true, 7),
('cat-asg-st-008', NULL, 'assignment_status', 'abgeschlossen', 'Abgeschlossen', 'Leistung abgeschlossen', 'assist', true, true, 8),
('cat-asg-st-009', NULL, 'assignment_status', 'dokumentiert', 'Dokumentiert', 'Dokumentation erfasst', 'assist', true, true, 9),
('cat-asg-st-010', NULL, 'assignment_status', 'abgerechnet', 'Abgerechnet', 'Abrechnung erfolgt', 'assist', true, true, 10),
('cat-asg-st-011', NULL, 'assignment_status', 'nicht_erledigt', 'Nicht erledigt', 'Einsatz nicht durchgefÃ¼hrt', 'assist', true, true, 11),
('cat-asg-st-012', NULL, 'assignment_status', 'abgesagt_klient', 'Abgesagt (Klient:in)', 'Absage durch Klient:in', 'assist', true, true, 12),
('cat-asg-st-013', NULL, 'assignment_status', 'abgesagt_team', 'Abgesagt (Team)', 'Absage durch Team', 'assist', true, true, 13),
('cat-asg-st-014', NULL, 'assignment_status', 'verschoben', 'Verschoben', 'Termin verschoben', 'assist', true, true, 14),
('cat-asg-st-015', NULL, 'assignment_status', 'ersatz_einsatz', 'Ersatzeinsatz', 'Ersatz durch andere Person', 'assist', true, true, 15),
('cat-asg-st-016', NULL, 'assignment_status', 'qualitaetspruefung', 'QualitÃ¤tsprÃ¼fung', 'In QualitÃ¤tsprÃ¼fung', 'assist', true, true, 16),
('cat-asg-st-017', NULL, 'assignment_status', 'reklamation', 'Reklamation', 'Reklamation offen', 'assist', true, true, 17),
('cat-asg-st-018', NULL, 'assignment_status', 'storniert', 'Storniert', 'Storniert', 'assist', true, true, 18),
('cat-asg-st-019', NULL, 'assignment_status', 'archiviert', 'Archiviert', 'Archiviert', 'assist', true, true, 19),
('cat-doc-st-001', NULL, 'document_status', 'entwurf', 'Entwurf', 'Noch nicht finalisiert', 'documents', true, true, 1),
('cat-doc-st-002', NULL, 'document_status', 'hochgeladen', 'Hochgeladen', 'Datei hochgeladen', 'documents', true, true, 2),
('cat-doc-st-003', NULL, 'document_status', 'in_pruefung', 'In PrÃ¼fung', 'Wird geprÃ¼ft', 'documents', true, true, 3),
('cat-doc-st-004', NULL, 'document_status', 'freigegeben', 'Freigegeben', 'Freigegeben zur Nutzung', 'documents', true, true, 4),
('cat-doc-st-005', NULL, 'document_status', 'signiert', 'Signiert', 'Unterschrieben / signiert', 'documents', true, true, 5),
('cat-doc-st-006', NULL, 'document_status', 'versendet', 'Versendet', 'An EmpfÃ¤nger versendet', 'documents', true, true, 6),
('cat-doc-st-007', NULL, 'document_status', 'abgelaufen', 'Abgelaufen', 'GÃ¼ltigkeit abgelaufen', 'documents', true, true, 7),
('cat-doc-st-008', NULL, 'document_status', 'ersetzt', 'Ersetzt', 'Durch neuere Version ersetzt', 'documents', true, true, 8),
('cat-doc-st-009', NULL, 'document_status', 'gesperrt', 'Gesperrt', 'Zugriff gesperrt', 'documents', true, true, 9),
('cat-doc-st-010', NULL, 'document_status', 'archiviert', 'Archiviert', 'Archiviert', 'documents', true, true, 10),
('cat-inv-st-001', NULL, 'invoice_status', 'entwurf', 'Entwurf', 'Rechnungsentwurf', 'billing', true, true, 1),
('cat-inv-st-002', NULL, 'invoice_status', 'geprueft', 'GeprÃ¼ft', 'Intern geprÃ¼ft', 'billing', true, true, 2),
('cat-inv-st-003', NULL, 'invoice_status', 'freigegeben', 'Freigegeben', 'Zur Versendung freigegeben', 'billing', true, true, 3),
('cat-inv-st-004', NULL, 'invoice_status', 'versendet', 'Versendet', 'An KostentrÃ¤ger versendet', 'billing', true, true, 4),
('cat-inv-st-005', NULL, 'invoice_status', 'teilbezahlt', 'Teilbezahlt', 'Teilzahlung eingegangen', 'billing', true, true, 5),
('cat-inv-st-006', NULL, 'invoice_status', 'bezahlt', 'Bezahlt', 'VollstÃ¤ndig bezahlt', 'billing', true, true, 6),
('cat-inv-st-007', NULL, 'invoice_status', 'ueberfaellig', 'ÃœberfÃ¤llig', 'Zahlungsziel Ã¼berschritten', 'billing', true, true, 7),
('cat-inv-st-008', NULL, 'invoice_status', 'gemahnt', 'Gemahnt', 'Mahnverfahren lÃ¤uft', 'billing', true, true, 8),
('cat-inv-st-009', NULL, 'invoice_status', 'storniert', 'Storniert', 'Storniert', 'billing', true, true, 9),
('cat-inv-st-010', NULL, 'invoice_status', 'gutschrift', 'Gutschrift', 'Gutschrift erstellt', 'billing', true, true, 10),
('cat-inv-st-011', NULL, 'invoice_status', 'abgelehnt', 'Abgelehnt', 'Von KostentrÃ¤ger abgelehnt', 'billing', true, true, 11),
('cat-inv-st-012', NULL, 'invoice_status', 'archiviert', 'Archiviert', 'Archiviert', 'billing', true, true, 12),
('cat-msg-st-001', NULL, 'message_status', 'entwurf', 'Entwurf', 'Nachricht als Entwurf', 'communication', true, true, 1),
('cat-msg-st-002', NULL, 'message_status', 'geplant', 'Geplant', 'Versand geplant', 'communication', true, true, 2),
('cat-msg-st-003', NULL, 'message_status', 'in_warteschlange', 'In Warteschlange', 'Wartet auf Versand', 'communication', true, true, 3),
('cat-msg-st-004', NULL, 'message_status', 'gesendet', 'Gesendet', 'Erfolgreich gesendet', 'communication', true, true, 4),
('cat-msg-st-005', NULL, 'message_status', 'zugestellt', 'Zugestellt', 'Beim EmpfÃ¤nger angekommen', 'communication', true, true, 5),
('cat-msg-st-006', NULL, 'message_status', 'gelesen', 'Gelesen', 'Vom EmpfÃ¤nger gelesen', 'communication', true, true, 6),
('cat-msg-st-007', NULL, 'message_status', 'beantwortet', 'Beantwortet', 'Antwort erhalten', 'communication', true, true, 7),
('cat-msg-st-008', NULL, 'message_status', 'fehlgeschlagen', 'Fehlgeschlagen', 'Versand fehlgeschlagen', 'communication', true, true, 8),
('cat-msg-st-009', NULL, 'message_status', 'zurueckgezogen', 'ZurÃ¼ckgezogen', 'Nachricht zurÃ¼ckgezogen', 'communication', true, true, 9),
('cat-msg-st-010', NULL, 'message_status', 'archiviert', 'Archiviert', 'Archiviert', 'communication', true, true, 10),
('cat-doc-client-001', NULL, 'document_category', 'client_01', 'Pflegevertrag', 'Dokumentkategorie: Pflegevertrag', 'office', true, true, 1),
('cat-doc-client-002', NULL, 'document_category', 'client_02', 'Leistungsvereinbarung', 'Dokumentkategorie: Leistungsvereinbarung', 'office', true, true, 2),
('cat-doc-client-003', NULL, 'document_category', 'client_03', 'Einwilligung Datenschutz', 'Dokumentkategorie: Einwilligung Datenschutz', 'office', true, true, 3),
('cat-doc-client-004', NULL, 'document_category', 'client_04', 'Einwilligung Foto/Video', 'Dokumentkategorie: Einwilligung Foto/Video', 'office', true, true, 4),
('cat-doc-client-005', NULL, 'document_category', 'client_05', 'Vollmacht AngehÃ¶rige', 'Dokumentkategorie: Vollmacht AngehÃ¶rige', 'office', true, true, 5),
('cat-doc-client-006', NULL, 'document_category', 'client_06', 'Arztbrief', 'Dokumentkategorie: Arztbrief', 'office', true, true, 6),
('cat-doc-client-007', NULL, 'document_category', 'client_07', 'Entlassungsbericht', 'Dokumentkategorie: Entlassungsbericht', 'office', true, true, 7),
('cat-doc-client-008', NULL, 'document_category', 'client_08', 'Medikationsplan', 'Dokumentkategorie: Medikationsplan', 'office', true, true, 8),
('cat-doc-client-009', NULL, 'document_category', 'client_09', 'Pflegegradbescheid', 'Dokumentkategorie: Pflegegradbescheid', 'office', true, true, 9),
('cat-doc-client-010', NULL, 'document_category', 'client_10', 'MD-Bericht', 'Dokumentkategorie: MD-Bericht', 'office', true, true, 10),
('cat-doc-client-011', NULL, 'document_category', 'client_11', 'Wunddokumentation', 'Dokumentkategorie: Wunddokumentation', 'office', true, true, 11),
('cat-doc-client-012', NULL, 'document_category', 'client_12', 'Vitalwerte-Protokoll', 'Dokumentkategorie: Vitalwerte-Protokoll', 'office', true, true, 12),
('cat-doc-client-013', NULL, 'document_category', 'client_13', 'Pflegeplan', 'Dokumentkategorie: Pflegeplan', 'office', true, true, 13),
('cat-doc-client-014', NULL, 'document_category', 'client_14', 'SIS-Assessment', 'Dokumentkategorie: SIS-Assessment', 'office', true, true, 14),
('cat-doc-client-015', NULL, 'document_category', 'client_15', 'Risikoanalyse', 'Dokumentkategorie: Risikoanalyse', 'office', true, true, 15),
('cat-doc-client-016', NULL, 'document_category', 'client_16', 'Notfallplan', 'Dokumentkategorie: Notfallplan', 'office', true, true, 16),
('cat-doc-client-017', NULL, 'document_category', 'client_17', 'Kostenvoranschlag', 'Dokumentkategorie: Kostenvoranschlag', 'office', true, true, 17),
('cat-doc-client-018', NULL, 'document_category', 'client_18', 'Abrechnungsunterlage', 'Dokumentkategorie: Abrechnungsunterlage', 'office', true, true, 18),
('cat-doc-client-019', NULL, 'document_category', 'client_19', 'Korrespondenz Krankenkasse', 'Dokumentkategorie: Korrespondenz Krankenkasse', 'office', true, true, 19),
('cat-doc-client-020', NULL, 'document_category', 'client_20', 'AngehÃ¶rigeninfo', 'Dokumentkategorie: AngehÃ¶rigeninfo', 'office', true, true, 20),
('cat-doc-client-021', NULL, 'document_category', 'client_21', 'Transportgenehmigung', 'Dokumentkategorie: Transportgenehmigung', 'office', true, true, 21),
('cat-doc-client-022', NULL, 'document_category', 'client_22', 'BetreuungsverfÃ¼gung', 'Dokumentkategorie: BetreuungsverfÃ¼gung', 'office', true, true, 22),
('cat-doc-client-023', NULL, 'document_category', 'client_23', 'PatientenverfÃ¼gung', 'Dokumentkategorie: PatientenverfÃ¼gung', 'office', true, true, 23),
('cat-doc-client-024', NULL, 'document_category', 'client_24', 'Vorsorgevollmacht', 'Dokumentkategorie: Vorsorgevollmacht', 'office', true, true, 24),
('cat-doc-client-025', NULL, 'document_category', 'client_25', 'Sonstiges Klientendokument', 'Dokumentkategorie: Sonstiges Klientendokument', 'office', true, true, 25),
('cat-doc-client-026', NULL, 'document_category', 'client_26', 'Archiv Klientendokument', 'Dokumentkategorie: Archiv Klientendokument', 'office', true, true, 26),
('cat-doc-employee-001', NULL, 'document_category', 'employee_01', 'Arbeitsvertrag', 'Dokumentkategorie: Arbeitsvertrag', 'office', true, true, 1),
('cat-doc-employee-002', NULL, 'document_category', 'employee_02', 'NebentÃ¤tigkeitserklÃ¤rung', 'Dokumentkategorie: NebentÃ¤tigkeitserklÃ¤rung', 'office', true, true, 2),
('cat-doc-employee-003', NULL, 'document_category', 'employee_03', 'Schweigepflicht', 'Dokumentkategorie: Schweigepflicht', 'office', true, true, 3),
('cat-doc-employee-004', NULL, 'document_category', 'employee_04', 'Datenschutz Mitarbeiter', 'Dokumentkategorie: Datenschutz Mitarbeiter', 'office', true, true, 4),
('cat-doc-employee-005', NULL, 'document_category', 'employee_05', 'FÃ¼hrungszeugnis', 'Dokumentkategorie: FÃ¼hrungszeugnis', 'office', true, true, 5),
('cat-doc-employee-006', NULL, 'document_category', 'employee_06', 'Erste-Hilfe-Nachweis', 'Dokumentkategorie: Erste-Hilfe-Nachweis', 'office', true, true, 6),
('cat-doc-employee-007', NULL, 'document_category', 'employee_07', 'Impfpass / Masernschutz', 'Dokumentkategorie: Impfpass / Masernschutz', 'office', true, true, 7),
('cat-doc-employee-008', NULL, 'document_category', 'employee_08', 'Fortbildungsnachweis', 'Dokumentkategorie: Fortbildungsnachweis', 'office', true, true, 8),
('cat-doc-employee-009', NULL, 'document_category', 'employee_09', 'Hygiene-Schulung', 'Dokumentkategorie: Hygiene-Schulung', 'office', true, true, 9),
('cat-doc-employee-010', NULL, 'document_category', 'employee_10', 'Fahrerlaubnis', 'Dokumentkategorie: Fahrerlaubnis', 'office', true, true, 10),
('cat-doc-employee-011', NULL, 'document_category', 'employee_11', 'Fahrzeugnutzung', 'Dokumentkategorie: Fahrzeugnutzung', 'office', true, true, 11),
('cat-doc-employee-012', NULL, 'document_category', 'employee_12', 'Dienstkleidung', 'Dokumentkategorie: Dienstkleidung', 'office', true, true, 12),
('cat-doc-employee-013', NULL, 'document_category', 'employee_13', 'Zeiterfassung', 'Dokumentkategorie: Zeiterfassung', 'office', true, true, 13),
('cat-doc-employee-014', NULL, 'document_category', 'employee_14', 'Urlaubsantrag', 'Dokumentkategorie: Urlaubsantrag', 'office', true, true, 14),
('cat-doc-employee-015', NULL, 'document_category', 'employee_15', 'Krankmeldung', 'Dokumentkategorie: Krankmeldung', 'office', true, true, 15),
('cat-doc-employee-016', NULL, 'document_category', 'employee_16', 'Beurteilung', 'Dokumentkategorie: Beurteilung', 'office', true, true, 16),
('cat-doc-employee-017', NULL, 'document_category', 'employee_17', 'Einarbeitungsplan', 'Dokumentkategorie: Einarbeitungsplan', 'office', true, true, 17),
('cat-doc-employee-018', NULL, 'document_category', 'employee_18', 'Qualifikationsnachweis', 'Dokumentkategorie: Qualifikationsnachweis', 'office', true, true, 18),
('cat-doc-employee-019', NULL, 'document_category', 'employee_19', 'PersÃ¶nliche Dokumente', 'Dokumentkategorie: PersÃ¶nliche Dokumente', 'office', true, true, 19),
('cat-doc-employee-020', NULL, 'document_category', 'employee_20', 'Notfallkontakt MA', 'Dokumentkategorie: Notfallkontakt MA', 'office', true, true, 20),
('cat-doc-employee-021', NULL, 'document_category', 'employee_21', 'Sonstiges Mitarbeiterdokument', 'Dokumentkategorie: Sonstiges Mitarbeiterdokument', 'office', true, true, 21),
('cat-doc-office-001', NULL, 'document_category', 'office_01', 'Allgemeine Korrespondenz', 'Dokumentkategorie: Allgemeine Korrespondenz', 'office', true, true, 1),
('cat-doc-office-002', NULL, 'document_category', 'office_02', 'Vertragsvorlage', 'Dokumentkategorie: Vertragsvorlage', 'office', true, true, 2),
('cat-doc-office-003', NULL, 'document_category', 'office_03', 'Rechnungsvorlage', 'Dokumentkategorie: Rechnungsvorlage', 'office', true, true, 3),
('cat-doc-office-004', NULL, 'document_category', 'office_04', 'Mahnungsvorlage', 'Dokumentkategorie: Mahnungsvorlage', 'office', true, true, 4),
('cat-doc-office-005', NULL, 'document_category', 'office_05', 'Formular Intake', 'Dokumentkategorie: Formular Intake', 'office', true, true, 5),
('cat-doc-office-006', NULL, 'document_category', 'office_06', 'Formular Entlassung', 'Dokumentkategorie: Formular Entlassung', 'office', true, true, 6),
('cat-doc-office-007', NULL, 'document_category', 'office_07', 'QM-Handbuch Auszug', 'Dokumentkategorie: QM-Handbuch Auszug', 'office', true, true, 7),
('cat-doc-office-008', NULL, 'document_category', 'office_08', 'Datenschutzkonzept', 'Dokumentkategorie: Datenschutzkonzept', 'office', true, true, 8),
('cat-doc-office-009', NULL, 'document_category', 'office_09', 'Brandschutzplan', 'Dokumentkategorie: Brandschutzplan', 'office', true, true, 9),
('cat-doc-office-010', NULL, 'document_category', 'office_10', 'Hygieneplan', 'Dokumentkategorie: Hygieneplan', 'office', true, true, 10),
('cat-doc-office-011', NULL, 'document_category', 'office_11', 'Dienstplan Vorlage', 'Dokumentkategorie: Dienstplan Vorlage', 'office', true, true, 11),
('cat-doc-office-012', NULL, 'document_category', 'office_12', 'Einsatzplan Vorlage', 'Dokumentkategorie: Einsatzplan Vorlage', 'office', true, true, 12),
('cat-doc-office-013', NULL, 'document_category', 'office_13', 'Checkliste BÃ¼ro', 'Dokumentkategorie: Checkliste BÃ¼ro', 'office', true, true, 13),
('cat-doc-office-014', NULL, 'document_category', 'office_14', 'Protokoll Besprechung', 'Dokumentkategorie: Protokoll Besprechung', 'office', true, true, 14),
('cat-doc-office-015', NULL, 'document_category', 'office_15', 'Protokoll QM-Runde', 'Dokumentkategorie: Protokoll QM-Runde', 'office', true, true, 15),
('cat-doc-office-016', NULL, 'document_category', 'office_16', 'Sonstiges BÃ¼rodokument', 'Dokumentkategorie: Sonstiges BÃ¼rodokument', 'office', true, true, 16),
('cat-doc-comm-001', NULL, 'document_category', 'comm_01', 'Portal-Nachricht Anhang', 'Dokumentkategorie: Portal-Nachricht Anhang', 'communication', true, true, 1),
('cat-doc-comm-002', NULL, 'document_category', 'comm_02', 'E-Mail Anhang', 'Dokumentkategorie: E-Mail Anhang', 'communication', true, true, 2),
('cat-doc-comm-003', NULL, 'document_category', 'comm_03', 'KIM-Nachricht Anhang', 'Dokumentkategorie: KIM-Nachricht Anhang', 'communication', true, true, 3),
('cat-doc-comm-004', NULL, 'document_category', 'comm_04', 'SMS-Protokoll', 'Dokumentkategorie: SMS-Protokoll', 'communication', true, true, 4),
('cat-doc-comm-005', NULL, 'document_category', 'comm_05', 'AngehÃ¶rigenbrief', 'Dokumentkategorie: AngehÃ¶rigenbrief', 'communication', true, true, 5),
('cat-doc-comm-006', NULL, 'document_category', 'comm_06', 'Einladung Veranstaltung', 'Dokumentkategorie: Einladung Veranstaltung', 'communication', true, true, 6),
('cat-doc-comm-007', NULL, 'document_category', 'comm_07', 'TerminbestÃ¤tigung Schriftverkehr', 'Dokumentkategorie: TerminbestÃ¤tigung Schriftverkehr', 'communication', true, true, 7),
('cat-doc-comm-008', NULL, 'document_category', 'comm_08', 'Informationsblatt', 'Dokumentkategorie: Informationsblatt', 'communication', true, true, 8),
('cat-doc-comm-009', NULL, 'document_category', 'comm_09', 'Newsletter', 'Dokumentkategorie: Newsletter', 'communication', true, true, 9),
('cat-doc-comm-010', NULL, 'document_category', 'comm_10', 'Sonstiges Kommunikationsdokument', 'Dokumentkategorie: Sonstiges Kommunikationsdokument', 'communication', true, true, 10),
('cat-upload-001', NULL, 'upload_category', 'einwilligung', 'Einwilligung', 'EinwilligungserklÃ¤rungen', 'office', true, true, 1),
('cat-upload-002', NULL, 'upload_category', 'vertrag', 'Vertrag', 'Vertragsdokumente', 'office', true, true, 2),
('cat-upload-003', NULL, 'upload_category', 'arztbrief', 'Arztbrief', 'Medizinische Unterlagen', 'office', true, true, 3),
('cat-upload-004', NULL, 'upload_category', 'rechnung', 'Rechnung', 'Rechnungsbelege', 'office', true, true, 4),
('cat-upload-005', NULL, 'upload_category', 'leistungsnachweis', 'Leistungsnachweis', 'Nachweise erbrachter Leistungen', 'office', true, true, 5),
('cat-upload-006', NULL, 'upload_category', 'pflegeplan', 'Pflegeplan', 'Pflegeplanung', 'office', true, true, 6),
('cat-upload-007', NULL, 'upload_category', 'sis', 'SIS / Assessment', 'Strukturierte EinschÃ¤tzung', 'office', true, true, 7),
('cat-upload-008', NULL, 'upload_category', 'foto', 'Foto / Bild', 'Bilddokumentation', 'office', true, true, 8),
('cat-upload-009', NULL, 'upload_category', 'identitaet', 'IdentitÃ¤tsnachweis', 'Ausweis / Legitimation', 'office', true, true, 9),
('cat-upload-010', NULL, 'upload_category', 'versicherung', 'Versicherungsnachweis', 'Kranken-/Pflegekasse', 'office', true, true, 10),
('cat-upload-011', NULL, 'upload_category', 'vollmacht', 'Vollmacht', 'BevollmÃ¤chtigung', 'office', true, true, 11),
('cat-upload-012', NULL, 'upload_category', 'beratung', 'Beratungsunterlage', 'Beratungsdokumentation', 'office', true, true, 12),
('cat-upload-013', NULL, 'upload_category', 'portal', 'Portal-Upload', 'Vom Portal hochgeladen', 'office', true, true, 13),
('cat-upload-014', NULL, 'upload_category', 'scan', 'Scan / OCR', 'Eingescanntes Dokument', 'office', true, true, 14),
('cat-upload-015', NULL, 'upload_category', 'intern', 'Intern', 'Interne Unterlagen', 'office', true, true, 15),
('cat-upload-016', NULL, 'upload_category', 'sonstiges', 'Sonstiges', 'Nicht zugeordnet', 'office', true, true, 16),
('cat-asg-target-001', NULL, 'assignment_target', 'klient_akte', 'Klient:innen-Akte', 'Direkt in Klientenakte', 'assist', true, true, 1),
('cat-asg-target-002', NULL, 'assignment_target', 'einsatz_doku', 'Einsatzdokumentation', 'An Einsatz gebunden', 'assist', true, true, 2),
('cat-asg-target-003', NULL, 'assignment_target', 'pflegeplan', 'Pflegeplan', 'An Pflegeplan angehÃ¤ngt', 'assist', true, true, 3),
('cat-asg-target-004', NULL, 'assignment_target', 'rechnung', 'Rechnung', 'An Rechnung angehÃ¤ngt', 'assist', true, true, 4),
('cat-asg-target-005', NULL, 'assignment_target', 'mitarbeiter_akte', 'Mitarbeiter:innen-Akte', 'Personalakte', 'assist', true, true, 5),
('cat-asg-target-006', NULL, 'assignment_target', 'beratung_akte', 'Beratungsakte', 'Beratungsfall', 'assist', true, true, 6),
('cat-asg-target-007', NULL, 'assignment_target', 'portal_sichtbar', 'Portal (sichtbar)', 'FÃ¼r Portal freigegeben', 'assist', true, true, 7),
('cat-asg-target-008', NULL, 'assignment_target', 'portal_intern', 'Portal (intern)', 'Nur intern sichtbar', 'assist', true, true, 8),
('cat-asg-target-009', NULL, 'assignment_target', 'kim_anhang', 'KIM-Anhang', 'TI/KIM Nachricht', 'assist', true, true, 9),
('cat-asg-target-010', NULL, 'assignment_target', 'qm_nachweis', 'QM-Nachweis', 'QualitÃ¤tsmanagement', 'assist', true, true, 10),
('cat-asg-target-011', NULL, 'assignment_target', 'archiv', 'Archiv', 'Langzeitarchiv', 'assist', true, true, 11),
('cat-task-001', NULL, 'task_category', 'haushalt', 'Haushalt', NULL, 'assist', true, true, 1),
('cat-task-002', NULL, 'task_category', 'waesche', 'WÃ¤sche', NULL, 'assist', true, true, 2),
('cat-task-003', NULL, 'task_category', 'einkauf', 'Einkauf', NULL, 'assist', true, true, 3),
('cat-task-004', NULL, 'task_category', 'koerperpflege', 'KÃ¶rperpflege', NULL, 'assist', true, true, 4),
('cat-task-005', NULL, 'task_category', 'begleitung', 'Begleitung', NULL, 'assist', true, true, 5),
('cat-sis-001', NULL, 'sis_topic', 'mobilitaet', 'MobilitÃ¤t', NULL, 'pflege', true, true, 1),
('cat-sis-002', NULL, 'sis_topic', 'kognition', 'Kognition', NULL, 'pflege', true, true, 2),
('cat-sis-003', NULL, 'sis_topic', 'selbstversorgung', 'Selbstversorgung', NULL, 'pflege', true, true, 3),
('cat-risk-001', NULL, 'care_risk_type', 'sturz', 'Sturzrisiko', NULL, 'pflege', true, true, 1),
('cat-risk-002', NULL, 'care_risk_type', 'dekubitus', 'Dekubitusrisiko', NULL, 'pflege', true, true, 2),
('cat-counsel-001', NULL, 'counseling_topic', 'pflegegrad', 'Pflegegrad', NULL, 'beratung', true, true, 1),
('cat-counsel-002', NULL, 'counseling_topic', 'entlastung', 'Entlastungsleistungen', NULL, 'beratung', true, true, 2),
('cat-acad-001', NULL, 'academy_course_type', 'mandatory', 'Pflichtschulung', NULL, 'akademie', true, true, 1),
('cat-acad-002', NULL, 'academy_course_type', 'advanced', 'Fortbildung', NULL, 'akademie', true, true, 2),
('cat-consent-001', NULL, 'consent_type', 'datenschutz', 'Datenschutz', NULL, 'office', true, true, 1),
('cat-consent-002', NULL, 'consent_type', 'foto', 'Foto-Einwilligung', NULL, 'office', true, true, 2),
('cat-bill-001', NULL, 'billing_item_type', 'sgb_xi', 'SGB XI Leistung', NULL, 'billing', true, true, 1),
('cat-bill-002', NULL, 'billing_item_type', 'privat', 'Privatleistung', NULL, 'billing', true, true, 2),
('cat-msg-cat-001', NULL, 'message_category', 'intern', 'Intern', NULL, 'communication', true, true, 1),
('cat-msg-cat-002', NULL, 'message_category', 'portal', 'Portal', NULL, 'communication', true, true, 2),
('cat-msg-cat-003', NULL, 'message_category', 'angehoerige', 'AngehÃ¶rige', NULL, 'communication', true, true, 3)
ON CONFLICT (id) DO NOTHING;
