import type { SystemCatalog, SystemCatalogEntry, SystemCatalogKey } from './systemCatalog.types';

function entries(items: [string, string][]): SystemCatalogEntry[] {
  return items.map(([key, label], i) => ({ key, label, sortOrder: i }));
}

export const SYSTEM_CATALOGS: Record<SystemCatalogKey, SystemCatalog> = {
  leistungsart: {
    key: 'leistungsart',
    label: 'Leistungsart / Klient:innenart',
    entries: entries([
      ['daily_assistance', 'Alltagsbegleitung'],
      ['support_care', 'Betreuung'],
      ['companionship', 'Begleitung'],
      ['ambulatory_care', 'Ambulante Pflege'],
      ['stationary_care', 'Stationäre Pflege'],
      ['consulting', 'Beratung'],
      ['academy_prepared', 'Akademie / Schulung vorbereitet'],
    ]),
  },
  client_status: {
    key: 'client_status',
    label: 'Status Klient:in',
    entries: entries([
      ['interessent', 'Interessent:in'],
      ['in_aufnahme', 'In Aufnahme'],
      ['aktiv', 'Aktiv'],
      ['pausiert', 'Pausiert'],
      ['warteliste', 'Warteliste'],
      ['kurzzeitversorgung', 'Kurzzeitversorgung'],
      ['abgeschlossen', 'Abgeschlossen'],
      ['verstorben', 'Verstorben'],
      ['archiviert', 'Archiviert'],
      ['gesperrt', 'Gesperrt'],
    ]),
  },
  salutation: {
    key: 'salutation',
    label: 'Anrede',
    entries: entries([
      ['frau', 'Frau'],
      ['herr', 'Herr'],
      ['divers', 'Divers'],
      ['keine_angabe', 'Keine Angabe'],
      ['familie', 'Familie'],
      ['eheleute', 'Eheleute'],
      ['firma', 'Firma / Einrichtung'],
    ]),
  },
  gender: {
    key: 'gender',
    label: 'Geschlecht',
    entries: entries([
      ['weiblich', 'weiblich'],
      ['maennlich', 'männlich'],
      ['divers', 'divers'],
      ['unbekannt', 'unbekannt'],
      ['keine_angabe', 'keine Angabe'],
    ]),
  },
  marital_status: {
    key: 'marital_status',
    label: 'Familienstand',
    entries: entries([
      ['ledig', 'ledig'],
      ['verheiratet', 'verheiratet'],
      ['verwitwet', 'verwitwet'],
      ['geschieden', 'geschieden'],
      ['getrennt', 'getrennt lebend'],
      ['lebenspartnerschaft', 'eingetragene Lebenspartnerschaft'],
      ['unbekannt', 'unbekannt'],
      ['keine_angabe', 'keine Angabe'],
    ]),
  },
  housing_form: {
    key: 'housing_form',
    label: 'Wohnform',
    entries: entries([
      ['eigene_wohnung', 'Eigene Wohnung'],
      ['eigenes_haus', 'Eigenes Haus'],
      ['betreutes_wohnen', 'Betreutes Wohnen'],
      ['wohngemeinschaft', 'Wohngemeinschaft'],
      ['seniorenwohnung', 'Seniorenwohnung'],
      ['stationaer', 'Stationäre Einrichtung'],
      ['kurzzeitpflege', 'Kurzzeitpflege'],
      ['tagespflege', 'Tagespflege'],
      ['bei_angehoerigen', 'Bei Angehörigen'],
      ['ohne_angabe', 'Ohne feste Angabe'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  contact_method: {
    key: 'contact_method',
    label: 'Kontaktweg',
    entries: entries([
      ['telefon', 'Telefon'],
      ['mobil', 'Mobiltelefon'],
      ['email', 'E-Mail'],
      ['brief', 'Brief'],
      ['portal', 'Portal'],
      ['angehoerige', 'Angehörige kontaktieren'],
      ['betreuung', 'Betreuung kontaktieren'],
      ['whatsapp_prepared', 'WhatsApp vorbereitet'],
      ['keine', 'Keine Präferenz'],
    ]),
  },
  contact_relationship: {
    key: 'contact_relationship',
    label: 'Beziehung',
    entries: entries([
      ['ehepartner', 'Ehepartner:in'],
      ['lebenspartner', 'Lebenspartner:in'],
      ['sohn', 'Sohn'],
      ['tochter', 'Tochter'],
      ['mutter', 'Mutter'],
      ['vater', 'Vater'],
      ['bruder', 'Bruder'],
      ['schwester', 'Schwester'],
      ['enkel', 'Enkel:in'],
      ['nichte_neffe', 'Nichte / Neffe'],
      ['betreuung', 'gesetzliche Betreuung'],
      ['bevollmaechtigt', 'Bevollmächtigte:r'],
      ['nachbar', 'Nachbar:in'],
      ['freund', 'Freund:in'],
      ['hausarzt', 'Hausarzt'],
      ['pflegedienst', 'Pflegedienst'],
      ['sonstige', 'sonstige Kontaktperson'],
    ]),
  },
  contact_role: {
    key: 'contact_role',
    label: 'Kontaktrolle / Berechtigung',
    entries: entries([
      ['notfall', 'Notfallkontakt'],
      ['hauptkontakt', 'Hauptkontakt'],
      ['rechnung', 'Rechnungskontakt'],
      ['auskunft', 'Auskunftsberechtigt'],
      ['unterschrift', 'Unterschriftsberechtigt'],
      ['bevollmaechtigt', 'Bevollmächtigt'],
      ['betreuung', 'Gesetzliche Betreuung'],
      ['portal', 'Portalnutzer:in'],
      ['dokumente', 'Darf Dokumente erhalten'],
      ['termine', 'Darf Termine abstimmen'],
      ['keine', 'Keine besondere Berechtigung'],
    ]),
  },
  care_level: {
    key: 'care_level',
    label: 'Pflegegrad',
    entries: entries([
      ['kein', 'kein Pflegegrad'],
      ['beantragt', 'beantragt'],
      ['pg1', 'PG 1'],
      ['pg2', 'PG 2'],
      ['pg3', 'PG 3'],
      ['pg4', 'PG 4'],
      ['pg5', 'PG 5'],
      ['abgelehnt', 'abgelehnt'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  care_level_status: {
    key: 'care_level_status',
    label: 'Pflegegrad-Status',
    entries: entries([
      ['beantragt', 'beantragt'],
      ['bewilligt', 'bewilligt'],
      ['abgelehnt', 'abgelehnt'],
      ['widerspruch', 'Widerspruch läuft'],
      ['hoeherstufung', 'Höherstufung beantragt'],
      ['herabstufung', 'Herabstufung angekündigt'],
      ['unveraendert', 'unverändert'],
      ['ruhend', 'ruhend'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  billing_type: {
    key: 'billing_type',
    label: 'Abrechnungsart',
    entries: entries([
      ['selbstzahler', 'Selbstzahler'],
      ['pflegekasse', 'Pflegekasse'],
      ['krankenkasse', 'Krankenkasse'],
      ['entlastungsbetrag', 'Entlastungsbetrag §45b'],
      ['umwandlung', 'Umwandlungsanspruch'],
      ['verhinderungspflege', 'Verhinderungspflege'],
      ['privatrechnung', 'Privatrechnung'],
      ['kombination', 'Kombination'],
      ['kostenuebernahme', 'Kostenübernahme'],
      ['vorbereitet', 'Abrechnung vorbereitet'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  cost_bearer_type: {
    key: 'cost_bearer_type',
    label: 'Kostenträgertyp',
    entries: entries([
      ['pflegekasse', 'Pflegekasse'],
      ['krankenkasse', 'Krankenkasse'],
      ['privatversicherung', 'Privatversicherung'],
      ['sozialamt', 'Sozialamt'],
      ['beihilfe', 'Beihilfe'],
      ['selbstzahler', 'Selbstzahler'],
      ['berufsgenossenschaft', 'Berufsgenossenschaft'],
      ['unfallversicherung', 'Unfallversicherung'],
      ['sonstiger', 'Sonstiger Kostenträger'],
    ]),
  },
  module_assignment: {
    key: 'module_assignment',
    label: 'Modulzuordnung',
    entries: entries([
      ['office', 'Office'],
      ['assist', 'Assist'],
      ['pflege', 'Pflege'],
      ['beratung', 'Beratung'],
      ['stationaer', 'Stationär'],
      ['akademie', 'Akademie'],
      ['qm', 'QM'],
      ['portal', 'Portal'],
      ['reporting', 'Reporting'],
    ]),
  },
  assist_services: {
    key: 'assist_services',
    label: 'Assist-Leistungen',
    entries: entries([
      ['alltagsbegleitung', 'Alltagsbegleitung'],
      ['betreuung', 'Betreuung'],
      ['begleitung_ausser_haus', 'Begleitung außer Haus'],
      ['haushalt', 'Haushaltsnahe Unterstützung'],
      ['einkauf', 'Einkaufsbegleitung'],
      ['arzt', 'Arztbegleitung'],
      ['spaziergang', 'Spaziergang'],
      ['gesellschaft', 'Gesellschaft leisten'],
      ['aktivierung', 'Aktivierung'],
      ['kochen', 'Kochen vorbereiten'],
      ['reinigung', 'leichte Haushaltstätigkeit'],
      ['waesche', 'Wäscheunterstützung'],
      ['organisation', 'Organisation im Alltag'],
      ['behoerde', 'Behördengang vorbereitet'],
      ['freizeit', 'Freizeitbegleitung'],
      ['entlastung', 'Entlastung Angehöriger'],
    ]),
  },
  care_services: {
    key: 'care_services',
    label: 'Pflege-Leistungen vorbereitet',
    entries: entries([
      ['einsatz', 'Pflegeeinsatz vorbereitet'],
      ['koerperpflege', 'Körperpflege vorbereitet'],
      ['vitalwerte', 'Vitalwertkontrolle'],
      ['medikation', 'Medikamentenerinnerung'],
      ['wunde', 'Wundkontrolle'],
      ['beratung', 'Pflegeberatung'],
      ['verordnung', 'Verordnungsleistung vorbereitet'],
      ['beobachtung', 'Beobachtung'],
      ['mobilisation', 'Mobilisation'],
      ['lagerung', 'Lagerung vorbereitet'],
      ['ernaehrung', 'Ernährung beobachten'],
      ['fluessigkeit', 'Flüssigkeitsaufnahme beobachten'],
      ['ausscheidung', 'Ausscheidung beobachten'],
    ]),
  },
  consulting_types: {
    key: 'consulting_types',
    label: 'Beratungsarten',
    entries: entries([
      ['erstberatung', 'Erstberatung'],
      ['pflegegrad', 'Pflegegradberatung'],
      ['angehoerige', 'Angehörigenberatung'],
      ['leistung', 'Leistungsberatung'],
      ['entlastung', 'Entlastungsberatung'],
      ['wohnraum', 'Wohnraumberatung'],
      ['hilfsmittel', 'Hilfsmittelberatung'],
      ['fallmanagement', 'Fallmanagement'],
      ['krise', 'Krisengespräch'],
      ['wiedervorlage', 'Wiedervorlage'],
      ['besuch', 'Beratungsbesuch vorbereitet'],
      ['sonstige', 'Sonstige Beratung'],
    ]),
  },
  stationary_areas: {
    key: 'stationary_areas',
    label: 'Stationäre Bereiche',
    entries: entries([
      ['wb1', 'Wohnbereich 1'],
      ['wb2', 'Wohnbereich 2'],
      ['wb3', 'Wohnbereich 3'],
      ['demenz', 'Demenzbereich'],
      ['kurzzeit', 'Kurzzeitpflege'],
      ['tagespflege', 'Tagespflege'],
      ['betreutes_wohnen', 'Betreutes Wohnen'],
      ['pflege', 'Pflegebereich'],
      ['betreuung', 'Betreuungsbereich'],
      ['palliativ', 'Palliativbereich vorbereitet'],
      ['sonstiger', 'Sonstiger Bereich'],
    ]),
  },
  room_status: {
    key: 'room_status',
    label: 'Zimmerstatus',
    entries: entries([
      ['frei', 'frei'],
      ['belegt', 'belegt'],
      ['reserviert', 'reserviert'],
      ['gesperrt', 'gesperrt'],
      ['reinigung', 'Reinigung'],
      ['renovierung', 'Renovierung'],
      ['kurzzeit', 'Kurzzeit'],
      ['auszug', 'Auszug geplant'],
      ['einzug', 'Einzug geplant'],
    ]),
  },
  meal_form: {
    key: 'meal_form',
    label: 'Kostformen',
    entries: entries([
      ['normal', 'Normalkost'],
      ['leichte_vollkost', 'leichte Vollkost'],
      ['diabetiker', 'Diabetikerkost'],
      ['vegetarisch', 'vegetarisch'],
      ['vegan', 'vegan'],
      ['passiert', 'passierte Kost'],
      ['weich', 'weiche Kost'],
      ['pueriert', 'pürierte Kost'],
      ['trinknahrung', 'Trinknahrung'],
      ['sondennahrung', 'Sondennahrung'],
      ['kalorienreduziert', 'kalorienreduziert'],
      ['eiweissreich', 'eiweißreich'],
      ['salzarm', 'salzarm'],
      ['allergie', 'allergieangepasst'],
      ['individuell', 'individuell'],
    ]),
  },
  document_category: {
    key: 'document_category',
    label: 'Dokumentkategorien',
    entries: entries([
      ['vertrag', 'Vertrag'],
      ['datenschutz', 'Datenschutz'],
      ['einwilligung', 'Einwilligung'],
      ['vollmacht', 'Vollmacht'],
      ['betreuerausweis', 'Betreuerausweis'],
      ['pflegegradbescheid', 'Pflegegradbescheid'],
      ['kassenbescheid', 'Kassenbescheid'],
      ['arztbrief', 'Arztbrief'],
      ['rezept', 'Rezept'],
      ['verordnung', 'Verordnung'],
      ['ueberweisung', 'Überweisung'],
      ['medikationsplan', 'Medikationsplan'],
      ['leistungsnachweis', 'Leistungsnachweis'],
      ['rechnung', 'Rechnung'],
      ['mahnung', 'Mahnung'],
      ['beratungsprotokoll', 'Beratungsprotokoll'],
      ['pflegebericht', 'Pflegebericht'],
      ['vitalwerte', 'Vitalwerte'],
      ['wunddokumentation', 'Wunddokumentation'],
      ['foto', 'Foto'],
      ['scan', 'Scan'],
      ['ausweis', 'Ausweis optional'],
      ['schluesselprotokoll', 'Schlüsselprotokoll'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  document_source: {
    key: 'document_source',
    label: 'Dokumentquelle',
    entries: entries([
      ['upload', 'Upload'],
      ['foto', 'Foto'],
      ['scan', 'Scan'],
      ['systemvorlage', 'Systemvorlage'],
      ['unterschrieben', 'Unterschriebenes Dokument'],
      ['import', 'Import'],
      ['email', 'E-Mail'],
      ['portal', 'Portal'],
      ['manuell', 'Manuell erstellt'],
      ['ki', 'KI vorbereitet'],
    ]),
  },
  document_status: {
    key: 'document_status',
    label: 'Dokumentstatus',
    entries: entries([
      ['entwurf', 'Entwurf'],
      ['vorbereitet', 'vorbereitet'],
      ['hochgeladen', 'hochgeladen'],
      ['geprueft', 'geprüft'],
      ['unterschrieben', 'unterschrieben'],
      ['freigegeben', 'freigegeben'],
      ['abgelaufen', 'abgelaufen'],
      ['widerrufen', 'widerrufen'],
      ['archiviert', 'archiviert'],
      ['fehlerhaft', 'fehlerhaft'],
    ]),
  },
  consent_type: {
    key: 'consent_type',
    label: 'Einwilligungsarten',
    entries: entries([
      ['datenschutz', 'Datenschutzeinwilligung'],
      ['schweigepflicht', 'Schweigepflichtentbindung'],
      ['kontakt', 'Einwilligung Kontaktaufnahme'],
      ['dokumente', 'Einwilligung Dokumentenverarbeitung'],
      ['portal', 'Einwilligung Portalzugang'],
      ['foto', 'Foto-/Dokumentationseinwilligung'],
      ['abrechnung', 'Abrechnungsvollmacht'],
      ['abtretung', 'Abtretungserklärung'],
      ['notfall', 'Notfallkontakt-Einwilligung'],
      ['angehoerige', 'Einwilligung Angehörigenkommunikation'],
      ['signatur', 'Einwilligung digitale Signatur'],
      ['elektronisch', 'Einwilligung elektronische Kommunikation'],
    ]),
  },
  contract_type: {
    key: 'contract_type',
    label: 'Vertragsarten',
    entries: entries([
      ['kundenvertrag', 'Kundenvertrag'],
      ['leistungsvereinbarung', 'Leistungsvereinbarung'],
      ['betreuungsvertrag', 'Betreuungsvertrag'],
      ['alltagsbegleitung', 'Alltagsbegleitungsvertrag'],
      ['pflegevertrag', 'Pflegevertrag vorbereitet'],
      ['beratungsvereinbarung', 'Beratungsvereinbarung'],
      ['schulung', 'Schulungsvereinbarung vorbereitet'],
      ['abrechnungsvollmacht', 'Abrechnungsvollmacht'],
      ['sepa', 'SEPA-Mandat vorbereitet'],
      ['schluessel', 'Schlüsselvereinbarung'],
      ['portal', 'Portalvereinbarung'],
      ['zusatz', 'Zusatzvereinbarung'],
    ]),
  },
  signature_role: {
    key: 'signature_role',
    label: 'Signaturrolle',
    entries: entries([
      ['klient', 'Klient:in'],
      ['betreuung', 'gesetzliche Betreuung'],
      ['bevollmaechtigt', 'Bevollmächtigte:r'],
      ['angehoerige', 'Angehörige:r mit Berechtigung'],
      ['ehepartner', 'Ehepartner:in'],
      ['sorgeberechtigt', 'Sorgeberechtigte:r'],
      ['geschaeftsfuehrung', 'Geschäftsführung'],
      ['mitarbeitend', 'Mitarbeitende:r'],
    ]),
  },
  home_access: {
    key: 'home_access',
    label: 'Wohnungszugang',
    entries: entries([
      ['klingel', 'Klingel vorhanden'],
      ['tuercode', 'Türcode'],
      ['schluessel', 'Schlüssel vorhanden'],
      ['tresor', 'Schlüsseltresor'],
      ['pförtner', 'Pförtner / Empfang'],
      ['angehoerige', 'Angehörige öffnen'],
      ['selbst', 'Klient:in öffnet selbst'],
      ['nachbar', 'Nachbar:in öffnet'],
      ['begleitung', 'kein Zugang ohne Begleitung'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  key_status: {
    key: 'key_status',
    label: 'Schlüsselstatus',
    entries: entries([
      ['kein', 'kein Schlüssel'],
      ['vorhanden', 'Schlüssel vorhanden'],
      ['beantragt', 'Schlüssel beantragt'],
      ['angehoerige', 'Schlüssel bei Angehörigen'],
      ['tresor', 'Schlüssel im Tresor'],
      ['verloren', 'Schlüssel verloren'],
      ['zurueck', 'Schlüssel zurückgegeben'],
      ['nicht_erforderlich', 'nicht erforderlich'],
    ]),
  },
  pets: {
    key: 'pets',
    label: 'Haustiere',
    entries: entries([
      ['keine', 'keine'],
      ['hund', 'Hund'],
      ['katze', 'Katze'],
      ['vogel', 'Vogel'],
      ['fische', 'Fische'],
      ['kleintiere', 'Kleintiere'],
      ['mehrere', 'mehrere Haustiere'],
      ['unbekannt', 'unbekannt'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  mobility: {
    key: 'mobility',
    label: 'Mobilität',
    entries: entries([
      ['selbststaendig', 'selbstständig'],
      ['gehstock', 'mit Gehstock'],
      ['rollator', 'mit Rollator'],
      ['rollstuhl', 'mit Rollstuhl'],
      ['bettlaegerig', 'bettlägerig'],
      ['transfer', 'transferbedürftig'],
      ['sturz', 'sturzgefährdet'],
      ['begleitung', 'Begleitung erforderlich'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  orientation: {
    key: 'orientation',
    label: 'Orientierung',
    entries: entries([
      ['orientiert', 'orientiert'],
      ['zeitlich', 'zeitlich eingeschränkt'],
      ['oertlich', 'örtlich eingeschränkt'],
      ['situativ', 'situativ eingeschränkt'],
      ['personell', 'personell eingeschränkt'],
      ['wechselnd', 'wechselnd'],
      ['desorientiert', 'desorientiert'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  communication: {
    key: 'communication',
    label: 'Kommunikation',
    entries: entries([
      ['klar', 'spricht klar'],
      ['schwerhoerig', 'schwerhörig'],
      ['gehoerlos', 'gehörlos'],
      ['sehbehindert', 'sehbeeinträchtigt'],
      ['sprachbehindert', 'sprachbeeinträchtigt'],
      ['einfach', 'versteht einfache Sprache'],
      ['fremdsprache', 'Fremdsprache'],
      ['nonverbal', 'nonverbal'],
      ['angehoerige', 'Kommunikation über Angehörige'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  risk_type: {
    key: 'risk_type',
    label: 'Risikoarten',
    entries: entries([
      ['sturz', 'Sturz'],
      ['dekubitus', 'Dekubitus'],
      ['dehydration', 'Dehydration'],
      ['mangelernaehrung', 'Mangelernährung'],
      ['schmerz', 'Schmerz'],
      ['infektion', 'Infektion'],
      ['weglauf', 'Weglauftendenz'],
      ['selbstgefaehrdung', 'Selbstgefährdung'],
      ['fremdgefaehrdung', 'Fremdgefährdung'],
      ['medikation', 'Medikationsrisiko'],
      ['allergie', 'Allergie'],
      ['aspiration', 'Aspiration'],
      ['kontraktur', 'Kontraktur'],
      ['haut', 'Hautrisiko'],
      ['psychisch', 'psychische Belastung'],
      ['isolation', 'soziale Isolation'],
    ]),
  },
  risk_level: {
    key: 'risk_level',
    label: 'Risikostufen',
    entries: entries([
      ['kein', 'kein Risiko bekannt'],
      ['niedrig', 'niedrig'],
      ['mittel', 'mittel'],
      ['hoch', 'hoch'],
      ['akut', 'akut'],
      ['unbekannt', 'unbekannt'],
    ]),
  },
  vital_type: {
    key: 'vital_type',
    label: 'Vitalwertarten',
    entries: entries([
      ['bp_sys', 'Blutdruck systolisch'],
      ['bp_dia', 'Blutdruck diastolisch'],
      ['puls', 'Puls'],
      ['temperatur', 'Temperatur'],
      ['spo2', 'Sauerstoffsättigung'],
      ['blutzucker', 'Blutzucker'],
      ['gewicht', 'Gewicht'],
      ['schmerz', 'Schmerzskala'],
      ['atemfrequenz', 'Atemfrequenz'],
      ['fluessigkeit', 'Flüssigkeitsmenge'],
      ['ausscheidung', 'Ausscheidung'],
    ]),
  },
  vital_unit: {
    key: 'vital_unit',
    label: 'Vitalwert-Einheiten',
    entries: entries([
      ['mmhg', 'mmHg'],
      ['per_min', '/min'],
      ['celsius', '°C'],
      ['percent', '%'],
      ['mg_dl', 'mg/dl'],
      ['mmol_l', 'mmol/l'],
      ['kg', 'kg'],
      ['nrs', 'NRS 0–10'],
      ['ml', 'ml'],
      ['l', 'l'],
    ]),
  },
  medication_form: {
    key: 'medication_form',
    label: 'Darreichungsform',
    entries: entries([
      ['tablette', 'Tablette'],
      ['kapsel', 'Kapsel'],
      ['tropfen', 'Tropfen'],
      ['saft', 'Saft'],
      ['loesung', 'Lösung'],
      ['salbe', 'Salbe'],
      ['creme', 'Creme'],
      ['gel', 'Gel'],
      ['spray', 'Spray'],
      ['inhalation', 'Inhalation'],
      ['pflaster', 'Pflaster'],
      ['ampulle', 'Ampulle'],
      ['injektion', 'Injektion vorbereitet'],
      ['zaepfchen', 'Zäpfchen'],
      ['pulver', 'Pulver'],
      ['beutel', 'Beutel'],
      ['sonde', 'Sonde vorbereitet'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  medication_unit: {
    key: 'medication_unit',
    label: 'Medikamenten-Einheiten',
    entries: entries([
      ['mg', 'mg'],
      ['g', 'g'],
      ['ml', 'ml'],
      ['l', 'l'],
      ['tropfen', 'Tropfen'],
      ['tablette', 'Tablette'],
      ['kapsel', 'Kapsel'],
      ['hub', 'Hub'],
      ['spruehstoss', 'Sprühstoß'],
      ['einheit', 'Einheit'],
      ['ie', 'IE'],
      ['beutel', 'Beutel'],
      ['ampulle', 'Ampulle'],
      ['pflaster', 'Pflaster'],
      ['messloeffel', 'Messlöffel'],
      ['stueck', 'Stück'],
    ]),
  },
  intake_time: {
    key: 'intake_time',
    label: 'Einnahmezeit',
    entries: entries([
      ['morgens', 'morgens'],
      ['mittags', 'mittags'],
      ['abends', 'abends'],
      ['nachts', 'nachts'],
      ['vor_essen', 'vor dem Essen'],
      ['zum_essen', 'zum Essen'],
      ['nach_essen', 'nach dem Essen'],
      ['bedarf', 'bei Bedarf'],
      ['individuell', 'individuell'],
    ]),
  },
  intake_schedule: {
    key: 'intake_schedule',
    label: 'Einnahmeschema',
    entries: entries([
      ['1-0-0-0', '1-0-0-0'],
      ['0-1-0-0', '0-1-0-0'],
      ['0-0-1-0', '0-0-1-0'],
      ['0-0-0-1', '0-0-0-1'],
      ['1-1-0-0', '1-1-0-0'],
      ['1-0-1-0', '1-0-1-0'],
      ['1-0-0-1', '1-0-0-1'],
      ['0-1-1-0', '0-1-1-0'],
      ['0-1-0-1', '0-1-0-1'],
      ['0-0-1-1', '0-0-1-1'],
      ['1-1-1-0', '1-1-1-0'],
      ['1-1-0-1', '1-1-0-1'],
      ['1-0-1-1', '1-0-1-1'],
      ['0-1-1-1', '0-1-1-1'],
      ['1-1-1-1', '1-1-1-1'],
      ['bedarf', 'nach Bedarf'],
      ['individuell', 'individuell'],
    ]),
  },
  prescription_type: {
    key: 'prescription_type',
    label: 'Rezept-/Verordnungstyp',
    entries: entries([
      ['rezept', 'Rezept'],
      ['verordnung', 'Verordnung'],
      ['ueberweisung', 'Überweisung'],
      ['arztbrief', 'Arztbrief'],
      ['medikationsplan', 'Medikationsplan'],
      ['heilmittel', 'Heilmittelverordnung'],
      ['hilfsmittel', 'Hilfsmittelverordnung'],
      ['krankenhaus', 'Krankenhausbericht'],
      ['pflegekasse', 'Pflegekassenbescheid'],
      ['sonstiges', 'sonstiges medizinisches Dokument'],
    ]),
  },
  support_tasks: {
    key: 'support_tasks',
    label: 'Aufgaben / Unterstützungswünsche',
    entries: entries([
      ['gesellschaft', 'Gesellschaft leisten'],
      ['spaziergang', 'Spaziergang'],
      ['einkaufen', 'Einkaufen'],
      ['kochen', 'Kochen / Mahlzeiten vorbereiten'],
      ['reinigung', 'leichte Reinigung'],
      ['waesche', 'Wäsche'],
      ['arzt', 'Arztbegleitung'],
      ['behoerde', 'Behördengang'],
      ['freizeit', 'Freizeitbegleitung'],
      ['aktivierung', 'Aktivierung'],
      ['termine', 'Erinnerung an Termine'],
      ['post', 'Post sortieren'],
      ['organisation', 'Organisation im Alltag'],
      ['entlastung', 'Angehörige entlasten'],
      ['biografie', 'Biografiegespräch'],
      ['vorlesen', 'Vorlesen'],
      ['spiele', 'Spiele / Aktivierung'],
    ]),
  },
  preferred_visit_times: {
    key: 'preferred_visit_times',
    label: 'Bevorzugte Einsatzzeiten',
    entries: entries([
      ['morgens', 'morgens'],
      ['vormittags', 'vormittags'],
      ['mittags', 'mittags'],
      ['nachmittags', 'nachmittags'],
      ['abends', 'abends'],
      ['wochentags', 'wochentags'],
      ['wochenende', 'Wochenende'],
      ['flexibel', 'flexibel'],
      ['feste', 'feste Zeiten'],
      ['absprache', 'nach Absprache'],
    ]),
  },
  billing_status: {
    key: 'billing_status',
    label: 'Abrechnungsstatus',
    entries: entries([
      ['nicht_relevant', 'nicht abrechnungsrelevant'],
      ['offen', 'offen'],
      ['bereit', 'bereit zur Abrechnung'],
      ['in_rechnung', 'in Rechnung übernommen'],
      ['abgerechnet', 'abgerechnet'],
      ['bezahlt', 'bezahlt'],
      ['teilbezahlt', 'teilbezahlt'],
      ['ueberfaellig', 'überfällig'],
      ['gemahnt', 'gemahnt'],
      ['storniert', 'storniert'],
    ]),
  },
  portal_status: {
    key: 'portal_status',
    label: 'Portalstatus',
    entries: entries([
      ['kein', 'kein Portalzugang'],
      ['code', 'Code erstellt'],
      ['aktiv', 'aktiv'],
      ['gesperrt', 'gesperrt'],
      ['neu', 'neu generieren erforderlich'],
      ['abgelaufen', 'abgelaufen'],
      ['deaktiviert', 'deaktiviert'],
    ]),
  },
  communication_channel: {
    key: 'communication_channel',
    label: 'Kommunikationskanal',
    entries: entries([
      ['telefon', 'Telefon'],
      ['email', 'E-Mail'],
      ['brief', 'Brief'],
      ['portal', 'Portal'],
      ['persoenlich', 'persönlich'],
      ['angehoerige', 'Angehörige'],
      ['betreuung', 'Betreuung'],
      ['intern', 'intern'],
      ['sonstiges', 'Sonstiges'],
    ]),
  },
  timeline_event_type: {
    key: 'timeline_event_type',
    label: 'Timeline-Ereignistypen',
    entries: entries([
      ['aufnahme', 'Aufnahme erstellt'],
      ['stammdaten', 'Stammdaten geändert'],
      ['modul', 'Modul zugeordnet'],
      ['dokument', 'Dokument hochgeladen'],
      ['vertrag', 'Vertrag unterschrieben'],
      ['einwilligung', 'Einwilligung erfasst'],
      ['einsatz_geplant', 'Einsatz geplant'],
      ['einsatz', 'Einsatz durchgeführt'],
      ['nachweis', 'Leistungsnachweis erstellt'],
      ['rechnung', 'Rechnung erstellt'],
      ['zahlung', 'Zahlung eingegangen'],
      ['nachricht', 'Nachricht gesendet'],
      ['vitalwert', 'Vitalwert erfasst'],
      ['medikation', 'Medikation geändert'],
      ['risiko', 'Risiko erfasst'],
      ['beratung', 'Beratungsprotokoll erstellt'],
      ['pflegebericht', 'Pflegebericht erstellt'],
      ['portal', 'Portalzugang erstellt'],
      ['export', 'Akte exportiert vorbereitet'],
    ]),
  },
};

export const ALL_CATALOG_KEYS = Object.keys(SYSTEM_CATALOGS) as SystemCatalogKey[];

export function getSystemCatalog(key: SystemCatalogKey): SystemCatalog {
  return SYSTEM_CATALOGS[key];
}

export function getCatalogLabel(key: SystemCatalogKey, value: string): string {
  const catalog = SYSTEM_CATALOGS[key];
  const entry = catalog.entries.find((e) => e.key === value);
  return entry?.label ?? value;
}
