/** Systemvorlagen für Kostenträger-Stammdaten (Name, Adresse, IK). */
export type SystemCostCarrierType =
  | 'pflegekasse'
  | 'krankenkasse'
  | 'privatversicherung'
  | 'sozialamt'
  | 'berufsgenossenschaft'
  | 'unfallversicherung';

export type SystemCostCarrierTemplate = {
  id: string;
  name: string;
  type: SystemCostCarrierType;
  department: string | null;
  street: string;
  zip: string;
  city: string;
  ikNumber: string;
};

export const SYSTEM_COST_CARRIER_TEMPLATES: SystemCostCarrierTemplate[] = [
  {
    id: 'aok-nordost-pflege',
    name: 'AOK Nordost — Die Gesundheitskasse',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Reinhardtstraße 28',
    zip: '10117',
    city: 'Berlin',
    ikNumber: '109519005',
  },
  {
    id: 'aok-nordost-kk',
    name: 'AOK Nordost — Die Gesundheitskasse',
    type: 'krankenkasse',
    department: null,
    street: 'Reinhardtstraße 28',
    zip: '10117',
    city: 'Berlin',
    ikNumber: '109519005',
  },
  {
    id: 'tk-kk',
    name: 'Techniker Krankenkasse',
    type: 'krankenkasse',
    department: null,
    street: 'Bramfelder Straße 140',
    zip: '22305',
    city: 'Hamburg',
    ikNumber: '101575519',
  },
  {
    id: 'tk-pflege',
    name: 'Techniker Krankenkasse',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Bramfelder Straße 140',
    zip: '22305',
    city: 'Hamburg',
    ikNumber: '101575519',
  },
  {
    id: 'barmer-kk',
    name: 'BARMER',
    type: 'krankenkasse',
    department: null,
    street: 'Lichtscheider Straße 89',
    zip: '42285',
    city: 'Wuppertal',
    ikNumber: '104940005',
  },
  {
    id: 'barmer-pflege',
    name: 'BARMER',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Lichtscheider Straße 89',
    zip: '42285',
    city: 'Wuppertal',
    ikNumber: '104940005',
  },
  {
    id: 'dak-kk',
    name: 'DAK-Gesundheit',
    type: 'krankenkasse',
    department: null,
    street: 'Nagelsweg 27-31',
    zip: '20097',
    city: 'Hamburg',
    ikNumber: '101560000',
  },
  {
    id: 'dak-pflege',
    name: 'DAK-Gesundheit',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Nagelsweg 27-31',
    zip: '20097',
    city: 'Hamburg',
    ikNumber: '101560000',
  },
  {
    id: 'knappschaft-kk',
    name: 'Knappschaft',
    type: 'krankenkasse',
    department: null,
    street: 'Karl-Wiechert-Allee 28',
    zip: '30625',
    city: 'Hannover',
    ikNumber: '109905003',
  },
  {
    id: 'knappschaft-pflege',
    name: 'Knappschaft',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Karl-Wiechert-Allee 28',
    zip: '30625',
    city: 'Hannover',
    ikNumber: '109905003',
  },
  {
    id: 'aok-bayern-kk',
    name: 'AOK Bayern — Die Gesundheitskasse',
    type: 'krankenkasse',
    department: null,
    street: 'Bodenseestraße 166',
    zip: '81241',
    city: 'München',
    ikNumber: '108310400',
  },
  {
    id: 'aok-bayern-pflege',
    name: 'AOK Bayern — Die Gesundheitskasse',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Bodenseestraße 166',
    zip: '81241',
    city: 'München',
    ikNumber: '108310400',
  },
  {
    id: 'ikk-classic-kk',
    name: 'IKK classic',
    type: 'krankenkasse',
    department: null,
    street: 'Wilhelmstraße 2',
    zip: '65185',
    city: 'Wiesbaden',
    ikNumber: '101570104',
  },
  {
    id: 'bkk-vbu-kk',
    name: 'BKK VBU',
    type: 'krankenkasse',
    department: null,
    street: 'Am Kümmerling 24-32',
    zip: '55294',
    city: 'Bodenheim',
    ikNumber: '101531011',
  },
  {
    id: 'hkk-kk',
    name: 'hkk Krankenkasse',
    type: 'krankenkasse',
    department: null,
    street: 'Martinistraße 26',
    zip: '28195',
    city: 'Bremen',
    ikNumber: '103170002',
  },
  {
    id: 'hkk-pflege',
    name: 'hkk Krankenkasse',
    type: 'pflegekasse',
    department: 'Pflegekasse',
    street: 'Martinistraße 26',
    zip: '28195',
    city: 'Bremen',
    ikNumber: '103170002',
  },
  {
    id: 'allianz-pv',
    name: 'Allianz Private Krankenversicherungs-AG',
    type: 'privatversicherung',
    department: null,
    street: 'Königinstraße 28',
    zip: '80802',
    city: 'München',
    ikNumber: '168140017',
  },
  {
    id: 'debeka-pv',
    name: 'DEBEKA Krankenversicherungsverein a. G.',
    type: 'privatversicherung',
    department: null,
    street: 'Im Metternich 4-6',
    zip: '56073',
    city: 'Koblenz',
    ikNumber: '168140012',
  },
  {
    id: 'sozialamt-berlin-mitte',
    name: 'Sozialamt Berlin-Mitte',
    type: 'sozialamt',
    department: null,
    street: 'Karl-Marx-Allee 31',
    zip: '10178',
    city: 'Berlin',
    ikNumber: '',
  },
  {
    id: 'sozialamt-hamburg-mitte',
    name: 'Bezirksamt Hamburg-Mitte — Sozialamt',
    type: 'sozialamt',
    department: null,
    street: 'Billstraße 80',
    zip: '20539',
    city: 'Hamburg',
    ikNumber: '',
  },
  {
    id: 'bgw',
    name: 'BGW — Berufsgenossenschaft für Gesundheitsdienst und Wohlfahrtspflege',
    type: 'berufsgenossenschaft',
    department: null,
    street: 'Kronenstraße 45-51',
    zip: '70174',
    city: 'Stuttgart',
    ikNumber: '105830016',
  },
  {
    id: 'bghw',
    name: 'BGHW — Berufsgenossenschaft Handel und Warenlogistik',
    type: 'berufsgenossenschaft',
    department: null,
    street: 'An der Feuerwehr 4',
    zip: '30173',
    city: 'Hannover',
    ikNumber: '105830017',
  },
  {
    id: 'uv-bund-bahn',
    name: 'Unfallversicherung Bund und Bahn',
    type: 'unfallversicherung',
    department: null,
    street: 'Glinkastraße 9',
    zip: '10117',
    city: 'Berlin',
    ikNumber: '109905004',
  },
  {
    id: 'uk-nord',
    name: 'Unfallkasse Nord',
    type: 'unfallversicherung',
    department: null,
    street: 'Hindenburgstraße 104',
    zip: '24114',
    city: 'Kiel',
    ikNumber: '109905005',
  },
];

export function formatSystemCostCarrierAddress(template: Pick<SystemCostCarrierTemplate, 'street' | 'zip' | 'city'>): string {
  return `${template.street}, ${template.zip} ${template.city}`;
}
