/** Render the fixed bank with the exact same local worker used for live speech.
 * Requires the existing project Playwright and FFmpeg development tools.
 * node robot-voice/render-browser.mjs /absolute/output-directory
 * Optional: CHROMIUM_EXECUTABLE_PATH for an existing Chromium installation.
 * Public runtime/model assets must already exist (prepare-neo-voice.mjs).
 */
import { chromium } from 'playwright';
import { createServer } from 'node:http';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const output = path.resolve(process.argv[2] || path.join(root, 'robot-voice/rendered'));
await mkdir(output, { recursive: true });
const catalog = JSON.parse(await readFile(path.join(root, 'robot-voice/reply-catalog.json'), 'utf8'));
const intro = 'Ich bin Neo, dein kleiner Assistent in deinem CareSuite Health OS.';
const extras = [intro, 'Hallo Kevin. Schön, dass du da bist.', 'Es ist siebzehn Uhr elf.'];
const texts = [...new Set([...Object.values(catalog), ...extras])];
const hash = data => createHash('sha256').update(data).digest('hex');
const ids = Object.fromEntries(Object.entries(catalog).map(([id, text]) => [id, hash(text).slice(0, 16)]));
const server = createServer(async (request, response) => {
  try {
    const name = decodeURIComponent(new URL(request.url, 'http://localhost').pathname);
    if (name === '/') { response.setHeader('Content-Type', 'text/html'); response.end('<!doctype html><title>Neo local voice rendering</title>'); return; }
    const file = path.resolve(root, 'public', '.' + name);
    if (!file.startsWith(path.join(root, 'public') + path.sep)) throw Error('invalid path');
    response.setHeader('Content-Type', file.endsWith('.js') ? 'text/javascript' : file.endsWith('.wasm') ? 'application/wasm' : 'application/octet-stream');
    response.end(await readFile(file));
  } catch { response.writeHead(404).end(); }
});
await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
const origin = `http://127.0.0.1:${server.address().port}`;
let browser;
try {
  browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE_PATH || undefined, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.route('**/*', route => route.request().url().startsWith(origin + '/') ? route.continue() : route.abort());
  await page.goto(origin);
  await page.evaluate(() => {
    window.voice = new Worker('/neo-voice/v1/neo-worker.js');
    window.render = (text, id) => new Promise((resolve, reject) => {
      const timeout = setTimeout(() => reject(Error('Voice render timed out')), 90000);
      window.voice.onmessage = ({ data }) => {
        if (data.id !== id) return;
        clearTimeout(timeout);
        if (data.error) reject(Error(data.error)); else resolve(Array.from(new Uint8Array(data.audio)));
      };
      window.voice.onerror = error => { clearTimeout(timeout); reject(Error(error.message)); };
      window.voice.postMessage({ type: 'speak', id, text });
    });
  });
  const clips = {}, report = [];
  for (const [index, text] of texts.entries()) {
    const clipId = hash(text).slice(0, 16), base = path.join(output, clipId);
    const wav = Buffer.from(await page.evaluate(({ text, id }) => window.render(text, id), { text, id: index + 1 }));
    await writeFile(base + '.wav', wav);
    execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', '-i', base + '.wav', '-map_metadata', '-1', '-codec:a', 'libmp3lame', '-b:a', '128k', base + '.mp3']);
    const mp3 = await readFile(base + '.mp3');
    const pcm = execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-i', base + '.mp3', '-f', 'f32le', '-ac', '1', '-ar', '22050', '-'], { maxBuffer: 8_000_000 });
    let peak = 0, sum = 0;
    for (let i = 0; i < pcm.length; i += 4) { const v = pcm.readFloatLE(i); peak = Math.max(peak, Math.abs(v)); sum += v * v; }
    const duration = pcm.length / 4 / 22050, rms = Math.sqrt(sum / (pcm.length / 4));
    if (!(duration > 0.25 && peak > 0.02 && peak < 0.99 && rms > 0.002)) throw Error(`Invalid audio: ${text}`);
    clips[clipId] = mp3.toString('base64');
    report.push({ clipId, text, duration, bytes: mp3.length, peak, rms, sha256: hash(mp3) });
    console.log(`${index + 1}/${texts.length} ${duration.toFixed(2)}s ${text}`);
  }
  const bank = Object.fromEntries([...new Set(Object.values(ids))].map(id => [id, clips[id]]));
  const header = '/** Generated by robot-voice/render-browser.mjs using the local Neo worker. */\n';
  let source = header;
  for (const [name, value] of [['ROBOT_AUDIO_TEXT', catalog], ['ROBOT_AUDIO_IDS', ids], ['ROBOT_AUDIO_MP3', bank]]) source += `export const ${name}: Readonly<Record<string, string>> = ${JSON.stringify(value, null, 2)};\n\n`;
  await writeFile(path.join(output, 'robotAudioBank.web.ts'), source.trimEnd() + '\n');
  await writeFile(path.join(output, 'neoFixedAudio.web.ts'), header + `export const NEO_FIXED_AUDIO: Readonly<Record<string, string>> = ${JSON.stringify({ [intro]: clips[hash(intro).slice(0, 16)] }, null, 2)};\n`);
  await writeFile(path.join(output, 'voice-report.json'), JSON.stringify({ renderer: 'local Neo browser worker', workerSha256: hash(await readFile(path.join(root, 'public/neo-voice/v1/neo-worker.js'))), sampleRate: 22050, lengthScale: 1.45, noiseScale: 0.55, noiseWScale: 0.45, sentencePauseSeconds: 0.24, leadSeconds: 0.07, tailSeconds: 0.12, replies: Object.keys(ids).length, uniqueClips: Object.keys(bank).length, clips: report }, null, 2) + '\n');
  // Preview consists of the actual encoded app clips, with space between examples.
  const preview = [intro, extras[1], catalog['calendar:0'], extras[2], catalog['error:0']];
  const pieces = [];
  for (const text of preview) {
    pieces.push(execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-i', path.join(output, hash(text).slice(0, 16) + '.mp3'), '-f', 's16le', '-ar', '22050', '-ac', '1', '-']));
    pieces.push(Buffer.alloc(Math.round(22050 * 0.5) * 2));
  }
  execFileSync('ffmpeg', ['-hide_banner', '-loglevel', 'error', '-y', '-f', 's16le', '-ar', '22050', '-ac', '1', '-i', '-', '-codec:a', 'libmp3lame', '-b:a', '128k', path.join(output, 'CareSuite_Stimme_Hoerprobe.mp3')], { input: Buffer.concat(pieces) });
} finally {
  await browser?.close();
  await new Promise(resolve => server.close(resolve));
}
