import type { AppRoute, RouteGroup } from '@/types/navigation/routes';

/**
 * Zentrale Routen-Registry für CareSuite+.
 * Alle Guards und Navigation-UI beziehen sich auf diese Definition.
 */
export const APP_ROUTES: AppRoute[] = [
  { path: '/', label: 'Start', group: 'public', requiresAuth: false },
  { path: '/fundament', label: 'Fundament', group: 'system', requiresAuth: false },
  { path: '/design-system', label: 'Design System', group: 'system', requiresAuth: false },

  { path: '/onboarding', label: 'Onboarding', group: 'public', requiresAuth: false },
  {
    path: '/onboarding/company-setup',
    label: 'Mandant einrichten',
    group: 'public',
    requiresAuth: false,
  },

  { path: '/auth/business-login', label: 'Business-Anmeldung', group: 'auth', requiresAuth: false },
  { path: '/auth/register', label: 'Registrierung', group: 'auth', requiresAuth: false },
  { path: '/auth/register-business', label: 'Business-Registrierung', group: 'auth', requiresAuth: false },
  { path: '/auth/employee-login', label: 'Mitarbeiter-Anmeldung', group: 'auth', requiresAuth: false },
  { path: '/auth/employee-portal-login', label: 'Mitarbeiterportal-Anmeldung', group: 'auth', requiresAuth: false },
  { path: '/auth/employee-first-login', label: 'Erstlogin Mitarbeiter', group: 'auth', requiresAuth: false },
  { path: '/auth/client-login', label: 'Klient:innen-Anmeldung', group: 'auth', requiresAuth: false },
  { path: '/auth/portal-code-login', label: 'Portal-Code Login', group: 'auth', requiresAuth: false },
  { path: '/auth/forgot-password', label: 'Passwort vergessen', group: 'auth', requiresAuth: false },

  { path: '/settings/data-request', label: 'Datenauskunft', group: 'settings', requiresAuth: true },
  { path: '/settings/account-deletion', label: 'Kontolöschung', group: 'settings', requiresAuth: true },
  {
    path: '/settings/appearance',
    label: 'Darstellung & Oberfläche',
    group: 'settings',
    requiresAuth: true,
  },

  {
    path: '/business',
    label: 'Business-Bereich',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
    children: ['/business/modules'],
  },
  {
    path: '/business/modules',
    label: 'Module & Lizenzen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/business/messages',
    label: 'Kommunikationszentrum',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
    children: [
      '/business/messages/new',
      '/business/messages/archived',
      '/business/messages/assignments',
      '/business/messages/settings',
      '/business/messages/channels',
    ],
  },
  {
    path: '/business/messages/settings',
    label: 'Einstellungen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/business/connect',
    label: 'CareSuite+ Connect',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: [
      '/business/connect/providers',
      '/business/connect/marketplace',
      '/business/connect/accounting/prepare',
      '/business/connect/billing/prepare',
    ],
  },
  {
    path: '/business/connect/providers',
    label: 'Connect Anbieter',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/communication/settings',
    label: 'Einstellungen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/communication/einstellungen',
    label: 'Einstellungen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/business/reporting',
    label: 'Business Reporting',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
    children: ['/business/reporting/list'],
  },
  {
    path: '/business/release',
    label: 'Release',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: ['/business/release/list'],
  },
  {
    path: '/business/roadmap',
    label: 'Roadmap',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: ['/business/roadmap/list'],
  },
  {
    path: '/business/security',
    label: 'Security',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: ['/business/security/list', '/business/security/data-requests'],
  },
  {
    path: '/business/qa',
    label: 'QA',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: ['/business/qa/list'],
  },
  {
    path: '/business/ops',
    label: 'Ops',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/ti',
    label: 'Telematik',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'nurse'],
    children: ['/business/ti/kim', '/business/ti/audit', '/business/ti/consent'],
  },
  {
    path: '/business/templates',
    label: 'Vorlagenzentrum',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/integrations',
    label: 'Integrationen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/platform',
    label: 'Plattform KI & OCR',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: ['/business/platform/ocr', '/business/platform/ai'],
  },
  {
    path: '/business/platform/ocr',
    label: 'OCR-Jobs',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/platform/ai',
    label: 'KI-Jobs',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/qm',
    label: 'Qualitätsmanagement',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'nurse'],
  },
  {
    path: '/business/office',
    label: 'Office',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/business/office/time-tracking',
    label: 'Arbeitszeit',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/business/office/time-tracking/audit',
    label: 'Arbeitszeit-Audit',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/portal/employee/arbeitszeit',
    label: 'Arbeitszeit',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/business/office/access',
    label: 'Zugänge & Benutzer',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
    children: [
      '/business/office/access/internal-users',
      '/business/office/access/employee-portal',
      '/business/office/access/client-portal',
      '/business/office/access/relative-portal',
      '/business/office/access/roles',
      '/business/office/access/login-audit',
      '/business/office/access/module-permissions',
    ],
  },
  {
    path: '/business/office/access/internal-users',
    label: 'Interne Benutzer',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/employee-portal',
    label: 'Mitarbeitendenportal',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/client-portal',
    label: 'Klient:innenportal',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/relative-portal',
    label: 'Angehörigenportal',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/roles',
    label: 'Rollen & Rechte',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/login-audit',
    label: 'Login-Protokoll',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/office/access/module-permissions',
    label: 'Modulrechte',
    group: 'business',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/business/admin/developer',
    label: 'Entwicklerwerkzeuge',
    group: 'system',
    requiresAuth: true,
    allowedRoles: ['business_admin'],
  },
  {
    path: '/business/admin/design-system',
    label: 'Design System (Admin)',
    group: 'system',
    requiresAuth: true,
    allowedRoles: ['business_admin'],
  },
  {
    path: '/business/admin/architecture',
    label: 'Architektur (Admin)',
    group: 'system',
    requiresAuth: true,
    allowedRoles: ['business_admin'],
  },
  {
    path: '/portal/relative',
    label: 'Angehörigenportal',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['family_portal'],
    children: ['/portal/relative/messages'],
  },
  {
    path: '/portal/relative/messages',
    label: 'Angehörigen-Nachrichten',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['family_portal'],
  },

  {
    path: '/office',
    label: 'Office',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: [
      '/office/clients',
      '/office/employees',
      '/office/appointments',
      '/office/calendar',
      '/office/invoices',
      '/office/documents',
      '/office/documents-signatures',
      '/business/office/documents/signatures',
      '/office/messages',
      '/office/catalogs',
    ],
  },
  {
    path: '/office/clients',
    label: 'Klient:innen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: ['/office/clients/create', '/business/office/clients/new'],
  },
  {
    path: '/office/clients/create',
    label: 'Klient:in anlegen (Weiterleitung)',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/business/office/clients/new',
    label: 'Neuaufnahme',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse', 'caregiver', 'counselor'],
  },
  {
    path: '/business/office/clients/[id]',
    label: 'Klient:innenakte',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/employees',
    label: 'Mitarbeitende',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: ['/office/employees/create'],
  },
  {
    path: '/office/employees/create',
    label: 'Mitarbeitende anlegen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch'],
  },
  {
    path: '/office/catalogs',
    label: 'Kataloge',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: [
      '/office/catalogs/create',
      '/office/catalogs/workflow-builder',
    ],
  },
  {
    path: '/office/catalogs/create',
    label: 'Katalog anlegen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'billing'],
  },
  {
    path: '/office/catalogs/workflow-builder',
    label: 'Workflow-Builder',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager'],
  },
  {
    path: '/office/appointments',
    label: 'Termine',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/kalender',
    label: 'Kalender',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/invoices',
    label: 'Abrechnung',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: ['/office/budgets'],
  },
  {
    path: '/office/budgets',
    label: 'Budgets',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/documents',
    label: 'Dokumentenablage',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/documents-signatures',
    label: 'Dokumente & Unterschriften (Weiterleitung)',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/business/office/documents/signatures',
    label: 'Dokumente & Unterschriften',
    group: 'business',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: ['/business/office/documents/signatures/[id]'],
  },
  {
    path: '/business/office/documents/signatures/[id]',
    label: 'Dokumentanforderung',
    group: 'business',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/messages',
    label: 'Nachrichten',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: ['/office/messages/compose', '/office/messages/settings', '/office/messages/templates'],
  },
  {
    path: '/office/messages/settings',
    label: 'Einstellungen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/messages/templates',
    label: 'Vorlagen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/office/messages/compose',
    label: 'Nachricht verfassen',
    group: 'module',
    productKey: 'office',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/assist',
    label: 'Assist',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: [
      '/assist/assignments',
      '/assist/durchfuehrung',
      '/assist/nachweise',
      '/assist/fahrten',
      '/assist/calendar',
    ],
  },
  {
    path: '/assist/nachweise',
    label: 'Nachweise',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/assist/fahrten',
    label: 'Fahrtenbuch',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/assist/durchfuehrung',
    label: 'Durchführung',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/assist/assignments',
    label: 'Einsätze',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/assist/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'assist',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/pflege',
    label: 'Pflege',
    group: 'module',
    productKey: 'pflege',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
    children: [
      '/pflege/calendar',
      '/pflege/plans',
      '/pflege/vitalwerte',
      '/pflege/medikation',
      '/pflege/wunddokumentation',
      '/pflege/dokumentation',
      '/pflege/dienstplaene',
      '/pflege/sis',
      '/pflege/auswertungen',
      '/pflege/settings',
    ],
  },
  {
    path: '/pflege/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'pflege',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/pflege/kalender',
    label: 'Kalender',
    group: 'module',
    productKey: 'pflege',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/pflege/plans',
    label: 'Pflegepläne',
    group: 'module',
    productKey: 'pflege',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/pflege/vitalwerte',
    label: 'Vitalwerte',
    group: 'module',
    productKey: 'pflege',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
    ],
  },
  {
    path: '/beratung',
    label: 'Beratung',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
    children: [
      '/beratung/calendar',
      '/beratung/cases',
      '/beratung/protokolle',
      '/beratung/wiedervorlagen',
      '/beratung/auswertungen',
      '/beratung/settings',
    ],
  },
  {
    path: '/beratung/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/kalender',
    label: 'Kalender',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/cases',
    label: 'Fälle',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/protokolle',
    label: 'Protokolle',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/wiedervorlagen',
    label: 'Wiedervorlagen',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/auswertungen',
    label: 'Auswertungen',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/beratung/settings',
    label: 'Einstellungen',
    group: 'module',
    productKey: 'beratung',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'counselor'],
  },
  {
    path: '/akademie',
    label: 'Akademie',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
    children: [
      '/akademie/calendar',
      '/akademie/courses',
      '/akademie/teilnehmer',
      '/akademie/zertifikate',
      '/akademie/auswertungen',
      '/akademie/settings',
    ],
  },
  {
    path: '/akademie/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/kalender',
    label: 'Kalender',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/courses',
    label: 'Kurse',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/teilnehmer',
    label: 'Teilnehmer',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/zertifikate',
    label: 'Zertifikate',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/auswertungen',
    label: 'Auswertungen',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/akademie/settings',
    label: 'Einstellungen',
    group: 'module',
    productKey: 'akademie',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'akademie_admin'],
  },
  {
    path: '/stationaer',
    label: 'Stationär',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
    children: [
      '/stationaer/calendar',
      '/stationaer/bewohner',
      '/stationaer/wohnbereiche',
      '/stationaer/uebergabebericht',
      '/stationaer/auswertungen',
      '/stationaer/settings',
    ],
  },
  {
    path: '/stationaer/calendar',
    label: 'Kalender',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/kalender',
    label: 'Kalender',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/bewohner',
    label: 'Bewohner:innen',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/wohnbereiche',
    label: 'Wohnbereiche',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/uebergabebericht',
    label: 'Übergabebericht',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/auswertungen',
    label: 'Auswertungen',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/stationaer/settings',
    label: 'Einstellungen',
    group: 'module',
    productKey: 'stationaer',
    requiresAuth: true,
    allowedRoles: ['business_admin', 'business_manager', 'dispatch', 'nurse'],
  },
  {
    path: '/insight',
    label: 'InsightCenter',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
    children: ['/insight/snapshots', '/insight/exports', '/insight/data-sources'],
  },
  {
    path: '/insight/data-sources',
    label: 'Insight Datenquellen',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/insight/snapshots',
    label: 'Insight Snapshots',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },
  {
    path: '/insight/exports',
    label: 'Insight Exporte',
    group: 'business',
    requiresAuth: true,
    allowedRoles: [
      'business_admin',
      'business_manager',
      'billing',
      'dispatch',
      'nurse',
      'caregiver',
      'counselor',
      'akademie_admin',
    ],
  },

  {
    path: '/portal/employee',
    label: 'Mitarbeiterportal',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
    children: [
      '/portal/employee/assignments',
      '/portal/employee/documents',
      '/portal/employee/documents/signatures',
      '/portal/employee/messages',
      '/portal/employee/announcements',
    ],
  },
  {
    path: '/portal/employee/assignments',
    label: 'Einsätze',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/portal/employee/documents',
    label: 'Dokumente',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/portal/employee/documents/signatures',
    label: 'Dokumente & Unterschriften',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
    children: ['/portal/employee/documents/signatures/[id]'],
  },
  {
    path: '/portal/employee/documents/signatures/[id]',
    label: 'Dokument unterschreiben',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/portal/employee/messages',
    label: 'Nachrichten',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/portal/employee/announcements',
    label: 'Ankündigungen',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['employee_portal', 'caregiver', 'nurse'],
  },
  {
    path: '/portal/client',
    label: 'Klient:innenportal',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['client_portal', 'family_portal'],
    children: [
      '/portal/client/appointments',
      '/portal/client/documents',
      '/portal/client/messages',
      '/portal/client/announcements',
    ],
  },
  {
    path: '/portal/client/appointments',
    label: 'Termine',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['client_portal', 'family_portal'],
  },
  {
    path: '/portal/client/documents',
    label: 'Dokumente',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['client_portal', 'family_portal'],
  },
  {
    path: '/portal/client/messages',
    label: 'Nachrichten',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['client_portal', 'family_portal'],
  },
  {
    path: '/portal/client/announcements',
    label: 'Mitteilungen',
    group: 'portal',
    requiresAuth: true,
    allowedRoles: ['client_portal', 'family_portal'],
  },

  // Platform Console — eigene Guard-Kette (PlatformRouteGuard), keine Mandantenrollen
  { path: '/platform', label: 'Platform Console', group: 'system', requiresAuth: true },
  { path: '/platform/login', label: 'Platform Login', group: 'system', requiresAuth: false },
  { path: '/platform/dashboard', label: 'Platform Dashboard', group: 'system', requiresAuth: true },
  { path: '/platform/tenants', label: 'Platform Mandanten', group: 'system', requiresAuth: true },
  { path: '/platform/modules', label: 'Platform Module', group: 'system', requiresAuth: true },
  { path: '/platform/plans', label: 'Platform Tarife', group: 'system', requiresAuth: true },
  { path: '/platform/discounts', label: 'Platform Rabatte', group: 'system', requiresAuth: true },
  { path: '/platform/billing', label: 'Platform Billing', group: 'system', requiresAuth: true },
  { path: '/platform/payments', label: 'Platform Zahlungen', group: 'system', requiresAuth: true },
  { path: '/platform/feature-flags', label: 'Platform Feature Flags', group: 'system', requiresAuth: true },
  { path: '/platform/support', label: 'Platform Support', group: 'system', requiresAuth: true },
  { path: '/platform/audit', label: 'Platform Audit', group: 'system', requiresAuth: true },
  { path: '/platform/system', label: 'Platform System', group: 'system', requiresAuth: true },
  { path: '/platform/releases', label: 'Platform Releases', group: 'system', requiresAuth: true },
  { path: '/platform/forbidden', label: 'Platform 403', group: 'system', requiresAuth: false },
];

export function getRouteByPath(path: string): AppRoute | undefined {
  const normalized = path.split('?')[0].replace(/\/$/, '') || '/';
  const exact = APP_ROUTES.find((r) => r.path === normalized);
  if (exact) return exact;
  const byPrefix = [...APP_ROUTES]
    .filter((r) => r.path !== '/')
    .sort((a, b) => b.path.length - a.path.length)
    .find((r) => normalized.startsWith(`${r.path}/`) || normalized === r.path);
  return byPrefix;
}

export function getModuleRoutes(): AppRoute[] {
  return APP_ROUTES.filter((r) => r.group === 'module');
}

export function getLoginRouteForGroup(group: RouteGroup): string {
  switch (group) {
    case 'portal':
      return '/auth/employee-login';
    case 'business':
    case 'module':
      return '/auth/business-login';
    default:
      return '/auth/business-login';
  }
}
