import { useEffect, useRef, useState, type ReactNode } from 'react';
import { consoleCsv } from '@/lib/platformConsole/consoleWorkspaceModel';

export const CONSOLE_WORKSPACE_CSS = `
.cs-console{--cs-ink:#142b49;--cs-muted:#526580;--cs-line:#d8e3f0;--cs-blue:#075dd5;color:var(--cs-ink);font-family:inherit;font-size:15px;line-height:1.55;min-width:0;display:flex;flex-direction:column;gap:22px}
.cs-console *{box-sizing:border-box}.cs-console h2,.cs-console h3,.cs-console p{margin:0}.cs-console h2{font-size:24px;line-height:1.25;letter-spacing:-.5px}.cs-console h3{font-size:17px;line-height:1.4}.cs-console small,.cs-muted{color:var(--cs-muted)}
.cs-hero{padding:28px;border:1px solid #c8d9ed;border-radius:22px;background:linear-gradient(115deg,#eef6ff 0%,#fff 65%,#e8f3ff 100%);display:flex;gap:24px;align-items:center;justify-content:space-between}.cs-hero p{max-width:780px;margin-top:9px;color:var(--cs-muted)}.cs-eyebrow{color:var(--cs-blue);font-size:12px;letter-spacing:1.8px;text-transform:uppercase;font-weight:800;margin-bottom:9px}.cs-price{flex-shrink:0;text-align:center;border:1px solid #c7d9ef;background:#fff9;border-radius:18px;padding:15px 22px}.cs-price strong{display:block;font-size:30px;color:var(--cs-blue)}
.cs-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,175px),1fr));gap:14px}.cs-stat{padding:18px 20px;border:1px solid var(--cs-line);border-radius:17px;background:#fff;min-width:0;box-shadow:0 4px 18px #19345505}.cs-stat strong{display:block;font-size:27px;letter-spacing:-.5px;line-height:1.4;overflow-wrap:anywhere}.cs-stat span{font-size:13px;color:var(--cs-muted)}.cs-stat small{display:block;font-size:11px;margin-top:5px}
.cs-panel{border:1px solid var(--cs-line);border-radius:19px;background:#fff;min-width:0;overflow:hidden}.cs-panel-head{padding:21px 23px;border-bottom:1px solid #e7eef6;display:flex;flex-wrap:wrap;gap:12px;align-items:center;justify-content:space-between}.cs-panel-body{padding:23px;display:flex;flex-direction:column;gap:17px}.cs-toolbar{display:flex;flex-wrap:wrap;gap:12px;align-items:end}.cs-toolbar>label{flex:1;min-width:min(100%,180px)}
.cs-field{display:flex;flex-direction:column;gap:6px;font-size:13px;font-weight:700;min-width:0}.cs-field small{font-weight:400}.cs-console input,.cs-console select,.cs-console textarea{font:inherit;font-size:15px;line-height:1.5;color:var(--cs-ink);border:1px solid #bccde0;background:#fff;border-radius:10px;padding:10px 12px;width:100%;min-width:0}.cs-console textarea{min-height:104px;resize:vertical}.cs-console input:focus,.cs-console select:focus,.cs-console textarea:focus{outline:3px solid #8ebaff80;border-color:#075dd5}.cs-console button{font:inherit;font-size:14px;line-height:1.4;cursor:pointer}.cs-btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;min-height:42px;padding:10px 16px;border:1px solid #c9d7e8;background:#fff;color:#144980;border-radius:10px;font-weight:700;text-decoration:none}.cs-btn:hover{background:#eef5ff;border-color:#83a9d9}.cs-btn:focus-visible,.cs-link:focus-visible,.cs-tab:focus-visible{outline:3px solid #7faefa;outline-offset:3px}.cs-btn.primary{background:#075dd5;border-color:#075dd5;color:#fff;box-shadow:0 5px 12px #075dd526}.cs-btn.danger{color:#ad2626;border-color:#e3b9b9;background:#fff6f5}.cs-btn:disabled{opacity:.48;cursor:default;box-shadow:none}.cs-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.cs-link{background:none;border:0;color:#075dd5;text-decoration:underline;text-underline-offset:3px;padding:3px 0;text-align:left;font-weight:700;overflow-wrap:anywhere}
.cs-table-scroll{overflow:auto;max-width:100%}.cs-table{border-collapse:collapse;width:100%;font-size:14px;text-align:left;min-width:680px}.cs-table th{background:#f3f7fc;color:#49607d;font-size:12px;font-weight:800;padding:13px 19px;white-space:nowrap;border-bottom:1px solid var(--cs-line)}.cs-table td{padding:17px 19px;border-bottom:1px solid #e8eef6;vertical-align:top;max-width:360px;overflow-wrap:anywhere}.cs-table tr:last-child td{border-bottom:0}.cs-table tbody tr:hover{background:#f7faff}.cs-table td small{display:block;margin-top:3px}.cs-table .cs-btn{min-height:34px;font-size:12px;padding:7px 10px}.cs-pager{padding:15px 20px;border-top:1px solid var(--cs-line);display:flex;flex-wrap:wrap;gap:14px;align-items:center;justify-content:space-between;font-size:13px;color:var(--cs-muted)}
.cs-badge{display:inline-flex;gap:6px;align-items:center;padding:4px 9px;border-radius:7px;background:#eef3fa;color:#435d7c;font-size:12px;font-weight:750;white-space:nowrap}.cs-badge.good{background:#e9f7f0;color:#176748}.cs-badge.warn{background:#fff2d9;color:#835510}.cs-badge.bad{background:#fff0ef;color:#a1342b}.cs-badge.blue{background:#eaf2ff;color:#125fae}.cs-notice{padding:14px 18px;border:1px solid #cddff6;border-radius:12px;background:#f1f7ff;font-size:14px;color:#254e78}.cs-notice.error{border-color:#efc7c5;background:#fff3f2;color:#92362f}.cs-notice.success{border-color:#b9dfcc;background:#ecfaf2;color:#256145}.cs-empty{padding:42px 24px;text-align:center;display:flex;flex-direction:column;gap:11px;align-items:center}.cs-empty p{color:var(--cs-muted);max-width:600px}.cs-columns{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr));gap:20px}.cs-kv{display:grid;grid-template-columns:minmax(100px,1fr) minmax(0,2fr);gap:8px 20px;margin:0}.cs-kv dt{color:var(--cs-muted);font-size:13px}.cs-kv dd{margin:0;white-space:pre-wrap;overflow-wrap:anywhere;font-size:14px}.cs-task{padding:15px;border:1px solid var(--cs-line);border-radius:12px;display:flex;align-items:center;justify-content:space-between;gap:14px}.cs-task strong{font-size:22px}.cs-task p{font-size:13px;color:var(--cs-muted)}
.cs-dialog{border:1px solid #c8d8ed;border-radius:23px;box-shadow:0 25px 100px #10274440;padding:0;width:calc(100% - 32px);max-width:880px;max-height:calc(100dvh - 36px);color:var(--cs-ink);background:#fff;overflow:auto}.cs-dialog::backdrop{background:#0c214a85;backdrop-filter:blur(8px)}.cs-dialog .cs-console{gap:0}.cs-dialog-head{padding:24px 28px;border-bottom:1px solid var(--cs-line);display:flex;justify-content:space-between;align-items:start;gap:20px;position:sticky;top:0;background:#fff;z-index:1}.cs-dialog-head p{margin-top:7px;color:var(--cs-muted);font-size:14px}.cs-dialog-body{padding:26px 28px;display:flex;flex-direction:column;gap:22px}.cs-dialog-footer{padding:18px 28px;border-top:1px solid var(--cs-line);display:flex;flex-wrap:wrap;justify-content:space-between;gap:14px;align-items:center;background:#f8fbff;position:sticky;bottom:0;z-index:1}.cs-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:19px}.cs-form-grid .wide{grid-column:1/-1}.cs-tabs{display:flex;flex-wrap:wrap;gap:7px;border-bottom:1px solid var(--cs-line);padding-bottom:12px}.cs-tab{padding:8px 13px;background:#f2f6fc;border:1px solid transparent;color:#415e80;border-radius:8px;font-weight:700}.cs-tab[aria-selected=true]{background:#eaf2ff;border-color:#94b7e6;color:#075dd5}.cs-code{font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f8fc;border:1px solid var(--cs-line);padding:15px;border-radius:10px;margin:0;max-height:360px;overflow:auto}.cs-loading{height:3px;background:linear-gradient(90deg,#eaf2ff,#1768df,#eaf2ff);background-size:200%;animation:cs-progress 1.3s linear infinite;border-radius:6px}.cs-busy-copy{font-size:13px;color:#415e80}.cs-role-table{min-width:540px}.cs-role-table td,.cs-role-table th{padding:10px 13px}.cs-right{text-align:right}@keyframes cs-progress{to{background-position:-200% 0}}
@media(max-width:680px){.cs-hero{padding:20px;align-items:flex-start;flex-direction:column}.cs-price{display:flex;gap:12px;align-items:center;padding:8px 14px}.cs-price strong{font-size:22px}.cs-panel-head,.cs-panel-body{padding:17px}.cs-form-grid{grid-template-columns:1fr}.cs-dialog-head,.cs-dialog-body{padding:19px}.cs-dialog-footer{padding:16px 19px}.cs-dialog{width:calc(100% - 16px);max-height:calc(100dvh - 16px)}.cs-kv{grid-template-columns:1fr}.cs-kv dd{margin-bottom:10px}.cs-toolbar{align-items:stretch}.cs-toolbar>label{flex-basis:100%}.cs-console h2{font-size:21px}.cs-stat strong{font-size:23px}}
@media(prefers-reduced-motion:reduce){.cs-loading{animation:none}}
`;

export function ConsoleStyle() { return <style>{CONSOLE_WORKSPACE_CSS}</style>; }
export function ConsoleBadge({ value, label }: { value: unknown; label: string }) {
  const text = String(value);
  const tone = ['active','available','succeeded','paid','ready','live','manual_free','true'].includes(text) ? 'good' : ['failed','suspended','revoked','chargeback','locked','false'].includes(text) ? 'bad' : ['past_due','pending','onboarding','scheduled','beta','partially_paid'].includes(text) ? 'warn' : 'blue';
  return <span className={`cs-badge ${tone}`}>{label}</span>;
}
export function ConsoleDialog({ title, description, children, footer, busy = false, onClose }: { title: string; description?: string; children: ReactNode; footer?: ReactNode; busy?: boolean; onClose: () => void }) {
  const ref = useRef<HTMLDialogElement>(null);
  const close = useRef(onClose); close.current = onClose;
  useEffect(() => { const dialog = ref.current; if (!dialog) return; dialog.showModal(); return () => { dialog.close(); }; }, []);
  return <dialog ref={ref} className="cs-dialog" aria-label={title} aria-busy={busy} onCancel={event => { event.preventDefault(); if (!busy) close.current(); }}>
    <div className="cs-console"><ConsoleStyle /><div className="cs-dialog-head"><div><div className="cs-eyebrow">CareSuite · Platform Console</div><h2>{title}</h2>{description && <p>{description}</p>}</div><button className="cs-btn" aria-label="Dialog schließen" disabled={busy} onClick={onClose}>✕</button></div>
      {busy && <div className="cs-loading" role="progressbar" aria-label="Änderung wird gespeichert" />}
      <div className="cs-dialog-body">{children}</div>{footer && <div className="cs-dialog-footer">{footer}</div>}
    </div>
  </dialog>;
}
export function ConsoleStats({ items }: { items: { label: string; value: ReactNode; hint?: string }[] }) {
  return <div className="cs-stats">{items.map(item => <div className="cs-stat" key={item.label}><span>{item.label}</span><strong>{item.value}</strong>{item.hint && <small>{item.hint}</small>}</div>)}</div>;
}
export function ConsolePanel({ title, description, children, actions }: { title: string; description?: string; children: ReactNode; actions?: ReactNode }) {
  return <section className="cs-panel"><div className="cs-panel-head"><div><h3>{title}</h3>{description && <small>{description}</small>}</div>{actions}</div>{children}</section>;
}
export function downloadConsoleCsv(name: string, headers: string[], rows: unknown[][]) {
  const url = URL.createObjectURL(new Blob([consoleCsv(headers, rows)], { type: 'text/csv;charset=utf-8' }));
  const link = document.createElement('a'); link.href = url; link.download = `${name}-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(link); link.click(); link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
export function ConsoleJson({ value }: { value: unknown }) { return <pre className="cs-code">{JSON.stringify(value, null, 2) ?? 'Keine Daten'}</pre>; }
export function ConsoleTabs({ tabs, children }: { tabs: string[]; children: (tab: string) => ReactNode }) {
  const [active, setActive] = useState(tabs[0]);
  return <><div className="cs-tabs" role="tablist">{tabs.map(tab => <button role="tab" aria-selected={active === tab} className="cs-tab" key={tab} onClick={() => setActive(tab)}>{tab}</button>)}</div><div role="tabpanel">{children(active)}</div></>;
}
